### ISSUE TITLE
SUGGESTION: Use explore function on nested results

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#1005]
Take the following example:

```graphql
{
  Get{
    Things{
      Publication(where:{
        path: ["HasArticles", "Article", "title"],
        operator: Equal,
        valueString: "Wired"
      }){
        name
        HasArticles(explore: { # < == SUGGESTION
          concepts: ["games"]
        }){
          ... on Article{
            title
          }
        }
      }
    }
  }
}
```

The suggestion is to organize the results based on the concepts related to the Articles, not to the publication.

**Comment by etiennedi** [comment]
Is this different from #971 or a duplicate?

**Comment by bobvanluijt** [comment]
Aha, duplicate.

**Comment by etiennedi** [comment]
Ok, in this case I'm closing here in favor of the original issue. Please also note the open question there: https://github.com/semi-technologies/weaviate/issues/971#issuecomment-529814879.
