### ISSUE TITLE
Allow classifications of over 9999 items

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1009]
The classification feature (#976) is limited to 9999 as it does not implement any kind paging/queuing logic. Instead it tries to get all unclassified ids in a single request. This limits the classification size to a single request size (max 9999).

## Goal

Overcome this limit to allow classifications of any size

**Comment by bobvanluijt** [comment]
Very relevant, @michaverhagen how many are you dealing with on average?

**Comment by michaverhagen** [comment]
I am now working with a dataset of 22K items. However, I am using the 22K to test, I am doing that in batches of 5K items.

**Comment by bobvanluijt** [comment]
@etiennedi ⬆️proved te relevance 😄

**Comment by bobvanluijt** [comment]
@michaverhagen will this limitation cause an issue in the short-term?

**Comment by michaverhagen** [comment]
No, so far we have been able to work around it quite easily
