### ISSUE TITLE
Bug: Classification with distanceWinning == 0 omits distance

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1011]
A common issue around `go-swagger` and json marshalling in general when the `omitEmpty` prop is set. If the value is a perfect `0` it is omitted in the JSON (both when storing the entry in the db, as well as when presenting to the user)

## Todo
* [ ] make `distanceWinning` a pointer type so it can be explicitly set to `0` without being omitted.

**Comment by bobvanluijt** [comment]
Is this resolved?
