### ISSUE TITLE
Get unknown words from c11y

### ISSUE THREAD

**Issue by fefi42** [semi-technologies/weaviate#1026]
There are some requests to add new words and synonyms to the c11y #1007 #946 for the workflow of adding new words and improving the results the user needs to be informed of what words are currently not supported.

Suggestion a request for a specific class and property that returns all the unknown words.
```
GET v1/words/unknown {
  class: "Training"
  property: "instruction"
}
==> {
  unknown: [ wwm, supersetted, ...]
}
```

This helps the workflow since these unknown words can now easily be added as synonyms.

**Comment by etiennedi** [comment]
I think this might also fit well into the existing `meta` option for a regular `GET /v1/things/<id>`. When we added the `meta` through `?meta=true` we only included classification meta, but argued that this field could contain all kinds of meta info. I think this would fit well.
