### ISSUE TITLE
Index: false should only include Explore{} function

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#1031]
If a property isn't indexed, the `where` filter can't be used on this property. It results in:

```
"message": "explorer: get class: vector search: vector search: request is error: status: 400 Bad Request, type: search_phase_execution_exception, reason: all shards failed, shards: Cannot search on field [soortKorting] since it is not indexed.",
```

In this case, the query who was expected to succeed was:

```
{
  Get{
    Things{
      Product(
        where: {
          operator: Equal
          path: ["soortKorting"]
          valueString: "FOOBAR"
        }
        explore: {
          concepts: ["Pepsi"]
        }
        limit: 10
      ){
        titel
        zoekMachineOmschrijving
        korting
        soortKorting
      }
    }
  }
}
```

**Comment by etiennedi** [comment]
This [works as designed](https://github.com/semi-technologies/weaviate/issues/952#issuecomment-522514618) so I'm removing the bug label. We can then use this issue to discuss if we want to alter the behavior.

**Comment by bobvanluijt** [comment]
Whoops, my mistake.

I think that _only_ not indexing while determining the vector representation would be good. Unless there is another upside that I'm missing.

**Comment by etiennedi** [comment]
The upside that I see is that the less is contained in the current "text based" index, the better it performs and fewer resources it requires. This doesn't matter on 5000 or 10000 items, but it will make a difference on really large sets.

A pattern I've seen is some of our use cases looks something like

```
Article
  raw: "some string containng <html> or <xml>"
  parsed: "the same string, but parsed"
```

For this, we don't really need to spam our index with the `raw` field, if we know that all searches would be performed on the `parsed` field. So I definitely see value in allowing a full no-index as is the case right now.

So I see value in having the following options:
- full index (both vector and text-based)
- only text (the case you're looking for)
- not indexed at all (for the case I outlined above)
