### ISSUE TITLE
Allow end-user to create schema class or property without c11y validation

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#1040]
When a user creates a schema item it should be accepted even if the c11y does not contain one of the words used. I.e., all schema classes and properties should be accepted.

**Comment by etiennedi** [comment]
@bobvanluijt Should the above always be true for everyone, or should there be a config setting (with a default for one or the other?) Where if the flag is set, behavior is as is current, but if the flag is not set, the above becomes possible?

**Comment by bobvanluijt** [comment]
A config setting is of course great. But I would see that it would be true by default. It seems that people get confused otherwise.

**Comment by etiennedi** [comment]
Implemented as part of #1062
