### ISSUE TITLE
Scroll API to iterate over results of a query

### ISSUE THREAD

**Issue by fefi42** [semi-technologies/weaviate#1043]
It is currently not possible to iterate over all results of a query in pages/batches.
Goal is to have all results of a query with no duplicates in smaller pages.

**Comment by etiennedi** [comment]
This is non-trivial in the NoSQL world, as we can't simply do something like `from: 500, size: 100`. Elasticsearch supports that, but only up to 10,000 items. However, that is also our current limit for a single query, so we wouldn't win anything.

At the same time we shouldn't build anything that is entirely specific to Elasticsearch, as that would make replacing Elasticsearch as a backend much harder. So I think we need some sort of a generic hash for current page, previous page and next page. 

In REST I could easily imagine this as headers and parameters. For example

```
GET /v1/things/?size=100&page=eyJmb28iOiJiYXIifQo=
X-Current-Page: eyJmb28iOiJiYXIifQo=
X-Next-Page: eyJiYXIiOiJuZXh0In0K

[ /* payload */ ]
```

For GraphQL this will be a lot trickier without introducing a breaking change. Anyone have an idea?

**Comment by bobvanluijt** [comment]
Still a request that keeps popping up...

**Comment by bobvanluijt** [comment]
@etiennedi will the new DB change the difficulty of this feature?

**Comment by etiennedi** [comment]
Yes and no.

With the new setup it should be quite trivial to dump all indices. So the usecase of "give me all entries" becomes easier. But a real pagination (through the entire dataset) like in an RDBMS isn't something a distributed database is ever good at. We could also build something like a cursor API - that should work, but doesn't come free.

**Comment by bobvanluijt** [comment]
Could you give some more context about the cursor API in this context.
