### ISSUE TITLE
Allow custom extension words as classnames

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1050]
Note: this only applies if the setting to be introduced in #1040 is set to off.

**Comment by etiennedi** [comment]
TODO: Check if we might have already solved this in 0.21.9. Background is that https://github.com/semi-technologies/contextionary/issues/20 includes custom extensions in the `IsWordPresent()` method of the c11y. Since this method it probably called to check if a word is present when creating class names, this issue might also be solved.

tl;dr: Verify

**Comment by bobvanluijt** [comment]
Still relevant
