### ISSUE TITLE
Like should ignore casing

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#1055]
Currently, casing is taken into account for the `where = Like` filter.

```
{
  Get {
    Things {
     	Article(
      where: {
        valueString: "*Money*"
        operator: Like
        path: ["title"]
      }
```

Ideally, casing should not play are role.

**Comment by etiennedi** [comment]
I just verified this with two different cases. This depends on the property type (which ultimately boils down to how elastic treats them).

Property type `string` -> Casing is kept in the index, you also need specify the correct casing on your wildcard query
Property type `text` -> Everything is lowercased at index time, you can specify all lowercase in your query

This makes sense to me, as `string` is only meant for really exact matches like an ID or hash (where a lowercase letter could be a completely different result from an uppercase). Whereas `text` is meant for  human-readable text where `Apple` and `apple` is most likely the same word.

**Comment by bobvanluijt** [comment]
Check, thanks.
