### ISSUE TITLE
Request: Czech Contextionary

### ISSUE THREAD

**Issue by viktorbezdek** [semi-technologies/weaviate#1059]
Are there any notes what needs to be done and what kind of datasets are necessary? 

Weaviate lacks support for Czech language. I'd be happy to contribute it with a little guidance. Lingual research centers at our universities offers [various large datasets](https://lindat.mff.cuni.cz/repository/xmlui/discover?rpp=10&etal=0&group_by=none&page=2&filtertype_0=type&filtertype_1=language&filter_relational_operator_1=equals&filter_relational_operator_0=equals&filter_1=Czech&filter_0=corpus) which seems to the crucial part.

Thanks for any hints.

**Comment by etiennedi** [comment]
Hello @viktorbezdek,

happy new year and thank you for your patience - most of the team was on vacation for the past two weeks.

Weaviate itself is agnostic of languages, but the contextionary is specific to languages. So far we have only provided `en`, `nl`, `de` and a couple of experimental ones, but we can easily add support for czech as well. The process of training a particular contextionary db is not open-source at the moment, so we can't accept contributions there. But the good news it's just a matter of starting a new run.

Does your use-case mix czech and english or is it czech only? All stable releases so far have been single-language, but we have also experimented with cross-language contextionaries. However, the quality is not the same yet as that of a single-language one. So I'd recommend to go czech-only if that works for you?

**Comment by bobvanluijt** [comment]
Hi @viktorbezdek,

- As an addition to @etiennedi's point. We can make one available in Czech and it would be great if you can help and validate for we don't have any Czech knowledge ;-)
- We can also mix it with e.g. English.

It would be awesome if you can contribute by helping to invalidate the new C11y :-)

Bob

**Comment by viktorbezdek** [comment]
Hi @bobvanluijt and @etiennedi, 

first of all - happy New Year. 

About use cases - I have two at the moment. The first one would be Czech/English and the second one will need just Czech. Do you need any details on the projects? I can provide them for you if it helps.

I'd be more than happy to validate Czech and help improve the already awesome tool you made.

**Comment by bobvanluijt** [comment]
Thanks, @viktorbezdek! That would be awesome. We can train them and make 'em available.

If you want to, you can [sign up](https://www.semi.technology/newsletter/) here where we can inform people when something new is available :-)

**Comment by viktorbezdek** [comment]
Signed up. Thanks for the tip, @bobvanluijt 👍 

You will notify users when new C11y is ready via the mailing list or you'll ping me here? Do you have any idea when the training could be done? Not pushing, just excited 😉

**Comment by bobvanluijt** [comment]
Cool, thanks @viktorbezdek.

I think @etiennedi can help answer the release question.

**Comment by bobvanluijt** [comment]
@viktorbezdek FYI we did not forget, just a small delay :)

**Comment by viktorbezdek** [comment]
@bobvanluijt Patiently waiting >]

**Comment by etiennedi** [comment]
@viktorbezdek  Please see the [current release](https://github.com/semi-technologies/weaviate/releases/tag/0.22.4) which includes a Czech contextionary. I'm leaving this issue open until looking forward to your feedback. Thanks.

**Comment by bobvanluijt** [comment]
@viktorbezdek https://www.semi.technology/documentation/weaviate/current/get-started/install.html#weaviate-with-a-czech-contextionary

Please let us know if it works for your case, we can also mix it with other languages if that helps (e.g., with English).
