### ISSUE TITLE
New concept not available on c11y/concepts endpoint

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#1061]
How to reproduce:

`GET http://localhost:8080/v1/c11y/concepts/kubectl`

Result (i.e., not found, we might actually want to show that):

```json
{
    "individualWords": [
        {
            "word": "kubectl"
        }
    ]
}
```

then: `POST http://localhost:8080/v1/c11y/extensions` with data object:

```json
{
  "concept": "kubectl",
  "definition": "The CLI tool to administer Kubernetes clusters",
  "weight": 1
}
```

Now, when running `GET http://localhost:8080/v1/c11y/concepts/kubectl` again. The result is still:

```json
{
    "individualWords": [
        {
            "word": "kubectl"
        }
    ]
}
```

The expected result is to find the actual data objects related to a word that's found.

**Comment by etiennedi** [comment]
fixed in 0.21.9 (https://github.com/semi-technologies/weaviate/commit/74485a797ec2bab1195a0b45983dd96b45a942d0)
