### ISSUE TITLE
Index settings not visible on /v1/schema

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#1067]
- `vectorizePropertyName`
- `vectorizeClassName`
- `index`

Are not shown on the `/v1/schema` endpoint which makes it difficult to validate if a schema was imported correctly.

**Comment by bobvanluijt** [comment]
Curious to know the status of this, it is handy to see this when developing.

cc: @michaverhagen

**Comment by etiennedi** [comment]
They should be visible, however `go-swagger` hides fields that have their default value by default. So `vectorizePropertyName` will not be shown if set to false, `vectorizeClassName` will not be shown unless explicitly set, etc.

**Comment by etiennedi** [comment]
Looks like they did some work on this in December last year, I'll look into whether we can easily make them always visible now: https://github.com/go-swagger/go-swagger/pull/2148

**Comment by bobvanluijt** [comment]
Good to know, this will be helpful.

**Comment by michaverhagen** [comment]
I just ran into this same issues - I had set all class names to not be vectorized, but could not see that setting in the schema endpoint

**Comment by bobvanluijt** [comment]
> They should be visible, however `go-swagger` hides fields that have their default value by default. So `vectorizePropertyName` will not be shown if set to false, `vectorizeClassName` will not be shown unless explicitly set, etc.

@etiennedi I can confirm that this assumption is incorrect. The three keys mentioned above are never visible regardless of their values.

**Comment by etiennedi** [comment]
Thanks for the update, I'll investigate what's going on.

**Comment by etiennedi** [comment]
> @etiennedi I can confirm that this assumption is incorrect. The three keys mentioned above are never visible regardless of their values.

I've also just tried and for me it's exactly as described in the assumption:

```
curl localhost:8080/v1/schema/ | jq
  {
        "class": "Post",
        "properties": [
          {
            "dataType": [
              "text"
            ],
            "name": "content"
          },
          {
            "dataType": [
              "boolean"
            ],
            "name": "training"
          },
          {
            "dataType": [
              "Category"
            ],
            "name": "ofCategory"
          },
          {
            "dataType": [
              "MainCategory"
            ],
            "name": "ofMainCategory"
          },
          {
            "dataType": [
              "string"
            ],
            "name": "controlCategoryId"
          },
          {
            "dataType": [
              "string"
            ],
            "name": "controlMainCategoryId",
            "vectorizePropertyName": true <============================
          }
        ],
        "vectorizeClassName": false <============================
      }
```

**Comment by etiennedi** [comment]
closing as obsolete
