### ISSUE TITLE
Decision tree

### ISSUE THREAD

**Issue by fefi42** [semi-technologies/weaviate#1072]
Classification based on descriptions can be hard if the descriptions are very short or contain a lot of custom domain words. In such cases a context is hard to find and a decision-tree can be a powerful tool. 

I am not sure how a decision tree could be realized. One suggestion is to use one text property of a class as the input and then have a reference to a label (like in other classifications). Then build the tree with all the objects that have the label set. And predict them for the other objects.

Another way would be that the input is a (many) reference to multiple tokens that are taken as tree input.

**Comment by etiennedi** [comment]
We can use this spike I did a few months ago as a start: https://github.com/etiennedi/gocart

The algorithm above could run after n elements are loaded into memory, similar to how we currently do that for contextual and knn classifications.
