### ISSUE TITLE
SUGGESTION: Automatic abbreviation matching

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1076]
## Goal

* Extend the c11y for the most important abbreviations automatically
* Specific to the imported dataset, not general language

## Example

* Dataset contains "wlb" which is an abbreviation for "wellbore", but this is not reflected in the contextionary
* We want to end up with a custom c11y extension for `wlb => wellbore` without manually adding this

## Algorithm
1. Search the entire dataset for words with length <= l (e.g. l=4). The idea is that anything shorter than the defined threshold might be a custom abbreviation
2. Build a regular expression based on the abbrevation. E.g. `^w.*l.*b.*$` for `wlb`. The idea is that the abbreviation will always start with the same letter, for the remaining letters we won't know where they appear, but they must appear in the correct order
3. Apply regex onto c11y word list (For the wlb example this returns 377 results)
4. Check the entire dataset for potential matches, sort by occurrence
5. If top item occurs more often than x, set a custom extension for (abbr => top item), e.g. (wlb => wellbore). (x is configurable and defaults to something reasonable, e.g. 5)
6. reindex entire dataset so that on next run wlb is vectorized as a synonym for wellbore 

## Additions to further improve:
* After step 1 remove all words with occurrence larger than x, as the assumption is that a very common short words (such as "this", "are", "one", ...) arent synonyms, but a non-sensical abbreviation is
* In addition to the above regex in step 2, we could also match something like `k8s` for `^k.{8}s$` to potentially match `kubernetes`.

Thoughts?

**Comment by fefi42** [comment]
What happens when `wlb` is actually part of the contextionary but just not in the context of wellbore. E.g. in the context of `work-life-balance` or `Wiener Lokalbahnen`. Do you plan to regex search on all words? Or all words within a certain length like up to 4 letters?

**Comment by etiennedi** [comment]
I'd suggest to use every word up to 4 letters regardless of whether it's known to the c11y or not. The underlying assumption is that if we have `wlb` in the dataset and the word `wellbore` is present in the dataset a lot, then `wlb` will mean `wellbore`. The same word could mean `Wiener Lokalbahnen` on a different dataset if in that priituclar dataset the term `Wiener Lokalbahnen` was more frequent than `wellbore`.

**Comment by bobvanluijt** [comment]
Intuitively this seems great. Maybe make the arbitrary 4-letter-rule variable for different languages or to disable it by setting it to `0`?
