### ISSUE TITLE
DISCUSSION: Numbers in strings

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1077]
**Please do not suggest solutions yet, I'd like to first gather the problems we have**

## Problem Statement

In the recent past we've repeatedly seen usecases where numbers are embedded in strings and we often lose semantic meaning if we are using any vector-based mechanisms (explore search, entity merging, classficiation, ...) on it.

Often these fields are human-written free text fields labelled "description", an example would be: "Nuka Cola Can 33cl"

Based on the above description here are some queries that currently would not work:

### Numbers in explore search
Query: `explore: { concepts: ["cola 33"] }`

Issues:
* Numbers are ignored in vectors, so the above query would not be closer or farther from "cola 50cl" than from "cola 33cl"

Desired Outcome:
* An explore search ranks "Nuka Cola 33cl" before "Nuka Cola 50cl"

Notes:
* The example uses search, but it would also apply for classifications or entity merging

### Numbers with SI units
Query: Regardless of explore or structured "cola 330ml"

Issues:
* We don't parse or recognize units
* We do not recognize a connection between "330ml" and "33cl"

Desired Outcome:
* When searching for "33cl", the results should include matches for "330ml" and "0.33l"

Notes:
* The example uses search, but it would also apply for classifications or entity merging

### Fuzzy numbers
Query: Regardless of explore or structured "cola 30cl"

Issues:
* Dataset doesn't contain anything for 30cl, only for 33cl
* No unit parsing as outlined above

Desired Outcome:
* In a search the closes result (top) should be 33cl, followed by 50cl, followed by 60cl (i.e. numbers are ranked on their difference to the target number"

Notes:
* The example uses search, but it would also apply for classifications or entity merging

**Comment by bobvanluijt** [comment]
Somewhat related: https://github.com/semi-technologies/weaviate/issues/1078

**Comment by bobvanluijt** [comment]
Could this somehow be related to https://github.com/semi-technologies/weaviate/issues/1076?

I was thinking about this because `cl` would match the `< 4` letter rule.
