### ISSUE TITLE
QUESTION: Are individual words in multiple word based extensions extended?

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#1079]
Let's take the following example:

```
POST /v1/c11y/extensions

{
  "concept": "Winlogon Helper DLL",
  "definition": "...",
  "weight": 1
}
```

In this result, `Winlogon Helper DLL` is seen as a single concept. But does it also relocate the definitions of: `Winlogon`, `Helper` and `DLL`?

It would be great that -for example- the word 'helper' now also moves into the direction of `Winlogon Helper DLL`. Or would this already be the case based on the definition?

**Comment by etiennedi** [comment]
@bobvanluijt to add some more detailed examples.
