### ISSUE TITLE
SUGGESTION: Recalculate vectors after adding new extensions

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#1080]
Currently, an entity object has a vector representation.

If an extension is added via the c11y endpoint, it would be great if the vector representations are re-calculated if the word(s) of the extension are/is part of the entity.

Maybe there should be an option to disable this.

```
POST /v1/c11y/extensions

{
  "concept": "Winlogon Helper DLL",
  "definition": "foobar",
  "weight": 1,
  "reindex": false // <== default = true
}
```

**Comment by bobvanluijt** [comment]
Extention of this request.

Take the following example where _two_ new concepts are added.

```JSON
POST /v1/c11y/extensions

{
  "concept": "bazbaq",
  "definition": "An example to explain what an foobarqaz is",
  "weight": 1
}
```

```JSON
POST /v1/c11y/extensions

{
  "concept": "foobarqaz",
  "definition": "An example to explain this issue and often used in combination with a bazbaq",
  "weight": 1
}
```

Note how the _first_ addition contains `foobarqaz` which is an unknown word. However, after adding the second word, it should know this word.

What I would like to propose is:

1. If a concept contains a word that it previously couldn't index, but now can, should be reindexed.
2. If a thing or action contains a word that it previously couldn't index, but now can, should be reindexed.

Any thoughts @etiennedi ?

**Comment by bobvanluijt** [comment]
Friendly nudge @etiennedi

**Comment by fefi42** [comment]
@bobvanluijt How would you solve circular dependencies?

**Comment by bobvanluijt** [comment]
> @fefi42 How would you solve circular dependencies?

It doesn't (yet) the goal is to start the discussion, especially with the [custom DB](https://github.com/semi-technologies/weaviate/milestone/10) this becomes interesting to have as a functionality.

Feel free to add suggestions to this issue ;-)
