### ISSUE TITLE
Italian contextionary

### ISSUE THREAD

**Issue by andreabat** [semi-technologies/weaviate#1084]
Hi, great idea, promising technology!
Would love to build some use cases and demo your product in Italian.
As you indicated on various talks, can you please generate it?

**Comment by bobvanluijt** [comment]
Thanks @andreabat, it is on our list :)

Would be great to get your help validating it. 🙏

**Comment by andreabat** [comment]
Will do.thanks a lot.

**Comment by etiennedi** [comment]
Please see the [current release](https://github.com/semi-technologies/weaviate/releases/tag/0.22.4) which includes an italian contextionary. I'm leaving this issue open until looking forward to your feedback. Thanks.

**Comment by bobvanluijt** [comment]
@andreabat, we will also publish it in the docs tomorrow, I'll let you know you here.

**Comment by bobvanluijt** [comment]
@andreabat https://www.semi.technology/documentation/weaviate/current/get-started/install.html#weaviate-with-an-italian-contextionary

Please let us know if it works for your case, we can also mix it with other languages if that helps (e.g., with English).

**Comment by andreabat** [comment]
Hi, sorry but I didn't receive any notifications from GitHub regarding this issue, and came back just in case! So j will dive deep into it Right away.

**Comment by bobvanluijt** [comment]
Cool, thanks @andreabat. Also reached out to you over email :-)

**Comment by andreabat** [comment]
Finally got a chance to install . Having some issues with elasticsearch complaining for limited disk space ( i'm using  docker compose) and not sure how to solve since I do have space available. I am currently, using this command to remove alarms ( temporarily...a few seconds), before trying to input data.

curl -XPUT -H "Content-Type: application/json" http://localhost:9201/_all/_settings -d '{"index.blocks.read_only_allow_delete": null}'

In the meantime I have create a simple schema ( Attore  - Film ) but not sure how to unleash the contexionary's potential regarding data exploration.

I was expecting, for example, that adding an "Film" I would be able to explore by genre, for example.

Will keep on document myself.

In the meantime thanks for all the work you've done.

**Comment by etiennedi** [comment]
Hi @andreabat ,

if you have specific questions on use cases and how to make the most of the contextionary's features, feel free to post on StackOverflow with the tag `weaviate`. Examples for classifications ([contextual](https://www.semi.technology/documentation/weaviate/current/features/contextual-classification.html), [knn](https://www.semi.technology/documentation/weaviate/current/features/knn-classification.html)) and [contextual searches](https://www.semi.technology/documentation/weaviate/current/query-data/explore.html) can also be found in the docs. @bobvanluijt and @laura-ham are also always happy for feedback on improving them in case something's not clear.

In the meantime I'd like to comment on 

> Having some issues with elasticsearch complaining for limited disk space ( i'm using docker compose) and not sure how to solve since I do have space available.

The error you describe (making an index read-only) is indeed typical Elasticsearch behavior for when disks get full. Depending on what system you're running on the docker disk might have a fixed size that is smaller than you system's disk. For example I'm running on macOS, so I have this setting in my Docker UI

![image](https://user-images.githubusercontent.com/8974479/79883155-d9a54500-83f3-11ea-8b27-7e8bcc5549fc.png)

Could it be that the docker disk has reached it's limit while the system's disk still has plenty of space? You can also use `docker system df` to see how Docker is using it's virtual disk at the moment. 

Hope that helps.

**Comment by bobvanluijt** [comment]
Hi @andreabat, 

Thanks for your message, what you are writing and wanting is indeed correct and should be possible (we don't know for Italian because nobody in the team speaks it, haha).

We are soon launching our cloud service where you can create a Weaviate for free (with a time limit) and use that one if you [sign up here](https://www.semi.technology/newsletter/) you will get an email when it's live.

@etiennedi can you please help @andreabat with the ES issue?

**Comment by bobvanluijt** [comment]
@etiennedi we commented at the same time :-)
