### ISSUE TITLE
Explore based on things

### ISSUE THREAD

**Issue by fefi42** [semi-technologies/weaviate#1085]
Currently the explore function allows to search for concepts:
```GraphQL
{
  Explore (
    concepts: ["New Yorker"],
  ) {
    beacon
    certainty
    className
  }
}
```
It would be nice to allow using things instead:
```GraphQL
{
  Explore (
    concepts: "beacon": "weaviate://localhost/things/7e9b9ffe-e645-302d-9d94-517670623b35",
  ) {
    beacon
    certainty
    className
  }
}
```

**Comment by etiennedi** [comment]
Makes sense to me. I'm not sure I understand your API suggestion around `concepts: "beacon": "..."`. Maybe it contains a typo/mistake as that doesn't look like valid GraphQL?

A simpler suggestion below - possibly this is what you intended?

```graphql
{
  Explore (
    beacon: "weaviate://localhost/things/7e9b9ffe-e645-302d-9d94-517670623b35"
  ) {
    beacon
    certainty
    className
  }
}
```

## Explore vs. Get { Things(explore) } }
In your example you used the `Explore` API, but I assume the same should apply to the `Get { Things { ClassName(explore: {}) } }` API. Or is there any reason it should not?

**Comment by fefi42** [comment]
@etiennedi your suggestion looks good. Yes it should also exist for the `Get { Things { ClassName(explore: {})}}`
Maybe it makes sense to exclude the thing itself? If we search for similar things of the same class then the thing itself is the trivial answer.

**Comment by bobvanluijt** [comment]
It would be good to think about non-text values, what can we do with them.

**Comment by etiennedi** [comment]
Similar to #1098, the latter only deals with the REST functionality, but the implementation should be nearly identical.
