### ISSUE TITLE
Search by "phoneNumber" in GraphQL "where" search

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1089]
# Background

Still awaiting API discussion in #1087 

# Todos
* tbd

**Comment by bobvanluijt** [comment]
Not sure how difficult this is, it would be helpful.

**Comment by etiennedi** [comment]
Not particularly difficult, it just needs agreement upon the API. It is on the current prioritization list (#1107), but it is relatively low on the list.

**Comment by bobvanluijt** [comment]
Gotcha
