### ISSUE TITLE
Include objects (alongside word concepts) in c11y response

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1095]
tbd 

---
> can you provide an example of what it would mean[.]

Yes, I would now expect the behavior to include both individual words _and_ things and actions. It would be nice to have a flag to _only_ show words or _only_ show things and actions.

_Originally posted by @bobvanluijt in https://github.com/semi-technologies/weaviate/issues/1073#issuecomment-586745639_

**Comment by bobvanluijt** [comment]
_nudge_ (for the bot)

this would be very helpful.

@etiennedi what would you like to know specifically?
