### ISSUE TITLE
DISCUSSION: What can we do with corpi?

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#1096]
What if we would have an endpoint where one can submit a corpus of text and where the response includes "Weaviate parsing" of that corpus? This parsing could include what things and actions are related, how it would parse the text into a thing or action or if it found entities in the text.

The idea of this issue is to get to an idea what an ideal semantic parsing of the text might look like..

Example:

```
POST /v1/c11y/corpus -d 'Some text that has entities like Paris and a phone number like +316 123 456 78'
```

Results might include:

- The detection that Paris might be in the `class: City` (assuming this class would exist).
- Maybe suggest a `class: City`.
- Find the phone number.
- etc.

**Comment by etiennedi** [comment]
I like this idea, I think there's a lot of potential. Before we go any further, I'd like to identify what the users intention would be with such a query.

Based on the example I could imagine a few:

- The user has a text and wants to know how close this text is to a existing entities (similar to an explore search)
- The user tries to import something, but doesn't know which existing class would fit best
- The user knows that their corpus contains special elements (such as phone numbers), but doesn't know where, the user is interested in extracting them
- ...

**Comment by bobvanluijt** [comment]
>  I'd like to identify what the users' intention would be with such a query

This idea is born from questions I receive along the lines of:
- Can Weaviate parse documents?
- Can Weaviate automatically create a schema based on data I'm feeding it?
- etcetera.

This suggestion is a way of adhering to these questions where people seem to want to work as schemaless as possible. Definitive use cases are often absent in the request though.

**Comment by laura-ham** [comment]
Cool idea. 

I think we should approach this from use case perspective. If we want to automatically parse texts and suggest schema classes (1) and objects belonging to classes (2), then is `/v1/c11y/` the right endpoint? Maybe it fits more in `v1/classifications/`, with an endpoint name like  `v1/classifications/text` or  `v1/classifications/schema` (we have to think about the exact use case before I/we can come up with a good name)
