### ISSUE TITLE
Give a response on GET /

### ISSUE THREAD

**Issue by jettro** [semi-technologies/weaviate#1103]
The current version of weaviate in docker returns a 404 on requesting the root of the project. Especially as it is mentioned on the getting started pages, it would be nice to see at least something here. Maybe a status page or some links to resources.

**Comment by bobvanluijt** [comment]
Can you please share where the getting started docs are confusing?

[All examples in the getting started](https://www.semi.technology/documentation/weaviate/current/get-started/quick_start.html#validate-via-the-restful-api) contain working end-points.

**Comment by jettro** [comment]
In the setup of the news publications:
https://www.semi.technology/documentation/weaviate/current/datasets/newspublications.html

"Weaviate will be available and preloaded with the newsarticle demo dataset on:"
http://localhost:8080

which returns a 404

**Comment by etiennedi** [comment]
I agree that a 404 result is not the most pleasant entry page. We could serve a simple json to give some hints for API disovery. The [github API too](https://api.github.com/) is a good example for that. 

@jettro Do I understand you correctly that this is only a cosmetic issue at the moment or does it block you from using Weaviate in any way?

**Comment by jettro** [comment]
Absolutely @etiennedi Just going through documentation and placing remarks at things I see. This is no blocking issue at all

**Comment by etiennedi** [comment]
Great to hear, thanks for your feedback.
