### ISSUE TITLE
Consistent use of $weaviate in samples

### ISSUE THREAD

**Issue by jettro** [semi-technologies/weaviate#1104]
Going over all the samples, which are great to get an idea of the options. It would be easier for copy-paste if $WEAVIATE is used consistently. In all curl commands would be good to have something like:
`curl -s $WEVIATE ...`

than use:
`
export $WEAVIATE=http://localhost:8080
`
including http in the environment variable makes it easier to switch between http and https for the sample commands. Example, where it would be easier to copy-paste, is the curl command to initialize the automatic classification.

**Comment by etiennedi** [comment]
cc @laura-ham @bobvanluijt

**Comment by bobvanluijt** [comment]
Thanks both, just saw the website PR's come in from @jettro 👍

**Comment by bobvanluijt** [comment]
Gonna close it because it is now on the semi-website Git.
