### ISSUE TITLE
Unable to start using docker-compose (port 2379 already in use)

### ISSUE THREAD

**Issue by johnrees** [semi-technologies/weaviate#1110]
I'm trying to run weaviate locally as per the documentation

```
# download the config file
$ curl -O https://raw.githubusercontent.com/semi-technologies/DEMO-datasets/master/newspublications/config.yaml
# download the Docker Compose file
$ curl -O https://raw.githubusercontent.com/semi-technologies/DEMO-datasets/master/newspublications/docker-compose.yml
# Run docker
$ docker-compose up
```

but get the following error. I don't have anything running on port 2379 so I assume it's due to a race condition or something?

I haven't changed the default [config.yaml](https://raw.githubusercontent.com/semi-technologies/DEMO-datasets/master/newspublications/config.yaml) or [docker-compose.yml](https://raw.githubusercontent.com/semi-technologies/DEMO-datasets/master/newspublications/docker-compose.yml)

```
❯ docker-compose up                   
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

Creating network "weaviate_test_default" with the default driver
Creating weaviate_test_etcd_1 ... 
Creating weaviate_test_etcd_1          ... error
Creating weaviate_test_esvector_1      ... 
WARNING: Host is already in use by another container

Creating weaviate_test_contextionary_1 ... done
Creating weaviate_test_esvector_1      ... done
Creating weaviate_test_weaviate_1      ... done
Creating weaviate_test_newspublications_1 ... done

ERROR: for etcd  Cannot start service etcd: driver failed programming external connectivity on endpoint weaviate_test_etcd_1 (ec2d40e0ed4d0d6760cd36a4bec6080d2a348405ce48c1dc5f2faf77aca00240): Error starting userland proxy: listen tcp 0.0.0.0:2379: bind: address already in use
ERROR: Encountered errors while bringing up the project.
```

Any ideas? Thanks

**Comment by etiennedi** [comment]
Hi,

>  I don't have anything running on port 2379 

and 

> listen tcp 0.0.0.0:2379: bind: address already in use

don't really fit together. Could it be that another docker container uses the port or that you are running (or tried to run) more than one weaviate setup. Docker-compose uses the folder you are running from as it's namespace and uses that as the prefix for the container names (in your case `weaviate_test`). But ports bound to the host can only be used once, regardless of container namespacing.

Does the output of `docker ps -a` return anything else that's using the port?

If that's not the case you can investigate if your host machine is using anything on that part [using this guide for example](https://linuxize.com/post/check-listening-ports-linux/)

**Comment by johnrees** [comment]
Something peculiar was going on as the port didn't seem to be used and there was no output from `docker ps` either but a system restart fixed it! Thanks for the reply @etiennedi  :)
