### ISSUE TITLE
SUGGESTION: Add non-linear weighing capabilities

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#1116]
Currently, a sentence has a specific weighing mechanism (occurrence in original corpus, etc).

The idea is to integrate ways to give importance to a corpus that is being vectorized. For example, a paragraph does well with the current setup but a product title has more "left to right" value.

Proposed forms:
- Linear (default)
- Ascending
- Descending
- Curved

<img width="504" alt="Screenshot 2020-04-02 at 15 24 14" src="https://user-images.githubusercontent.com/5509162/78254328-0998b100-74f6-11ea-9849-4b2d16fd332e.png">

**Comment by etiennedi** [comment]
Anyone have any ideas on how to name this strategy? My immediate thoughts would be something along the lines of `weighingCurve` or `weighingDistribution`, but I think this hides the fact that the x-axis is literally the corpus from left to right. So I think there should be a better term. Something that expresses "how much should I weigh this individual word when moving left to right on the corpus?" Maybe it could involve the word `read` - as reading is something that we already associate with scanning over text left to right. 

Some ideas in no particular order:

- `weighingCurve: ascending`
- `scanWeight: ascending`
- `vectorizationScanner: ascending`
- ....

Any ideas @bobvanluijt @fefi42 @laura-ham @michaverhagen ?

**Comment by laura-ham** [comment]
Curious if the user would be interested in manually setting this. Can't this be automated by finding the relative importance of words in the corpus?

**Comment by bobvanluijt** [comment]
- @laura-ham can you elaborate a bit? Not sure I understand the suggested approach.
- @etiennedi it isn't always a curve, is it? Maybe something in the direction of `figure` or so?
