### ISSUE TITLE
QUESTION: What is the schema update behavior?

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#1122]
Example: https://app.swaggerhub.com/apis/semi-technologies/weaviate/0.22.5#/schema/schema.actions.update

This description states: `Rename, or replace the keywords of the Action.` but the fact that a complete schema object is needed implies that the complete schema item (i.e., class) can be updated. The same goes for things and properties.

Question: _What can and can't be updated after a schema item is created?_

**Comment by etiennedi** [comment]
That is a fair question and not that easy to answer. I'll have to investigate, as this also depends on limitation of the backing db's.

**Comment by bobvanluijt** [comment]
Thanks, I couldn't find it in the dcs so I will add it when available.

**Comment by bobvanluijt** [comment]
Disabling editing in the dashboard in the meantime.
