### ISSUE TITLE
Enable 'explore" with knn classification

### ISSUE THREAD

**Issue by michaverhagen** [semi-technologies/weaviate#1127]
Would it be possible to enable 'explore' functionality that returns results based on knn classification? 

So the explore query could (in pseudo code) look something like this:

```
knn_explore(explore_concept, target_class, nnn)
```
where:
- `explore_concept` is the concept you try to classify
- `target_class` is the class you try to classify to
- `nnn` is the number of nearest neighbors

The result would be:
```
[ beacon_1, beacon_2, beacon_3]
```
presented in order of distance from the `explore_concept`

**Comment by bobvanluijt** [comment]
@michaverhagen do you mean `nnn` as in words or data-objects?

**Comment by michaverhagen** [comment]
I think for most use cases data objects would be most relevant
