### ISSUE TITLE
Rename certainty to distance.

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#1128]
Where Weaviate uses "certainty", use "distance".

Maybe keep "certainty" in with a deprecation message.

**Comment by etiennedi** [comment]
Wasn't aware we had this issue. Now that we track deprecations this should be easy to do.

**Comment by Iheanacho-ai** [comment]
I would like to work on this

**Comment by etiennedi** [comment]
Hi @Iheanacho-ai Thanks for your interest. This issue can be considered deprecated because of the discussion mentioned in #1863 . We're already working on that one internally.
