### ISSUE TITLE
QUESTION: Is the same weighing algo used for the /v1/c11y/concepts end-point?

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#1130]
For example:

```
GET /v1/c11y/concepts/bradPitt
```

Are `brad` and `pitt` being weight in the same as during vectorization?

**Comment by etiennedi** [comment]
Yes, the vector for the concat word is calculated with the same method (weighing, stopword removal, etc.) as we apply in vectorizing of objects. [See code here](https://github.com/semi-technologies/weaviate/blob/69074a0792e4c0c4737a11acb8b61db76b95eed4/usecases/vectorizer/inspector.go#L86-L95). The vectors for the individual words list don't contain any weighing of course.
