### ISSUE TITLE
GroupBy in Get function

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#1132]
Use case: "I want to group all the available properties in a class together."
Use case in the example: "Show me all years that are part of `RetailSale`"

It would be helpful if we can extend Get's function with a traditional group by too _or_ that it is possible to solve the use case in Aggregate.

Example / suggestion:

```graphql
{
  Get{
    Things{
      RetailSale ({
        group: {
          type: traditional
      	  }
        }) {
        year
      }
    }
  }
}
```

<hr>

## Example response _without_ the filter

```json
{
    "data": {
        "Get": {
            "Things": {
                "RetailSale": [
                    {
                        "year": "2019"
                    },
                    {
                        "year": "2019"
                    },
                    {
                        "year": "2020"
                    },
                    {
                        "year": "2020"
                    }
                ]
            }
        }
    }
}
```

## Example response _with_ the filter

```json
{
    "data": {
        "Get": {
            "Things": {
                "RetailSale": [
                    {
                        "year": "2019"
                    },
                    {
                        "year": "2020"
                    }
                ]
            }
        }
    }
}
```

_NOTE I: probably the user also needs to specify what they would have liked grouped (in the example it would be year)_

_NOTE II: maybe this functionality is more for Aggregate._

**Comment by etiennedi** [comment]
Regarding 
> Use case: "I want to group **all** the available properties in a class together."
> Use case in the example: "Show me **all** years that are part of RetailSale"

(highlights by me)

and 

> NOTE I: probably the user also needs to specify what they would have liked grouped (in the example it would be year)
> 
> NOTE II: maybe this functionality is more for Aggregate.

I agree that Aggregate would be the better fit for the following reasons:
* The functionality is already possible with Aggregate at the moment
* A group on get will only run on the result set. So if you have 10,000 items and query 100 and group, the groups will be made based on those 100 results. You wouldn't be able to serve the query "I want to group **all** the available properties in a class together.". At most you'd be able to serve the query "I want to group the available properties **of the first 100 search results** in a class together."
* Aggregate is designed to aggregate over the entire dataset as opposed to a subset
