### ISSUE TITLE
`atMostOne` cardinality is not supported by add references endpoint.

### ISSUE THREAD

**Issue by fefi42** [semi-technologies/weaviate#1133]
`POST` and `PUT` on `/things/{id}/references/{propertyName}` do not support `atMostOne` cardinalities. Trying to use this endpoint with a cardinality `atMostOne` will result in an `Property 'key' has a cardinality of atMostOne` error. 

There is also **no** substitute for it such as `/reference`. To add an `atMostOne` reference one must update the thing itself. This is especially unintuitive if the reference is `null`. We should allow this cardinality or at least give some hints in the error message.

**Comment by etiennedi** [comment]
related to #1142
