### ISSUE TITLE
Suggestion semantic path metric based on fixed distances

### ISSUE THREAD

**Issue by fefi42** [semi-technologies/weaviate#1135]
To show the semantic path aka. what objects lie between A and B in the contextionary I suggest the following metric. The graphic visualizes the process: ![image](https://user-images.githubusercontent.com/4573211/80599459-3ffd1980-8a2b-11ea-86a6-1ac7a794c1a1.png)

1. Interpolate linearly in equal step size between object A and B (pink circles). The step size is fixed and for all semantic paths equal. The steps are indicated as brown squares.
2. Search for the closest object to each of those interpolation points (blue triangle). 
3. List the found objects as the semantic path.

+ Because of the equal step size longer paths represent concepts that are further away from each other. This is intuitive.
(+) I assume this is easy to implement.

- In a densely populated space many concepts might be skipped. 
- Extreme sparse sub spaces might create artifacts like one object being listed double.

**Comment by etiennedi** [comment]
Thanks for riding down the detailed suggestion. I'll implement a small prototype shortly to see if the results are indeed what we would expect.
