### ISSUE TITLE
Meta information in Get{} results

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#1136]
When Weaviate's semantic features are used to provide results to the end-user, we might be able to improve the UX to _why_ Weaviate came to these results by introducing a `__meta` "property" that contains additional information per class.

# Available keys

- `semanticPath.concept` (aka _shortest semantic path_) = A concept as defined in [the docs](https://www.semi.technology/documentation/weaviate/current/about/philosophy.html#basic-terminology) or a entity in the form of a beacon.
- `semanticPath.distanceToQuery` = The distance to the Explore{} filter.
- `semanticPath.distanceToParent` = If there is a parent, the semantic distance.
- `semanticPath.distanceToNext` = If there is a next item in the path, the distance.
- `distanceToQuery` = The distance to the Explore{} filter.
- `distanceToParent` = If there is a parent, the semantic distance.

# Example Query

A query might look like this (also includes the proposed values)

_Note: results function just as examples_

```graphql
{
  Get {
    Things {
      Article(
        explore: {
          concepts: ["beatles"]
        }
        limit: 1
      ) {
        title
        InPublication {
          ... on Publication {
            name
            __meta {
              semanticPath {
                concept
                distanceToQuery
                distanceToParent
                distanceToNext
              }
              distanceToQuery
              distanceToParent
            }
          }
        }
        __meta {
          semanticPath {
            concept
            distanceToQuery
            distanceToParent
            distanceToNext
          }
          distanceToQuery
          distanceToParent
        }
      }
    }
  }
}
```

# Example result

Proposed result based on the above query.

```js
{
  "data": {
    "Get": {
      "Things": {
        "Article": [
          {
            "InPublication": [
              {
                "name": "The Guardian"
                "__meta": {
                    "semanticPath": [{
                        "concept": "foo",
                        "distanceToQuery": 0.4, // the Explore{} filter
                        "distanceToParent": 0.8, // In this case the parent Article
                        "distanceToNext": null // there is no next item
                    }, {
                        "concept": "weaviate://localhost/things/6fe82690-bef8-3be4-9e22-7f1374e27fed", // a concept can be a word or a thing/action
                        "distanceToQuery": 0.6, // the Explore{} filter
                        "distanceToParent": 0.45, // In this case the parent Article
                        "distanceToNext": 0.2 // in this case the concept "foo"
                    }]
                    "distanceToQuery": 0.3, // the Explore{} filter
                    "distanceToParent": 0.2 // In this case the parent Article
                }
              }
            ],
            "title": "Opinion | John Lennon Told Them ‘Girls Don’t Play Guitar.’ He Was So Wrong."
            "__meta": {
                "semanticPath": [{
                    "concept": "baz",
                    "distanceToQuery": 0.4, // the Explore{} filter
                    "distanceToParent": null, // there is no parent
                    "distanceToNext": null // there is no next item
                }, {
                    "concept": "weaviate://localhost/things/6fe82690-bef8-3be4-9e22-7f1374e27fed", // a concept can be a word or a thing/action
                    "distanceToQuery": 0.6, // the Explore{} filter
                    "distanceToParent": null, // there is no parent
                    "distanceToNext": 0.2 // in this case the concept "baz"
                }]
                "distanceToQuery": 0.3, // the Explore{} filter
                "distanceToParent": null // there is no parent
            }
          }
        ]
      }
    }
  },
  "errors": null
}
```

**Comment by bobvanluijt** [comment]
This issue solves: https://github.com/semi-technologies/weaviate/issues/1126

**Comment by etiennedi** [comment]
Thanks for the suggestion and the detailed explanations, @bobvanluijt .

Some immediate thoughts and questions:

* Were you able to find anything about whether the double-underscore properties (`__prop`) are reserved for a fixed set of properties in GraphQL or whether we can freely add new ones? If not I'm happy to research this myself
* The above suggestion shows a lot of distances, I'm not sure if the amount of different distances is immediately intuitive? Would we potentially gain more from a more reduced API that is easier to grasp? (cc @laura-ham)
* In particular the `distanceToParent` within the path is not very intuitive to me. I understand that `distanceToParent` on an object is interesting, but is it really required on every path element?
* What's the direction of a path. Does it go from query to object or the inverse? 
* The first element in the path has no `distanceToNext`, but the last element does. If this is the desired order I think a `distanceToPrevious` would be more intuitive. Or alternatively the last item in the list should not have 'distanceToNext', but the first one should?
* On the query side `semanticPath` should probably take arguments, i.e. `semanticPath( /* ... */). 
  * Possible things I'd want to configure: Which path algorithm do we use: "fixed distance" where the length of the path is a hint to the distance or "variable length" where we keep jumping until we have found the target. Also for "fixed length" the length should be configurable.
  * I think we should spike out the two alternatives before we implement this. Possibly one is always better than the other and we can save on API complexity by always using the same one.

cc @fefi42 @michaverhagen @laura-ham

**Comment by bobvanluijt** [comment]
CC: https://github.com/semi-technologies/weaviate/issues/1135

**Comment by bobvanluijt** [comment]
Thanks @etiennedi, responses per bullet.

> * Were you able to find anything about whether the double-underscore properties (`__prop`) are reserved for a fixed set of properties in GraphQL or whether we can freely add new ones? If not I'm happy to research this myself

No, I have not, but I think it would more be a "Weaviate reserved property which resembles GraphQL properties".

> * The above suggestion shows a lot of distances, I'm not sure if the amount of different distances is immediately intuitive? Would we potentially gain more from a more reduced API that is easier to grasp? (cc @laura-ham)

Let's not forget that the end-user does not have to use them, e.g., if you _only_ want to know the distance to a parent, you can set that property. The goal is to give maximum flexibility to the end-user.

> * In particular the `distanceToParent` within the path is not very intuitive to me. I understand that `distanceToParent` on an object is interesting, but is it really required on every path element?

Fair point, maybe not. On the other hand, depending on how hard the implementation is, it might be helpful for the end-user.

> * What's the direction of a path. Does it go from query to object or the inverse? 

It goes ascending (top to bottom) to be aligned with how results are shown when results are shown with an explore filter. I've tried to indicate this with the example response.

> * The first element in the path has no `distanceToNext`, but the last element does. If this is the desired order I think a `distanceToPrevious` would be more intuitive. Or alternatively the last item in the list should not have 'distanceToNext', but the first one should?

Good point, the reason it says "there is no next" is because it takes the result -> query route. Meaning that in this case, next would be the query.

Completely open to reverse this.

@laura-ham what do you think is more intuitive?

> * On the query side `semanticPath` should probably take arguments, i.e. `semanticPath( /* ... */). 
>  * Possible things I'd want to configure: Which path algorithm do we use: "fixed distance" where the length of the path is a hint to the distance or "variable length" where we keep jumping until we have found the target. Also for "fixed length" the length should be configurable.
>  * I think we should spike out the two alternatives before we implement this. Possibly one is always better than the other and we can save on API complexity by always using the same one.

Absolutely agreed, let's also not forget @fefi42's issue #1135  

> * What's the motivation behind showing not just concepts, but also object-beacons in the path?

In the example, we are looking for Articles, but there might be a 'non-Article' object in between (maybe an Author or Publication).

**Comment by laura-ham** [comment]
It took me some time to grasp all the concepts, it's clear explanation, but maybe we can use some different wordings etc.

> * In particular the `distanceToParent` within the path is not very intuitive to me. I understand that `distanceToParent` on an object is interesting, but is it really required on every path element?

This one is also not intuitive to me. Maybe we should stay away from `Parent` since it is not clear if it means `Previous` or the `class` of the object. And I think `Parent` might be confusing because we have a flat hierarchy ontology structure. If I understand it correct, this parent is always a class, so why not just name it `class`.
Also the user maybe doesn't know what the parent of the object is, so we'd need to introduce also `belongsToParent` (`class` or `belongsToClass`). 
I see no use case in this `distanceToParent` at the moment by the way, because it tells something about a concept you find on the way of the path, its not telling anything about the path from the query to the end object itself. But if it's useful, go ahead ;)

> > * What's the direction of a path. Does it go from query to object or the inverse?
> 
> It goes ascending (top to bottom) to be aligned with how results are shown when results are shown with an explore filter. I've tried to indicate this with the example response.

I agree that this is not super clear atm. But `distanceToQuery` tells this, and if I think mentioning this in the docs would be sufficient. (I don't see an alternative, e.g. nesting will be over complicating the whole thing)

> > * The first element in the path has no `distanceToNext`, but the last element does. If this is the desired order I think a `distanceToPrevious` would be more intuitive. Or alternatively the last item in the list should not have 'distanceToNext', but the first one should?
> 
> Good point, the reason it says "there is no next" is because it takes the result -> query route. Meaning that in this case, next would be the query.

Hmm this is a difficult one. I was reasoning from query perspective, but the result is from the returned data object perspective. The datafield is called `semanticPath`, which is why I think from query perspective. But something goes wrong in the ordering of your example, like @etiennedi also points out. Also, how can the `distanceToQuery` of the returned object be smaller than of the items on the path? Could you clarify this @bobvanluijt, that would make it easier to decide on `distanceToQuery`, `distanceToNext` and/or `distanceToPrevious`

> * The above suggestion shows a lot of distances, I'm not sure if the amount of different distances is immediately intuitive? Would we potentially gain more from a more reduced API that is easier to grasp? (cc @laura-ham)

Besides the `Parent` I mentioned above, I think it is fine like this.

**Comment by bobvanluijt** [comment]
> how can the distanceToQuery of the returned object be smaller than of the items on the path?

Sorry @laura-ham, I'm not sure I understand the question in this context.

**Comment by bobvanluijt** [comment]
Related: https://github.com/semi-technologies/weaviate/issues/1139

**Comment by bobvanluijt** [comment]
cc: @graphileon

**Comment by bobvanluijt** [comment]
I've updated the algo.

## Example input 1

```golang
sourceStringArr := []string{"beatles"}
targetStringArr := []string{"yoko", "ono"}
```

result:

```bash
concept: beatles distanceToQuery: 0.30386263 distanceToParent: UNSET distanceToNext: UNSET
concept: mccartney distanceToQuery: 0.2672233 distanceToParent: UNSET distanceToNext: UNSET
concept: lennon distanceToQuery: 0.20381969 distanceToParent: UNSET distanceToNext: UNSET
```

Reasoning of results: Yoko Ono was married to John Lennon

## Example input 2

```golang
sourceStringArr := []string{"new", "york", "city"}
targetStringArr := []string{"holland"}
```

result:

```bash
concept: york distanceToQuery: 0.38275877 distanceToParent: UNSET distanceToNext: UNSET
concept: newly distanceToQuery: 0.35695243 distanceToParent: UNSET distanceToNext: UNSET
concept: already distanceToQuery: 0.3553279 distanceToParent: UNSET distanceToNext: UNSET
concept: shortly distanceToQuery: 0.35154867 distanceToParent: UNSET distanceToNext: UNSET
concept: went distanceToQuery: 0.35122553 distanceToParent: UNSET distanceToNext: UNSET
concept: purchased distanceToQuery: 0.34686 distanceToParent: UNSET distanceToNext: UNSET
concept: bought distanceToQuery: 0.34192425 distanceToParent: UNSET distanceToNext: UNSET
concept: britain distanceToQuery: 0.34009206 distanceToParent: UNSET distanceToNext: UNSET
concept: los distanceToQuery 0.3296434 distanceToParent: UNSET distanceToNext: UNSET
concept: angeles distanceToQuery 0.2952841 distanceToParent: UNSET distanceToNext: UNSET
concept: ny distanceToQuery 0.23678344 distanceToParent: UNSET distanceToNext: UNSET
concept: jersey distanceToQuery 0.1960155 distanceToParent: UNSET distanceToNext: UNSET
concept: yorks distanceToQuery 0.16018993 distanceToParent: UNSET distanceToNext: UNSET
```

Reasoning of results: New York bought the rights for NYC from queen of Holland.

## Example input 3

```golang
sourceStringArr := []string{"alexander", "mcqueen"}
targetStringArr := []string{"vogue"}
```

result:

```bash
concept: alexander distanceToQuery: 0.4102744 distanceToParent: UNSET distanceToNext: UNSET
concept: famously distanceToQuery: 0.37717065 distanceToParent: UNSET distanceToNext: UNSET
concept: remarked distanceToQuery: 0.37446737 distanceToParent: UNSET distanceToNext: UNSET
concept: likes distanceToQuery: 0.369704 distanceToParent: UNSET distanceToNext: UNSET
concept: commented distanceToQuery: 0.34802863 distanceToParent: UNSET distanceToNext: UNSET
concept: photographed distanceToQuery: 0.27807295 distanceToParent: UNSET distanceToNext: UNSET
```

Reasoning of results: Alexander Mcqueen is a fashion designer whose work appeared (i.e., photos) in Vogue.

# Important

The naming of `distanceToQuery` is not a 100% accurate because of [this part of the algo](https://github.com/semi-technologies/weaviate/blob/519bd870d0d06b24d28045c29a8a30f541725e63/usecases/traverser/explorer_semantic_path.go#L62). I don't think it is an issue though because it seems intuitively correct.

**Comment by etiennedi** [comment]
Thanks for investigating and playing around with the algorithm. Do I understand it correctly that the major change you made - compared to the last version - is that each following element is skipped if it is further away from the target than the last?

Did you only evaluate it from concept to concept or also from concept to search result (object)? I'll do some checks with the latter.

**Comment by bobvanluijt** [comment]
Three things are changed:

1. All distances need to be lower than the previous one.
2. First, it does the above from source nearest neighbors to target.
3. Secondly, I do it in reverse order from the nearest neighbor (I.e., from far to close) towards the target.

For 3, the distance rule from 1 becomes arbitrary. There is no relation between the distances in 1 and 2.

**Comment by bobvanluijt** [comment]
@etiennedi is it possible to also add this [metadata](https://www.semi.technology/documentation/weaviate/current/features/knn-classification.html#get-classification-meta-information-of-data-objects) to the GraphQL results?

**Comment by etiennedi** [comment]
> @etiennedi is it possible to also add this [metadata](https://www.semi.technology/documentation/weaviate/current/features/knn-classification.html#get-classification-meta-information-of-data-objects) to the GraphQL results?

@bobvanluijt I only saw this now and now the link is 404ing. I assume this is about the classification meta as metnioned in #1155?

**Comment by bobvanluijt** [comment]
> > @etiennedi is it possible to also add this [metadata](https://www.semi.technology/documentation/weaviate/current/features/knn-classification.html#get-classification-meta-information-of-data-objects) to the GraphQL results?
> 
> @bobvanluijt I only saw this now and now the link is 404ing. I assume this is about the classification meta as metnioned in #1155?

This is the link :-) https://www.semi.technology/documentation/weaviate/current/classification/knn-classification.html#get-classification-meta-information-of-data-objects

**Comment by bobvanluijt** [comment]
> I assume this is about the classification meta as mentioned in #1155?

Correct 👍

**Comment by bobvanluijt** [comment]
### Results from discussion 11/06

- Remove the “__meta” in general, keep the content as separate functions.
- Convention in GraphQL == “__” [link]
- Convention for Weaviate will be “_” [link]
- Same results in the RESTful API.
- metaFields=_semanticPath,_foobar (option?)
- Not user-defined should start with an underscore.

```
{
  … {
     <CLASS>{
       <PROPERTY>
       _semanticPath(params) {

       }
	 _nearestNeigbors(params) { # array, note the “s” :)
	concept
 }
       _featureProjection(params) {
		# TSNE spike was fast enough, results are okayish
		# UMAP is also an option
		# Add algo as a param, start with TSNE
		# Context should be per query _or_ in complete context, first implementation is _only_ on query level
		# Include nearest words?
	2D
	3D
_nearestNeigbors(params) { # array, note the “s” :)
		concept
		2D
		3D
	 }
       }
       _classification(params) {
		# data is available
       }
       _snippets(params){ # array, note the “s” :)

       }
       _meta(params){
        	# data is available
       }
     }
  }
}
```
