### ISSUE TITLE
Suggestion: auto cut-off Explore search results

### ISSUE THREAD

**Issue by laura-ham** [semi-technologies/weaviate#1138]
### Problem & current behaviour
If the `Explore` filter in a GraphQL `Get` query is used, it is unclear how to set and control the `certainty` (or distance) parameter. This parameter controls what results to return, but with the current design, the user does not know what to set this parameter, to get optimal results. 

You don't want to see 'bad' results amongst the results, but you don't know beforehand where the cut off point of the `certainty` is. Additionally, we observed that the user prefers not to see any results if there are no good results at all.

### Proposed solution
Automatically find a cut-off threshold for which results to show. This threshold can be calculated by e.g. an elbow in distances between each result and the query, or between a cluster of results and the query. 

![IMG_20200508_144440458](https://user-images.githubusercontent.com/26965746/81402691-8f81ca80-913a-11ea-86b5-e1f67e80630c.jpg)

### Questions
1. Should the user have the option to set whether they want to enable this auto function on their query?
2. What value to set the (relative) cut-off point to? (=how big should the gap between the points or clusters relatively be?)

**Comment by bobvanluijt** [comment]
Thanks @laura-ham 

@etiennedi, maybe an idea to get to the answer through a quick spike?

**Comment by etiennedi** [comment]
Thanks @laura-ham for the detailed explanation and the visualization. 

I agree that a spike against a few queries on a few datasets would be very helpful here. @laura-ham do you have any capacity to aid with this? I think we already expose all metrics (mainly distance) to spike this outside of Weaviate?

**Comment by bobvanluijt** [comment]
@laura-ham nudge...

> @laura-ham do you have any capacity to aid with this?

**Comment by laura-ham** [comment]
Not at the moment tbh.. I might have a bit more time in the second half of the month, in July for sure.

**Comment by bobvanluijt** [comment]
Cool, please keep it on your radar ;-)

**Comment by bobvanluijt** [comment]
Hi @laura-ham – friendly nudge regarding this issue

**Comment by laura-ham** [comment]
**Update** 

Had a discussion with @bobvanluijt, and we want to propose to include an option for an auto cut-off point for GraphQL `Get (explore:{}) {}` queries. 

* The goal is to improve the UX for using this functionality, because it's hard to define beforehand what a good level of `certainty` is before executing the query and checking the results first.
* This `auto_cutoff` will be `false` by default, so no behaviour will be changed when performing a 'normal' Get explore query.
* I will do some research and suggest a good performing algorithm. We are aware that results will depend on the dataset, size of dataset, and many other variables. Therefore, the default is not cutting off automatically, and giving information messages when needed (see https://github.com/semi-technologies/weaviate/issues/1289). The algorithm will be as simple as possible, because we don't want to slow down the query time too much by e.g. relying on feature projections. So probably only (relative) `certainty` will be taken into account. 

Potential query filter: 
```graphql
{
    Get {
        Things {
            Article (
                explore: {
                    concepts: ["fashion"],
                    auto_cutoff: "true"
                }
            ) {
                title
                _certainty
            }
        }
    }
}
```

If you agree with this approach, I will suggest a algorithm to calculate cut-off points soon.

**Comment by etiennedi** [comment]
Thanks for the update, @laura-ham.

The suggestions you make seem very reasonable to me. Especially, the goal of making it optional resonates well with me, as this will allow us to get away with it not having to perform 100% perfect on day one and the ability to further improve it as we go.

Needless to say, I'm very happy about a simple algorithm that does not slow down query times :)

If I understand you correctly, we (as in Marcin and I) don't have to to anything at the moment, until you've made a suggestion for an algorithm?

**Comment by laura-ham** [comment]
> If I understand you correctly, we (as in Marcin and I) don't have to to anything at the moment, until you've made a suggestion for an algorithm?

Correct, just wanted to give an update (and your positive reply so I can start experimenting with the algo 😃 )

**Comment by laura-ham** [comment]
Let's this open until we have an idea if&how to solve this with the modularized structure

**Comment by bobvanluijt** [comment]
Ha - yes, thanks @laura-ham – this is an important one

**Comment by bobvanluijt** [comment]
cc: @michaverhagen

**Comment by bobvanluijt** [comment]
Discussion: https://weaviate.slack.com/archives/C02RRQP23K3/p1662619147103219?thread_ts=1660801682.805749&cid=C02RRQP23K3
