### ISSUE TITLE
Suggestion: build context based on subgraph

### ISSUE THREAD

**Issue by fefi42** [semi-technologies/weaviate#1140]
Problem: 
Consider a simple schema that represents RDF triples. Where we have 4 classes: `Subject`, `Predicate`, `Object` and `Triple`, while the triple just consists of 3 references to one of each of the other 3 classes. 

It would be nice to create a contextual search for a triplet. However this is currently not possible, because the triplets context is not determined by its references. So an explore search on a triplet currently returns a kind of random result.

Suggestion:
I want to be able to combine the context (vector position) of `Triple` with those of `Subject`, `Predicate` and `Object`.

``` gql
{
  Get {
    Things {
      Triple (explore: {
        concepts: ["voltage"]
        extendContext: [
            {path: ["Subject", "Subject"]},
            {path: ["Predicate", "Predicate"]},
            {path: ["Object", "Object"]},
        ]
      }){
        Subject {
          ... on Subject {
            value
          }
        }
        Predicate {
          ... on Predicate {
            value
          }
        }
        Object {
          ... on Object {
            value
          }
        }
      }
    }
  }
}
```

@etiennedi @bobvanluijt @laura-ham do you see this as useful? Any opinions on the gql query definition, implementation, ...?

**Comment by etiennedi** [comment]
My first impression is that I like it and seems useful to me. But, I'm not sure I completely understand your expected results yet. Could you add an example?

Implementation wise this would be quite interesting: If I understand your goals correctly, we'd probably need to do three independent searches for each element in `extendContext`, then see which `Triple` objects have links to some of those results? Are the three searches independent or do they all need to "match"?

**Comment by fefi42** [comment]
My first thought was to just create a new context out of the already existing once.
Take the triple `chicken isIn soup`  then we would just create a vector combination out of `chicken` `isIn` and `soup` and check how close it is to the concept term that is searched for.

**Comment by etiennedi** [comment]
> Take the triple chicken isIn soup then we would just create a vector combination out of chicken isIn and soup

So if 100M objects are in the db, we'd have to create 100M vectors at search time? Or does this new vector not have to be built once for every possible search result?

**Comment by fefi42** [comment]
I guess building centroids would be too expensive at scale. 
Maybe we can add a kind of additional index field for classes. 
```
 "myIndex": [Subject, Predicate, Object]
```
This index would then be build when the class is created or when one of these references change.

Then we could do explore like this:
```
 Triple (explore: {
        concepts: ["voltage"]
        basedOn: "myIndex"
      })

```

**Comment by bobvanluijt** [comment]
@fefi42 is this still relevant?

**Comment by fefi42** [comment]
Not for the moment
