### ISSUE TITLE
Sempath experimentation setup

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1141]
These are instructions to run the spike code

### Step 0 - Spike path
Check out the branch `spike/semantic-path-algo`:
```sh
git checkout spike/semantic-path-algo
```

### Step 1 - Dev env
Start the dev-env with a custom contextionary by running
```sh
tools/dev/restart_dev_environment.sh --sempath
```

### Step 2 - Compile and run Weaviate
```sh
./tools/dev/run_dev_server.sh
```

### Step 3 - Import Data
Import any dataset you like, it doesn't matter what it is, but the spike code depends on data being present

### Step 4 - Run a query
Run a GraphQL `Get {}` query _with_ an explore filter. This is the trigger for the spike code in ` usecases/traverser/explorer_semantic_path.go` to run.

Once running it will print the path to the console.

*Note: The algo runs once per search result, so it makes sense to limit your query to 1 or very few results*

### Spike Code
There's a lot of commented out and moved around stuff. Also I wouldn't be surprised if comments are no longer up-to date.

### Hardcoded words as opposed to using the query values.
The current version completely ignores the query and actually hard-codes the concepts for source and target of the path:
https://github.com/semi-technologies/weaviate/blob/b39b663df313a378f23af2a1108110b505e0aa0b/usecases/traverser/explorer_semantic_path.go#L19-L26

If you instead want to use the actual source and target for each query result, simply remove those lines and the real values will be used

### Alternative algorithm
At the moment the default algorithm is the "search around source and target and determine overlap" algorithm. It is defined in https://github.com/semi-technologies/weaviate/blob/b39b663df313a378f23af2a1108110b505e0aa0b/usecases/traverser/explorer_semantic_path.go#L10

Alternatively you could also run the algorithm where we do a knn search around the source, pick the result which is closest to the target, do another search, etc. This algo is defined in https://github.com/semi-technologies/weaviate/blob/b39b663df313a378f23af2a1108110b505e0aa0b/usecases/traverser/explorer_semantic_path.go#L114

Which algo is currently used is defined in:
https://github.com/semi-technologies/weaviate/blob/b39b663df313a378f23af2a1108110b505e0aa0b/usecases/traverser/explorer.go#L129

**Comment by bobvanluijt** [comment]
Thanks for the clear explanation, [got it in one](https://i.imgur.com/0PfMfYb.gif) Go ;-)
