### ISSUE TITLE
Is cardinality still needed?

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#1142]
I believe that the cardinality is a leftover from the days of Janus.

Is it possible to completely remove this from Weaviate _or_ to always default to `many` to make sure all API endpoints work as advertised in the documentation?

This seems a problem more people encounter and I've encountered it myself too.

**Comment by bobvanluijt** [comment]
@fefi42, do you sometimes explicitly use `atMostOne`? I can't find the difference in behavior in the API... Or am I missing something? If so, it is incorrectly in the docs...

**Comment by fefi42** [comment]
I think you are using the batch request which skips the validation process and thus allows to add many references even if the cardinality is `atMostOne`.

**Comment by etiennedi** [comment]
I'll all for a removal, internally we always store as a list anyway.

**Comment by bobvanluijt** [comment]
I'm also in, but let's make sure we make it match with the docs and try to not break anything existing. In theory, the behavior of the API shouldn't change.

**Comment by fefi42** [comment]
I am all for pushing this. The current behavior of `atMostOne` references is unintuitive since they are pretty much read only. This is confusing and should be deprecated.

**Comment by etiennedi** [comment]
TODO: Investigate if we can remove this for the September 15 release. In classification validate at runtime as opposed to in schema.

**Comment by bobvanluijt** [comment]
![](https://t3.gstatic.com/images?q=tbn:ANd9GcRe99lIPo0TO56uPVw9p7j5y5BAPXaNV1-hJPlhYnbtuGAzqYtMHtw30wwwF2SD-RfgnxO18ASzbHiQBCwlBxo)

**Comment by etiennedi** [comment]
Closing this discussion issue in favor of the new implementation issue #1240
