### ISSUE TITLE
Custom DB strategy

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1143]
# Questions

## Is (H)NSW a good fit our problem space?
✅ Yes, it performs well. The highest cost is at import time (index creation), but it's still reasonable for  our use cases. Ran two spikes to validate. The is no benefit to using NSW over HNSW, as the latter is better in all tested aspects.

## How can we store the index?
⚠️ Current favorite is to store in memory and write into a commit log. The commit log can be periodically merged into a db file. On startup the db file is read into memory. On replica sync the db file can be copied for large chunks and the commit log can be used for iterative changes. Not yet validated through a spike.

## The index performs best with a `uint32` id, but we commonly use uuids. How can we deal with that?
✅ We can assign an incremental id per shard (see below) and store the ID with the data object. This way the lookup `uuid->indexid` is one hop (itself being O(log(n)) due to the b+ tree). Similarly we can set the indexid is a hidden property on the object. Since we build a simple inverse index anyway the lookup `indexid->uuid` is 1 hop.

## How can we assign incremental ids per shard in a thread-safe fashion that is immediately persisted
✅ A simple write-only 4 byte file (for a `uint32`) and a regular `sync.Mutex` to align concurrenct counter increases is plenty fast enough, validated through a spike.

## Can we use boltdb for both the kNN and the inverse index?
* inverse index
  * ✅ generally yes, validated through spike
  * ⚠️ can we do efficient partial and number range lookups? Not yet validated, but in theory this should be no issue with a B+ tree as keys are already stored in order
* regular data objects
  * ✅ no issues here, this is pretty much what it's designed for
* kNN index
  * ⚠️ needs to be validated
  * The current assumption is that the index itself will always have to run in memory, so this "only" a backup to build the in-mem model at startup. Needs to be combined with the commit log (compare Cassandra) for writes that have not yet been added. The assumption is that building the index in bolt live without the use of a commit log is far too slow, as we have a very large amount of random writes per index instruction (because HNSW is a graph and we add a lot of edges per iteration!)
* write speed
  * ✅ OKish, as our limting factor will be the HNSW creation anyway

## Looking up vectors from disk is expensive, but the HNSW index needs to do a lot of lookups. How can we deal with that?
✅ Looking up a vector from disk with an underlying b+-tree storage mechanism is O(log(n)), additionally we have introduced indexid->uuid step which itself has the same cost. This ultimately leads to 2 *O(log(n)) costs per lookup. However a simple spike showed that keeping the most recent (100MB or so) vectors in an in-memory cache this cost can be largely ignored. A lot of the lookups in an HNSW index are to the same objects, so  the cache pays off very quickly. For the largest part we can treat vectors as immutable. If they do ever change we can accept the cost of invalidating the cache.

**Comment by bobvanluijt** [comment]
@etiennedi, I'm not sure if this is the right place to ask this. But I would like to get a better understanding of user-facing functionality. I.e., what API's are available to add, mutate, search, etc. the vectors? (something like a swagger example would be ideal).

**Comment by etiennedi** [comment]
@bobvanluijt Nothing like this has been designed yet, I can create an initial proposal which can serve as a basis for this discussion. It's not really tied to the new db strategy as there's nothing in the way from also implementing it with the old strategy (other than double work and scaling limitations)

**Comment by bobvanluijt** [comment]
@etiennedi perfect, that's clear.
