### ISSUE TITLE
Custom DB Shortcut clean up

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1150]
## Background & Process
In order to move fast with the custom db and tackle the highest uncertainties and complexities first, we are prepared to take some shortcuts. These shortcuts need to be cleaned up before a public release or we risk a feature regression.

Any item on this list should - once fixed - be protected through a test. If an existing test is temporarily removed it should be tagged with `// TODO gh-1150` so we can easily find it when tackling this

### From MVP 1 (#1146)
* [x] Parse geo-prop field on read
* [ ] deal with object meta on read
* [x] add `uuid` into required field for GraphQL read

**Comment by etiennedi** [comment]
>  marked as stale because it has not had recent activity.

Haha, apparently commits to the issue don't count as activity ;-) Last Commit is 5 days old...

**Comment by bobvanluijt** [comment]
Haha, it's funny to see you communicate with the bot @etiennedi  🤣

**Comment by etiennedi** [comment]
It's my secret trick to inflate my GitHub profile activity.

**Comment by etiennedi** [comment]
Has it really been another 60days, bot? Shame on you for trying to close the clean up issue. Shame on me for not having cleaned them up yet.

**Comment by bobvanluijt** [comment]
![robot](https://media1.tenor.com/images/396773199c03673b0b3bfcb466b900b5/tenor.gif?itemid=18526730)

**Comment by etiennedi** [comment]
Closing this issue, the original intend was to have a catch all for all clean ups. However, with the increased issue quality as of lately, we seem to have listed all required cleanups in individual issues. If we encounter a `// TODO gh-1150` in the code that is not covered by another issue, we need to open a new one.
