### ISSUE TITLE
Batch endpoint for PATCH

### ISSUE THREAD

**Issue by fefi42** [semi-technologies/weaviate#1167]
Problem: It is not possible to batch update specific fields in many entities at once. 

I'd like to have a batch endpoint for `PATCH` just like we have for `POST` right now. 
Just like the regular PATCH it should merge the documents or create a new one if none exists.

**Comment by etiennedi** [comment]
As discussed over Slack this contains two parts:

* Allow a patch Upsert (on both APIs)
* Add a batched Patch endpoint

**Comment by fefi42** [comment]
I am still looking forward to this. It is required to update data efficiently.
