### ISSUE TITLE
Improve error messages after "broken batch imports"

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1185]
## What's going on?

* Batch imports avoids checks by design (that's how it can be very fast)
* If you reference a source that doesn't exist, Weaviate still accepts it and merges a ref into a "null object". This null object then doesn't contain the required fields, such as `uuid`, `kind`. This leads to ugly errors when querying such an object, e.g. `interface conversion: interface {} is nil, not string`

## Todos
We can't really prevent such a corrupt input because the "cost" of the batch function is that the we skip validation and the user has to be sure they import a non-broken dataset.

However, we could at least try and catch this case and present a more usable error message.

**Comment by bobvanluijt** [comment]
How many checks are there?

**Comment by etiennedi** [comment]
Nothing is checked that would require reading the object first. That's how the speed is gained, as we don't have to wait for a read before being able to write. 

So if you import a cross ref from `A.hasFoo to B`, we can't check if A or B exist. (This only applies to the batch importer, the regular importer does validate both)

**Comment by bobvanluijt** [comment]
Would it be an idea to set it as flags?

I.e.

- `POST /v1/batching/things` skips all checks
- `POST /v1/batching/things?validate=checkA` skips all tests except checkA
- `POST /v1/batching/things?validate=checkA,CheckB` skips all tests except checkA and checkB
- etc

**Comment by etiennedi** [comment]
What's the advantage of using batch if batch has to perform checks? Why not just use the non-batch API then?

**Comment by bobvanluijt** [comment]
Adding + 1000 things without batch is not possible (i.e., Weaviate often (not always) times out if you add a lot of things one by one) and one by one is probably slower anyways than sending a big batch. Also, if there are multiple checks, you can enable a check which is crucial for your use case but disable others.

**Comment by etiennedi** [comment]
> Adding + 1000 things without batch is not possible (i.e., Weaviate often (not always) times out if you add a lot of things one by one

This is exactly what batch is avoiding by not doing those checks. It avoids the reads which slow down the entire system to a point where it doesn't work anymore. Adding those checks to batch would make batch basically identical with the non-batched endpoints. The only real difference would be in only disabling some checks. But any meaningful check needs a read-before-write, so we end up with the exact same situation.

**Comment by bobvanluijt** [comment]
> It avoids the reads which slow down the entire system to a point where it doesn't work anymore

You probably know way better than I do :-)

But isn't it a connection issue? Setting a short sleep and continuing often solves the issue.

**Comment by bobvanluijt** [comment]
I assume we want to keep this one open(?)
