### ISSUE TITLE
[SUGGESTION]: Allow user to "keep context" while doing follow-up queries

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#1203]
This idea suggests adding `context` parameters when doing an explore search. The use case is a user that wants to do a second query but who wants to stay in a specific semantic context.

Take the following example:

```graphql
{
  Get{
    Things{
      Product(
        explore: {
          concepts: ["soup"]
        }
      ){
        name
        _featureProjection{
          vector
        }
      }
    }
  }
}
```

Looking at results produced by the feature projection, a user might desire to do a followup request where they stay inside a specific context:

<img width="779" alt="Screenshot 2020-07-16 at 22 01 13" src="https://user-images.githubusercontent.com/5509162/87716940-e72e5900-c7af-11ea-8f50-1c1ddb9be64c.png">

The green bulb represents a specific result chosen by an end-user if the user now wants to do a new query but where they would like to stay in the context of the previous results they can specify it by adding the uuids as context.

Let's say that the two closest purple bulbs represent:

- `984b326b-8f3d-455e-8205-40c66f0e3dcc` => Pumpkin soup
- `f1671b0b-786b-4eda-9d67-0d1b5cef9402` => Vegetarian soup

A follow-up query might look like:

```graphql
{
  Get{
    Things{
      Product(
        explore: {
          concepts: ["vegetables"],
          context: ["984b326b-8f3d-455e-8205-40c66f0e3dcc", "f1671b0b-786b-4eda-9d67-0d1b5cef9402"] // these uuid's represent two soup products
        }
      ){
        name
      }
    }
  }
}
```

**Comment by bobvanluijt** [comment]
Nudge: @etiennedi @fefi42 @michaverhagen @laura-ham 
Also note: #1204

**Comment by etiennedi** [comment]
What does “stay in the context” mean? What would the second query return? How would it differ from one that does not have a context set?

**Comment by fefi42** [comment]
Isn't that something we could solve on the user side? Just feeding the last query together with the new one maybe with adjusted weights?

**Comment by etiennedi** [comment]
The way I understand the original draft this is actually happening on the user's side: I.e. there is no server-side state, but the user just "merges" their next query with the uuids they want to keep of the previous query? But I'm also not 100% certain what the second query would actually do?

**Comment by bobvanluijt** [comment]
> Isn't that something we could solve on the user side? Just feeding the last query together with the new one maybe with adjusted weights?

@fefi42 in theory yet, but it wouldn't be too handy because you need the vector representation of the complete object (i.e., UUID).

> What does “stay in the context” mean?

@etiennedi (et al) below in more detail.

---

Let's take the following query into consideration:

```graphql
{
  Get{
    Things{
      Product(
        explore: {
          concepts: ["Pepsi Cola"] # <== changing from soup to cola
        }
      ){
        name
        _featureProjection{
          vector
        }
      }
    }
  }
}
```

The following result may be returned:

<img width="569" alt="Screenshot 2020-07-13 at 15 34 37" src="https://user-images.githubusercontent.com/5509162/87930114-cacc3e00-ca87-11ea-9d20-2b689095f11b.png">

It might be the case that the results related to "cherry" might be the 3rd, 8th, and 12th results in the query.

What a user might want to do, is stick with the original query but search in a certain context (even other products might pop up).

<img width="569" alt="Screenshot 2020-07-13 at 15 34 37 2" src="https://user-images.githubusercontent.com/5509162/87930385-44fcc280-ca88-11ea-8ef8-780c4b7765a2.png">

### How would the user do this?

They provide the same query, but with the UUIDs of the things (in this case, products) that they want to stay in "the context off".

```graphql
{
  Get{
    Things{
      Product(
        explore: {
          concepts: ["Pepsi Cola"],
          context: ["UUID-for-product-cola-max-cherry", "etc..."]
        }
      ){
        name
      }
    }
  }
}
```

### How will the user now the UUID's?

1. Calculate them based on the `_featureProjection{}`. Or;
2. Having them as part of the `_nearestNeighbors{}` (hence: #1204)

### What will Weaviate do?

Search again based on: `centroid(vector for 'Pepsi Cola', "UUID-for-product-cola-max-cherry", "UUID-etc")`

**Comment by fefi42** [comment]
OK this makes it clear however I still have trouble imagining this workflow. You would need a search UI that allows you to query and select the context separately. Wouldn't a query context history make more sense in this way:

Query 1: `Pepsi Cola`
Results as shown above.
Query 2 stays in context of query one by adding `pepsi cola` to the new search-term `cherry`.

I think this would allow a more natural workflow. Also the last query could be weighted.

I am not sure how much the results would differ from @bobvanluijt proposal but I would assume that they don't differ too much.

**Comment by etiennedi** [comment]
> **What will Weaviate do?**
> Search again based on: centroid(vector for 'Pepsi Cola', "UUID-for-product-cola-max-cherry", "UUID-etc")

I think it would make sense then to put `context` into the existing `moveTo` object as it's essentially the same thing. Just not a "move to concept", but "move to object(s)"

**Comment by bobvanluijt** [comment]
> You would need a search UI that allows you to query and select the context separately.

@fefi42 Probably, but that is agnostic from the API offering the feature (I could imagine other ways of using this as well, hence #1204)

> Query 2 stays in context of query one by adding pepsi cola to the new search-term cherry.

@fefi42 But then you need to do manual work. If a user enters a query and next selects n+1 objects they like to "stay in the context of" you don't need to figure out that the context is about _cherry_, maybe it is something else hidden in the vectorized corpus.

> I think it would make sense then to put `context` into the existing `moveTo` object

Yes, I like that idea very much. The opposite should also work, `moveAway` from that context
