### ISSUE TITLE
Mapping conflict when indexing data

### ISSUE THREAD

**Issue by byronvoorbach** [semi-technologies/weaviate#1208]
I'm getting the following issue when indexing data into Weaviate:

`"stacktrace": ["java.lang.IllegalArgumentException: mapper [_meta.interpretation.source.weight] cannot be changed from type [long] to [float]"`

This issue is caused by the [dynamic mapping functionality ](https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-field-mapping.html) of Elasticsearch.
Take the following example:

1 - First docoument comes in with a weight of 1
2 - ES recognises as a Long mapping
3 - Second doc comes in with weight value of 0.12
4 - Exception for trying to change mapping from long to float

This can be fixed by creating a [dynamic index template](_meta.interpretation.source.weight) for all Weaviate properties in ES.

**Comment by etiennedi** [comment]
I think your analysis is spot on, while we do explicitly map the user-defined schema-props, the meta props are implicit. So ES might really choose the wrong type based on the first entry.

**Comment by etiennedi** [comment]
Closing as obsolete as Elasticsearch is no longer used in 0.23.0 and 1.0.0.
