### ISSUE TITLE
contextionary_nl containing weird concepts

### ISSUE THREAD

**Issue by byronvoorbach** [semi-technologies/weaviate#1210]
The current version of the Contextionary (nl0.16.0-v0.4.15) still contains some weird concepts:

For the following url:
`http://localhost:8080/v1/c11y/concepts/appel`

We get:

```
{
  "individualWords": [
    {
      "inC11y": true,
      "info": {
        "nearestNeighbors": [
          {
            "word": "appel"
          },
          {
            "distance": 5.648614,
            "word": "koekjesdadelblaadjesdadelcakedadelkoekjesdadelpastadadelsdadelskoekjesdadelspoederdagschoteldanoncakedanonede"
          },
          {
            "distance": 5.9698453,
            "word": "walnotencakedadel"
          },
          {
            "distance": 6.1200814,
            "word": "rijstgewone"
          },
          {
            "distance": 6.188902,
            "word": "pudingcusukdadel"
          },
          {
            "distance": 6.1948595,
            "word": "milkshakeavocadosalade"
          },
          {
            "distance": 6.2310214,
            "word": "kipavocadoslaavondmaaltijdaysh"
          },
          {
            "distance": 6.24075,
            "word": "aardbei"
          },
          {
            "distance": 6.2573767,
            "word": "broodglutenvrij"
          },
          {
            "distance": 6.334371,
            "word": "ananas"
          },
          {
            "distance": 6.334822,
            "word": "assarayaaziatische"
          },
          {
            "distance": 6.370806,
            "word": "koekjescustard"
          }
        ],
        "vector": ...
      },
      "word": "appel"
    }
  ]
}
```

There are more NL terms that cause this effect, if needed I can provide more of them

**Comment by etiennedi** [comment]
@laura-ham @fefi42 @bobvanluijt @michaverhagen - Tagging you because I need help from someone who speaks dutch. 

The above seems to be a recurring issue with contextionaries trained with common crawl data. Could some of you build a quality benchmark (manual or automated) that compares the `nl` contextionary versions `0.14.0` (pre-cc) and `0.16.0` (post-cc) against each other?

Ideally the benchmark would contain both a classification and explore `searches`. Thanks.

**Comment by etiennedi** [comment]
@byronvoorbach FYI, we've just found out that the NN-search on this endpoint does not use the same filtering as in the `_underscore` props. That's not intentional, but a bug. See #1211
