### ISSUE TITLE
[Discovery] Investigate splitting of compound words in contextionary

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1212]
When a compounded word such as `driehoeksbroodje` is not found in the c11y, we should evaluate if partial matches (such as `driehoek` and `broodje`) can be found instead.

## Goal
Investigate potential algorithms which aren't terribly expensive but yield good results

cc @fefi42 @byronvoorbach

**Comment by byronvoorbach** [comment]
Splitting of compound words for Dutch language can be a real pain, if needed we can help with some test cases

**Comment by fefi42** [comment]
@byronvoorbach that would certainly be helpful thanks.

**Comment by bobvanluijt** [comment]
> Splitting of compound words [for Dutch] language can be a real pain

We also have the C11y validation avaiable (e.g., using `driehoeksbroodje`, `driehoek` will be available `driehoeks` probably not) and word occurrences (e.g., in `driehoeksbroodje`, `driehoek` probably occures less often than `drie` therefor you could bias it towards `driehoek`) available as well, this might help in creating the compounding ago. 

I believe this could be a generic algorithm for Germanic and Latin languages.

**Comment by fefi42** [comment]
I have some test implementations lined up @bobvanluijt @byronvoorbach I could now use some example words to compare them.

**Comment by byronvoorbach** [comment]
I created [a gist](https://gist.github.com/byronvoorbach/e321fe9629000db9cb031bfe0eb8174e) with a few compound words. Let me know if you need more or need it to be in a different format :)

**Comment by fefi42** [comment]
These are the results of the best splitter:
```
Splitted blauwekaas into: [blauwe kaas]
Splitted vaatwastabletten into: [vaat wastabletten]
Splitted sojadrink into: [soja drink]
Splitted italiaansegroente into: [italiaanse groente]
Splitted babyvoeding into: [baby voeding]
Splitted pastagroenten into: [pasta groenten]
Splitted pizzabodem into: [pizza bodem]
Splitted sojayoghurt into: [soja yoghurt]
Splitted wijnglas into: [wijn glas]
Splitted snoeptomaten into: [snoep tomaten]
Splitted broodbeleg into: [brood beleg]
Splitted rundergehakt into: [runde gehakt]
```

The only error in this test is `vaat wastabletten` instead of `vaatwas tabletten`. The reason is that `vaat` is also a valid word and both results would have the same score so it just takes the first one. I don't think we can fix issues like this with a simple splitter. By simple I mean not machine learning based.

**Comment by fefi42** [comment]
https://github.com/semi-technologies/contextionary/pull/36

**Comment by etiennedi** [comment]
Closing as this has already been publicly released and is also explained in the docs.
