### ISSUE TITLE
Suggestion: Remove keywords

### ISSUE THREAD

**Issue by fefi42** [semi-technologies/weaviate#1223]
Suggestion to remove keywords from the schema.

Reasoning:
1. It is not entirely clear what they really do at this point.
They can be changed in the schema but this must mean that they are not part of the vectorization or only partially. 
2. They look like extra work. The Keywords look like they need to be specified for weaviate to work however one strength of weaviate is that you don't need to specify extra keywords to get your context.

**Comment by bobvanluijt** [comment]
Agreed

**Comment by etiennedi** [comment]
Awesome, I'll add that to the next release.
