### ISSUE TITLE
Docker compose files for all configurations

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#1226]
Ideally, there are individual docker-compose files that can be referenced in the documentation.

Differences:
- Version (i.e., '0.x.x' vs '1.x.x')
- C11y versions
- C11y language
- Compound words setting

**Comment by etiennedi** [comment]
What if we build a simple way to generate the required files on the fly? Otherwise we'd end up with a massive set of files. The things you mention alone would already be (using 2 for c11y model version 0.14.0 and 0.16.0) 40 different files. And which each potential new option that number would increase.

```
2 * 2 * 5 * 2  = 40
```

Alternatively we could have a simple API:

```
GET /docker-compose # serves the latest, default, english
GET /docker-compoes?language=de&contextionaryModel=0.16.0&compoundSplitting=true # de with 0.16.0 and compound Splitting
```

I think this would be much more flexible and would also make it much easier to allow for custom dropdowns in the Docs.

**Comment by bobvanluijt** [comment]
Perfect plan – maybe use cloud functions or so?

**Comment by etiennedi** [comment]
API suggestion, so you can get started building the front end:


*Returns a list of possible options for the language field*
```
GET /docker-compose/configuration/languages
Content-Type: application/json

{
  "languages": [
    {
      "value": "en",
      "label": "English",
    },
    {
      "value": "de",
      "label": "German",
    }
  ]
}
```

*Returns a list of possible options for the model field field,* **only returns the models that are available for the selected langauge** (Render this field only after the user has selected a language in the first field).
```
GET /docker-compose/configuration/contextionary-models?language=en
Content-Type: application/json

{
  "contextionary-models": [
    {
      "value": "0.14.0",
      "label": "0.14.0 (Glove, Wikipedia Only)",
    },
    {
      "value": "0.16.0",
      "label": "0.16.0 (Glove, Common Crawl + Wikipedia)",
    },
    {
      "value": "0.17.3",
      "label": "0.17.3 (FastText, Common Crawl + Wikipedia)",
    },
  ]
}
```

*Generate a docker-compose file based on the selected values. All query params are optional. It defaults to something reasonable*
```
GET /docker-compose/?contextionary-model=0.17.3&language=en
Content-Type: text/yaml

version: 3.3
services:
  weaviate:
...
```

**Comment by etiennedi** [comment]
I think the decision flow should be:

1. Vector Search or Semantic Search Mode (will error on Vector Search for now)
2. Contextionary language *(only if mode == Semantic Search)*
3. Contextionary Model (Glove, Fasttext, etc.) *(only if mode == Semantic Search)*
4. Additional features: e.g. Compound Splitting *(only if mode == Semantic Search)*
5. Weaviate Mode (Elasticsearch vs. Standalone)

where each next question depends on the previous input.

**Comment by bobvanluijt** [comment]
Perfect
