### ISSUE TITLE
Playground with the lately released arXiv full dump (4.3Gb)

### ISSUE THREAD

**Issue by x0rzkov** [semi-technologies/weaviate#1228]
Hi guys,

Hope you are all well !

I was wondering if it is possible to create a playground with the latest arXiv dataset available here with weaviate. I am curious to see the results on 4.2Gb database.

Refs.
- https://www.kaggle.com/Cornell-University/arxiv

# to get the dump
```bash
gsutil ls gs://arxiv-dataset/metadata-v5/
gsutil cp gs://arxiv-dataset/metadata-v5/arxiv-metadata-oai.json .
```

Is it possible to index this dataset quickly as there is an update every week ?

Thanks in advance for your insights and inputs

Cheers,
X

**Comment by bobvanluijt** [comment]
Hi @x0rzkov – that's definitely possible :)

@laura-ham maybe you can help because you've done more with research related docs?

**Comment by etiennedi** [comment]
Before the stalebot tries to close this. This is actually complete, right? Or is there any other reason to keep this open @laura-ham or @x0rzkov?

For those of you landing here via Google, let me redirect you to the correct repository: 

https://github.com/semi-technologies/arXiv-demo-dataset

**Comment by laura-ham** [comment]
@etiennedi this is complete, yes. The dataset is currently even running as demo dataset on [https://arxiv.demo.data.semi.technology/v1/](https://arxiv.demo.data.semi.technology/v1/) if you want to try it out. This issue can be closed from my perspective.

**Comment by etiennedi** [comment]
Thanks, closing.
