### ISSUE TITLE
Change name of schema in data object

### ISSUE THREAD

**Issue by fefi42** [semi-technologies/weaviate#1234]
```
{
  "id": "123",
  "class": "Transformer",
  "schema": {
    "name": "Optimus Prime"
  }
}
```
The field name `schema` is confusing in the data object. It should be `properties` because that is what it defines. 

This change is `on hold` until end of year 2020 due to other priorities.

**Comment by etiennedi** [comment]
@bobvanluijt @laura-ham @antas-marcin 

Are we making this part of v1.0.0?

**Comment by bobvanluijt** [comment]
It would be a breaking change, right?

**Comment by etiennedi** [comment]
> It would be a breaking change, right?

yes.

FYI: I'm currently adding this to the list of breaking changes for V1 with status "Proposal", meaning we can use the next discussion session to finalize this.

**Comment by etiennedi** [comment]
I'm only now realizing what an awesome issue number this issue has 🤣
