### ISSUE TITLE
Remove not implemented endpoints from RESTful open api specs

### ISSUE THREAD

**Issue by laura-ham** [semi-technologies/weaviate#1235]
The following endpoints are reflected in the Open API specs, but are not implemented in Weaviate (and will not be implemented (soon or ever) either), and thus should be removed from the documentation in Open API specs:

- [x] PUT `v1/schema/actions/{className}`
- [x] PUT  `v1/schema/actions/{className}/properties/{propertyName}`
- [x] DELETE  `v1/schema/actions/{className}/properties/{propertyName}`
- [x] PUT `v1/schema/things/{className}`
- [x] PUT  `v1/schema/things/{className}/properties/{propertyName}`
- [x] DELETE  `v1/schema/things/{className}/properties/{propertyName}`
- [ ] the `meta` parameter in `GET v1/{semantic_kind}` is deprecated but still in the specs
- [x] anything related to `/p2p`

For reference: (https://app.swaggerhub.com/apis/semi-technologies/weaviate/0.22.15#/)

Related to https://github.com/semi-technologies/weaviate/issues/973

_This list might be extended in the coming days_

**Comment by etiennedi** [comment]
None of these work at the moment, so removing any of those can't break anything correct?

**Comment by laura-ham** [comment]
Correct, from my point of view it should indeed not be possible to break anything.

**Comment by laura-ham** [comment]
> @bobvanluijt @laura-ham
> Should we remove the `/p2p` endpoints as well? They also don't do anything at the moment...

I vote for removing it until we need and implement actual p2p functions

**Comment by bobvanluijt** [comment]
+1 for removal

**Comment by etiennedi** [comment]
Re

>  the meta parameter in GET v1/{semantic_kind} is deprecated but still in the specs
 
I can't remove that yet unforunately, as that would be a breaking change. The `openapi` specs are the source of truth for the API server, so if I remove it from there it would be completely gone and we'd have a breaking change.

---

I've removed all the other ones and all tests are still passing, so that's a good indication, they were really all unused/unimplemented.
