### ISSUE TITLE
Classification resets `_interpretation` property

### ISSUE THREAD

**Issue by fefi42** [semi-technologies/weaviate#1237]
After running a classification all the objects on which a label was set have `_interpretation` set to `null`.

**Comment by etiennedi** [comment]
There is already a check that says "don't overwrite existing _underscore props": https://github.com/semi-technologies/weaviate/blob/6f256e74482f3f3f2e96b0acb18cd3421c0df789/usecases/classification/classifier_run.go#L155-L158

So it's not something as obvious as I was hoping for.

**Comment by etiennedi** [comment]
Maybe we need to explicitly specify all underscores when reading, i.e. the check always returns `nil`, because we never ask for the props when reading them?

**Comment by fefi42** [comment]
Can be. I just know that the `_interpretation` is gone after a classification was executed on the specific object.

**Comment by antas-marcin** [comment]
In @etiennedi explicitly setting the additional parameters fixed the issue. This PR #1421 fixes this issue
