### ISSUE TITLE
Import raw vector, search by raw vector

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1245]
## Background

Moving towards `1.0.0` there will be an option not to use the Semantic Search extension, which also means no Contextionary will be used. For this the user has to be able to

1. Provide their own vectors with their data objects
2. Perform an explore (or similar) search by specifying a custom search vector.

## Goals of this issue

Propose and discuss an API

TODO ~~@etiennedi Make a first proposal~~ @laura-ham has taken over the proposal making :)

**Comment by laura-ham** [comment]
@etiennedi @antas-marcin @bobvanluijt 

I was thinking that inputting a `vector` as a starting point for a query in the vector space, in essence will do the same as when you use the current `explore` filter with words in `concept` (except for the NLP part, for which we need the NLP Module). Because in both cases, Weaviate will look for the nearest neighbors with a vector as starting point (the vector will be created by the NLP module when `concepts` are given). Sooo, what do you think of including `vector` or `rawVector` into the explore filter? 

```graphql
{
    Get {
        Things {
            Article (
                explore: {
                    vector: [3.094, 5.340, ..., 2.784]
                }
            ) {
                name
            }
        }
    }
}
```

We have to consider also:
1. When using `explore`, exactly ONE of `vector` or `concepts` can be passed (not both, and not none).
2. I think we can keep `moveTo` and `moveAwayFrom`, and also add `vector` in those objects.
3. This means that the `explore` filter will always be available with Weaviate Core, without any Modules.

What do you think? About
1. The ux of having `vector` inside the `explore`, with keeping the restriction of point 1 above in mind.
2. Is it possible implementation wise? So 
    1. dynamically adding filter objects and restrictions depending on the Modules on top of Weaviate Core? 
    2. the length of the vector array should match the dimensions of the Weaviate vector space. How to make this clear to the user, and what to do if it doesn't match (simply returning an error works, but just to keep this in mind)

**Comment by etiennedi** [comment]
My initial thoughts:

1. Adding `vector` to `explore` would complicate the defintion of what a module is, quite a bit in my opinion. Because as of now we said a module would be something that can (among other things) either extend the API(s) or provide a vectorization process. If we allow the `nlp` module to hook into the `explore` block, essentially the module definition becomes (in addition to the things above) "...or provide additional fields to the existing `explore` block in GraphQL". So an image module would also have to hook into this explore block somehow. This would make for a really complex module API design, especially with the validation rules you already outlined. (We'd need to check that exactly one way is used, etc.). So, I'm definitely in favor of having separate objects such as `textExplore`, `vectorExplore` etc. The names are just to outline the intention, not meant as actual proposals.

2. Regarding possiblity
  i. Certainly possible, but I imagine quite complex. Also because the module would not just hook into extending the `explore` object. It would also have to hook into the part that interprets that `explore` objects, as it needs to provide something to read the `concepts` fields and return a vector for it. So, as outlined above, I think this would be cleaner if a module could only provide entire objects which are not interfered with by other modules

  ii. At the moment we simply error if `len(a) != len(b)`. But the target length is not defined anywhere. It's implicitly assumed based on the first thing you import. It might make sense to make this an explicit setting? Because then we could also fail at import time if object1 has a different vector length from object2.

**Comment by laura-ham** [comment]
You raise very valid points

Alright, then what about something like:

```graphql
{
    Get {
        Things {
            Article (
                nearVector: [3.094, 5.340, ..., 2.784]      # or exploreVector
            ) {
                name
            }
        }
    }
}
```

Would just a vector array be enough, or do we want (either now or in the future) extend this search filter by e.g. direction (like `moveTo` and `moveAwayFrom`). Then we should make it an object already to avoid possible breaking changes in the future, i.e.:

```graphql
{
    Get {
        Things {
            Article (
                nearVector: {
                    vector: [3.094, 5.340, ..., 2.784]      # or exploreVector
                }
            ) {
                name
            }
        }
    }
}
```

**Comment by etiennedi** [comment]
Some thoughts:

1. I really like the `nearVector` name, I think that's clear (I'd also be fine with an alternative `exploreVector`, but I think "near" is even clearer)
2. I don't see a need for `moveTo` and `moveAway` from. Since the user already has to calculate/provide their own vector, they could also do any movement (if applicable) as part of that process
3. I think we should rename the current explore to make more clear that it's about text. For example if we go with `nearVector`, the equivalent for text would be `nearText` (similarly `exploreText` if we go with `exploreVector`).

**Comment by bobvanluijt** [comment]
Do we want to also allow for specific vector operations like: search in a cluster around this vector, search in between these X-amount of nodes, search in between these X-amount of vectors, etc.

**Comment by etiennedi** [comment]
> Do we want to also allow for specific vector operations like: search in a cluster around this vector, search in between these X-amount of nodes, search in between these X-amount of vectors, etc.

I'm not sure I'm following - could you give an example for each of those. What  query would look like? Essentially all our underlying vector indices have only a single functionality: a kNN-search around a vector position, but maybe this is something that would be sufficient for the search types your're suggesting?

**Comment by bobvanluijt** [comment]
I was asking because there might be other functions which we are currently not thinking about besides nearest neighbors alone. Just something to keep in mind.

**Comment by etiennedi** [comment]
I think as long as we go with the "wrapped in an object" approach as outlined by @laura-ham we can always add new fields to `nearVector` in a non-breaking fashion. If we come up with something completely new that doesn't fit the description of `nearVector` we can always add a new object.

(By the way just using `nearVector` as an example term for what the object is going to be called. I think there hasn't been a `nearVector` vs `exploreVector` decision yet.)
