### ISSUE TITLE
Feature suggestion: allow sorting of GraphQL result 

### ISSUE THREAD

**Issue by laura-ham** [semi-technologies/weaviate#1254]
Current design of GraphQL queries don't allow sorting based on property value. The results of `Explore` functions and functions with `explore` filter sorts the results based on the `certainty` of the result relative to the query. A suggestion is to implement the argument field `orderBy` (or `sortBy`) on class level, with the possible values `desc` (or `descending`) and `asc` (or `ascending`), like this:

```graphql
{
    Get {
        Things {
            Paper (orderBy: {year: asc}) {
                title
                year
            }
        }
    }
}
``` 

It should be possible to create the property field in the argument to sort by (here: `year`) from the schema, so that no string from the user input has to be parsed (like requiring `{"year": acs}`), because this would be more error prone. 

This could also work for nested (reference) properties: 

```graphql
{
    Get {
        Things {
            Paper (orderBy: {InJournal: {name: desc}}) {
                title
                year
                InJournal {
                    ... on Journal {
                        name
                    }
                }
            }
        }
    }
}
``` 

If this nested operation doesn't work, then let's go for the following which is more in line with the current design of other GraphQL filters we use:

```graphql
{
    Get {
        Things {
            Paper (orderBy: {
                path: ["desc"],
                order: asc 
                } ) {
                title
                year
            }
        }
    }
}
``` 

and 

```graphql
{
    Get {
        Things {
            Paper (orderBy: {
                path: ["InJournal", "Journal", "name"],
                order: asc 
                } ) {
                title
                year
                InJournal {
                    ... on Journal {
                        name
                    }
                }
            }
        }
    }
}
```

Also sorting on multiple property values should be possible: first by the year and then by the rating: 

```graphql
{
    Get {
        Things {
            Paper (orderBy: [{
                path: ["InJournal", "Journal", "name"],
                order: asc 
                }, {
                path: ["year"],
                order: desc 
                }]) {
                title
                year
                InJournal {
                    ... on Journal {
                        name
                    }
                }
            }
        }
    }
}
```

Sorting rules of data types can be straightforward:
- string: alphabetically on first letter
- int/number: just natural number ordering
- date: natural calendar order
- boolean: asc= first false, then true. Descending first True then False
- geoCoordinates: suggestions? (usually you sort geoCoordinates from a base coordinate, then this should be provided in the filter)
- phoneNumber: don't support this (I see no value) or otherwise by numbers

For a nice example, see https://hasura.io/docs/1.0/graphql/core/queries/sorting.html#sort-query-results.

Any thoughts? 

**Edit**
The more I think about it, the more I see why the second method (with the strings) is actually better because this is more in line with the current design. Agree?

**Comment by laura-ham** [comment]
@x0rzkov Any additions?

**Comment by laura-ham** [comment]
still relevant in my opinion

**Comment by lucmichalski** [comment]
Of course, especially for e-commerce use-cases ^^

**Comment by etiennedi** [comment]
Keep open, still relevant

**Comment by laura-ham** [comment]
Still relevant 🙋‍♀️

**Comment by etiennedi** [comment]
Keep. Will be part of the v1.13.0 or a similar release.
