### ISSUE TITLE
Parity between explores queries

### ISSUE THREAD

**Issue by fefi42** [semi-technologies/weaviate#1258]
In the GraphQL Get with (explore) filter it is not possible to see the distance(certainty) between the explore and the object as it is in the GraphQL Explore function. 

Would it be possible to add this to the filter?

GraphQL Get with (explore):
```
{
  Get {
    Things {
      Song (explore: {
        concepts: ["happy glad good"] 
      }){
        uuid
      }
    }
  }
}
```

GraphQL Explore function:
```
{
  Explore (
    concepts: ["good, happy, glad"]
   ) {
    certainty
    className
    beacon
  }
}
```

**Comment by bobvanluijt** [comment]
+1 for underscore props in Explore{}

**Comment by etiennedi** [comment]
@bobvanluijt feel free to open a separate issue for that. In order to be able to move fast (and aid in fixing #995), I want to limit this issue's scope to Felix' original inquiry: Add certainty to `Get` with `explore`.

@laura-ham Felix suggested adding the certainty as an underscore prop. I think that's a good idea as it would fit with the other underscore props. However, it would also make it slightly inconsistent with the `Explore{}` API where certainty is a "regular" prop. Any thoughts?

**Comment by laura-ham** [comment]
> @laura-ham Felix suggested adding the certainty as an underscore prop. I think that's a good idea as it would fit with the other underscore props. However, it would also make it slightly inconsistent with the Explore{} API where certainty is a "regular" prop. Any thoughts?

I'd add it as an underscore prop. This is consistent with having all data object info except for the actual properties and the uuid accessible via the underscore. So it would be:
```graphql
{
  Get {
    Things {
      Article(
        explore: {
          concepts: ["fashion"]
      }) {
        title
        _certainty
      }
    }
  }
}
```

with potential result:
```json
{
  "data": {
    "Get": {
      "Things": {
        "Article": [
          {
            "title": "Social justice and sustainability at Men's Fashion Week in London",
            "_certainty": 0.73
          },
          {
            "title": "Ballgowns, champagne bags and Gaultier's final show at the Haute Couture week in Paris",
            "_certainty": 0.64
          }
        ]
      }
    }
  },
  "errors": null
}
```

I think that we could make the underscore props consistent along with the `Explore{}` function over time, as @bobvanluijt suggests. We can then add `_certainty` in `Explore{}` as well, but with deprecation time (meaning that both `_certainty` and `certainty` can be there for a while).

**Comment by laura-ham** [comment]
See also https://github.com/semi-technologies/weaviate/issues/995 to see why displaying `_certainty` in the results adds value.
