### ISSUE TITLE
Introduce info message field in GraphQL results

### ISSUE THREAD

**Issue by laura-ham** [semi-technologies/weaviate#1289]
Based on a conversation with @bobvanluijt, we want to propose the possibility of adding informative messages to GraphQL results. This can be done using the `extensions` return field of GraphQL. This is an underexposed field in the GraphQL docs (https://github.com/graphql/graphql-spec/blob/master/spec/Section%207%20--%20Response.md#response-format) and in usage, but it's available next to `data` and `errors`, like:

```json
{
    "data": {},
    "errors": null, 
    "extensions": {
       ...
    }
}
```

For example in case of doing a `Get` query with `explore` filter, additional information about the (not) returned data is useful. Imagine no results are returned because the `certainty in the filter was set too high by the user, and no results are returned because their calculated `_certainty` is too low. We could like to inform the user about this to explain why they see no results, and improve the UX. In this case, the result could look like this: 

```json
{
    "data": {},
    "errors": null, 
    "extensions": {
       "info": "There are no data objects returned because all data objects have a lower certainty than the certainty in the filter. Lower the certainty value in the filer to return data objects with lower calculated certainty."
    }
}
```

Note: this issue just addresses including the possibility to add "info" messages in the "extensions" field. Actual info messages will be proposed in other issues, for example in https://github.com/semi-technologies/weaviate/issues/1138. 

@etiennedi @antas-marcin what do you think about adding this?

**Comment by etiennedi** [comment]
I like the idea. Can you point me to where that is defined in the spec? If I follow the link in your post above it doesn't show the field next to `data` and `errors`, but only as a nested field within the error object. The example on the page shows:

```json
{
  "errors": [
    {
      "message": "Name for character with ID 1002 could not be fetched.",
      "locations": [ { "line": 6, "column": 7 } ],
      "path": [ "hero", "heroFriends", 1, "name" ],
      "extensions": {
        "code": "CAN_NOT_FETCH_BY_ID",
        "timestamp": "Fri Feb 9 14:33:09 UTC 2018"
      }
    }
  ]
}
```

Am I missing the place where it says that this can be added as a root object?

**Comment by laura-ham** [comment]
They are indeed not clear where this field is placed. I read it as 'in the map next to `data` and `errors`" 

See the last paragraph here. 
![image](https://user-images.githubusercontent.com/26965746/98977266-b7525080-2518-11eb-90c1-e97dbad3b467.png)

Also here they mention it: https://dgraph.io/docs/graphql/api/requests/#responses

**Comment by etiennedi** [comment]
Good points, the docs are a bit confusing because the example only lists the extensions key within the error. But the way I understand it now - both is possible, an extensions field at root level *and* within each error object.

Thanks, clear.

**Comment by etiennedi** [comment]
Next we need to verify if the Go GraphQL Implementation acutally supports that. It has a type called [Extensions](https://github.com/graphql-go/graphql/blob/dd05d5e04e778045859bc3f2d65166a98a9f1f46/extensions.go#L33-L57) but I'm not sure if they refer to the `extensions` field - or if they're something completely different. The API of this type suggests that it's maybe rather something to extend the library itself?
