### ISSUE TITLE
Discussion: Desired Behavior and Cost of Like operator in Standalone

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1290]
# Goal

The `Like` operator has no exactly defined behavior in pre-Standalone, as it was essentially just passed on to do a `wildcard` search in Elasticsearch. The point of this discussion thread is to define the behavior and decide how to implement it. An inverted index does not naturally support such wildcarded queries. As a result a workaround is required. Elasticsearch also does such workarounds - what exactly they do is not clear to me. But they do consider the `wildcard` operator to be [an expensive query with a high upfront cost](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-wildcard-query.html)

# Desired Behavior

This to make sure we are on the same page regarding the capabilities:

* `?` -> exactly one unknown character
* `*` -> zero, one or more unknown characters
* `car?` matches `cart`, `care`, but not `car`
* `car*` matches `car`, `care`, `carpet`, etc
* `*car*` matches `car`, `healthcare`, etc.

Agreed?

# Implementation options

Currently I see two implementation options, that are feasible for the short-term. This excludes fancier options such as ngrams, etc.

### Description
- We iterate over the entire inverted index for the specified property and check if the property is a match using a regular expression.

### Advantages
- Lowest implementation cost

### Disadvantages
- Each query iterates over the entire inverted index for that prop.
- The search time will go up linearly with the dataset size. 
- There is a point, where this query is too expensive, and will not work anymore

### Description
- If a query does not start with a `*` or `?` we can optimize this query
- Instead of doing a full index scan, we only scan the parts where the first `n` characters are a match (where `n` is the number of characters before the first wildcard operator)
- We check for a match using a regular expression only on those entries that matched the previous step
- For those queries that begin with `*` or `?` we fall back to Option 1

### Advantages
- The more characters are used before the first wildcard, the more efficient the query will become

### Disadvantages
- Higher implementation cost than Option 1
- No performance gain if query starts with a wildcard

## Option 3
... make a suggestion!

# Decisions

1. Is the outlined behavior the desired behavior, if not, what is?
1. Is this operator important enough to justify the extra effort of Option 2 or should we go with Option 1 for now and accept that this operator will break/be very slow on large datasets?

**Comment by fefi42** [comment]
I have many cases that use wildcards prefixes. There it would also be an option to run other where filters first (if they exist ofc.) to reduce the search space.

**Comment by bobvanluijt** [comment]
I don't have a strong opinion on this, I think mostly @fefi42's, @michaverhagen's, and @StefanBogdan's are important from a user perspective. Maybe @laura-ham has some thoughts on UX?

**Comment by laura-ham** [comment]
Point 1: The desired behaviour seems right.
Point 2: Can't say much about UX without actual numbers about the effect of dataset size and effect on performance. Nevertheless, the approach @fefi42 mentions (other `where` filters first) is good for sure. And if the filter isn't used much at the moment, then I'm voting for option 1 for now.

**Comment by etiennedi** [comment]
Ok, thanks for the input. We're going with Option 1 at first and then see how we're on time and how much effort it would be to go for Option 2, as well. 

> There it would also be an option to run other where filters first (if they exist ofc.) to reduce the search space.

That's not an easy option unfortunately, because in an inverted index, each operator is independent (so it can also be paralellized) and aftewards we merge the results. So for example if we have an AND operator, then internally we perform two independent searches (which are quite cheap thanks to being an inverted index) and then merge the results. So if search 1 returned docs `1, 3 , 5` and search 2 returned `1, 2, 3`, then we serve the intersection of that (`1,3`) to the user. So, similarly on a `Like` search - even if it was combined with another operator, it would always act upon the whole search space unless we build some very specific logic that only applies to the Like operator in combination with another operator - which is something that's not really worth the cost at the moment, I believe.
