### ISSUE TITLE
Discussion: API for per-class configuration in V1.0.0

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1305]
# Goal of this discussion

With the upcoming completion of Standalone and the modularization from v1.0.0, we have a new requirement to provide configuration per class. At least the following requirements need to be met:

1. **Each class configures one vectorizer module (or none)**. Example: Class "Article" should be vectorized by the `text2vec-bert` module, the class "Image" is vectorized by `img2vec-resnet50` and the class "FancyMLThing" is not vectorized at all because the user provides the vectors themselves.

1. **Each module can provide module-specific configuration for the overall class** Example: The class vectorized by `text2vec-bert` must make decisions about whether the className should be vectorized (currently done with `vectorizeClassName: bool`. Such a decision does not make sense on the other two classes.

1. **Each module can provide module-specific configuration for one (or more) of the properties of the class** Example: The class vectorized by `text2vec-bert` must make decisions about which property should be included in the vectorization (e.g. `name` should be included, but `customerId` should not. Similarly for the `img2vec-resnet50` class, it might be required to highlight which proprerty contains the image. For the "FancyMLThing" class, no such decisions have to be taken.

1. Weaviate `v1.0.0` will allow for different vector index types. The only supported index at release is `HNSW`, but in the future we might se others, such as `ScaNN`. **It must be possible to select which index type should be used for the vector index of a class.**

1. Each different vector index will have specific configuration. For example in `HNSW` the user can set `efConstruction` and `maxConnections`. However, there are also implementation specific parameters, such as `maximumCacheSize`. **It must be possible to set the right configuration parameters for each index.**

1. We do not know what other modules will be added in the future. **It must be extendable with regards to module configuration.**

1. We do not know what other index types will be added in the future. **It must be extendable with regards to vector index configuration.**

**Comment by bobvanluijt** [comment]
I don't have any specifics to add. Looking forward to see the end result :)

**Comment by etiennedi** [comment]
For decision log see: https://docs.google.com/document/d/1o_77mX0cMyGPDB6DQYeWRKwy4ZsLP7rZYAxr4YKzNlg/edit#
For issues resulting from the decision log, see: https://github.com/semi-technologies/weaviate/milestone/16
