### ISSUE TITLE
SUGGESTION: Solve "fuzzy" relations like one-shot classification?

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#1320]
Related to: https://github.com/semi-technologies/weaviate/issues/955, https://github.com/semi-technologies/weaviate/issues/1163, https://github.com/semi-technologies/weaviate/issues/1319

Fuzzy references have been on our wishlist, would it be an idea to resolve this like we do with classifications?

1. If a reference count is 0.
2. If a user specifies a type of classification?

E.g.;

```graphql
{
  Get{
    Article(
      explore: ["monkeys"]
    ){
      title
      OfCategory(
        fuzzyref: {
          type: "knn"
          # etc...
        }
      ) {
        ... on Category{
          name
        }
      }
    }
  }
}
```

**Comment by etiennedi** [comment]
Great idea, I like this!
