### ISSUE TITLE
Remove Things and Actions

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1336]
## Background

With opening up Weaviate for all kinds of use cases the distinction between Things and Actions no longer makes sense. Additionally from a UX perspective, always having to specify the semantic kind is an additional step the user has to do over and over.

## Goals

* [x] T/A are removed from the schema endpoint, as outlined in [Point 4](https://docs.google.com/document/d/1o_77mX0cMyGPDB6DQYeWRKwy4ZsLP7rZYAxr4YKzNlg/edit#heading=h.ofrapwy2issl)
* [x] Data is served on the `/v1/objects` endpoint and `/v1/things` and `/v1/actions` are removed as outlined in [Point 5](https://docs.google.com/document/d/1o_77mX0cMyGPDB6DQYeWRKwy4ZsLP7rZYAxr4YKzNlg/edit#heading=h.hejttxs6a9x2)
* [x] In GraphQL `Get {}` and `Aggregate {}` the T/A level is removed as outlined in [Point 6](https://docs.google.com/document/d/1o_77mX0cMyGPDB6DQYeWRKwy4ZsLP7rZYAxr4YKzNlg/edit#heading=h.otyxcr6srq78)
* [x] The short-form and long-form beacon when validated, parsed and resolved no longer contains T/A as outlined in [Point 7](https://docs.google.com/document/d/1o_77mX0cMyGPDB6DQYeWRKwy4ZsLP7rZYAxr4YKzNlg/edit#heading=h.iq1yg4iohigv) and [Point 8](https://docs.google.com/document/d/1o_77mX0cMyGPDB6DQYeWRKwy4ZsLP7rZYAxr4YKzNlg/edit#heading=h.8j8z6debr3h9)
* [x] In all internal places where we currently make a distinction between Things/Actions, the duplication is removed instead of thing/action one object can be labelled "object"

## Notes

* For any goswagger-related changes, always adapt `openapi-specs/schema.json` first, then run `tools/gen-code-from-swagger.sh` for the auto-generation to take effect.
* Besides the API endpoints internally we are probably facing a lot of T/A logic in the `usecases/kinds` package (should probably be renamed to `usecases/objects`) as well as in `adapters/repos/db` where a lot the `storobj` explicitly distinguishes between T/A

**Comment by antas-marcin** [comment]
Changes merged with master
