### ISSUE TITLE
Rename existing endpoints/APIs/Schema

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1337]
## Background

We want to use the breaking change that comes with v1 to clean up some stuff that will be breaking. The motivations for the changes in this issue have varying causes, but none are related to the removal of things and actions which are all grouped into #1336 

The motivation behind this issue was to group all renaming that have no logical changes, but only name changes.

## Goals

* [x] `/v1/batching` is renamed to `/v1/batch` as outlined in [Point 9](https://docs.google.com/document/d/1o_77mX0cMyGPDB6DQYeWRKwy4ZsLP7rZYAxr4YKzNlg/edit#)
* [x] The current `explore` sorter in GraphQL get is renamed to `nearText` to indicate it depends on the text media type as outlined in [Point 15](https://docs.google.com/document/d/1o_77mX0cMyGPDB6DQYeWRKwy4ZsLP7rZYAxr4YKzNlg/edit#heading=h.12bao5x67q2e)
* [ ] The current `contextual` classification is renamed to `text2vec-contextionary-classification` as outlined in [Point 22](https://docs.google.com/document/d/1o_77mX0cMyGPDB6DQYeWRKwy4ZsLP7rZYAxr4YKzNlg/edit#heading=h.lklmgq8b3k68)
* [x] In a data object (not in a schema class!) the property `schema` is renamed to `properties` as outlined in [Point 24](https://docs.google.com/document/d/1o_77mX0cMyGPDB6DQYeWRKwy4ZsLP7rZYAxr4YKzNlg/edit#heading=h.rcvzlp87o382)

## Notes
* Look at the issue number 😆

**Comment by laura-ham** [comment]
> In a data object (not in a schema class!) the property schema is renamed to properties

What do you mean with 'not in schema class'? 

Additionally, I just noticed `'properties'` is used a lot in the api specs to indicate properties of API definitions (https://github.com/semi-technologies/weaviate/blob/master/openapi-specs/schema.json), I hope this won't cause any issues.

**Comment by etiennedi** [comment]
> > In a data object (not in a schema class!) the property schema is renamed to properties
> 
> What do you mean with 'not in schema class'?

My intention was to convey that this affects [this object](https://app.swaggerhub.com/apis/semi-technologies/weaviate/0.22.20#/things/things.create), but [not this one](https://app.swaggerhub.com/apis/semi-technologies/weaviate/0.22.20#/schema/schema.things.create) where the equivalent field is already called `properties`.

> Additionally, I just noticed `'properties'` is used a lot in the api specs to indicate properties of API definitions (https://github.com/semi-technologies/weaviate/blob/master/openapi-specs/schema.json), I hope this won't cause any issues.

I think this won't be an issue as we were already able to use `properties` in [here](https://app.swaggerhub.com/apis/semi-technologies/weaviate/0.22.20#/schema/schema.things.create).
