### ISSUE TITLE
Remove kind.Object

### ISSUE THREAD

**Issue by antas-marcin** [semi-technologies/weaviate#1366]
## Background

In #1359 we have reduced what previously was two options in kind (`kind.Thing` and `kind.Action`) to a single one which is always `kind.Object`. This is no longer needed, as a kind can never be anything but an `Object`. We can thus remove this entirely. However, we didn't include this in #1359 as time was critical.

**Comment by etiennedi** [comment]
This is a nice-to-have to the Milestone, as doing this later would be non-breaking.
