### ISSUE TITLE
Fix schema endpoints

### ISSUE THREAD

**Issue by antas-marcin** [semi-technologies/weaviate#1368]
Fix schema endpoint according to documentation [point 4](https://docs.google.com/document/d/1o_77mX0cMyGPDB6DQYeWRKwy4ZsLP7rZYAxr4YKzNlg/edit#heading=h.ofrapwy2issl)

**Comment by etiennedi** [comment]
As discussed on Slack, as part of this we also want to remove the `type` field in the schema response 
![image](https://user-images.githubusercontent.com/8974479/103627624-2eff9300-4f3e-11eb-8cda-1c574cde901c.png) as this no longer has any meaning
