### ISSUE TITLE
Search based on objects

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#1427]
## UPDATE

See https://github.com/semi-technologies/weaviate/issues/1427#issuecomment-763775356 for the latest API design, the content of this post is somewhat outdated

----

It would be great if Weaviate could search based on a data object. A single word functions as a token to vectorize, but if you could take the vector of a data object as input it allows to search based on objects besides concepts.

As a first suggestion:

```graphql

  Get{
    Publication(
      nearText: {
        concepts: [$("27b5213d-e152-4fea-bd63-2063d529024d"), "fashion"],
        certainty: 0.7
      }
    ){
      name
      _additional {
        certainty
      }
    }
  }
}
```

or

```graphql
{
  Get{
    Publication(
      nearVector: {
        vector: $("27b5213d-e152-4fea-bd63-2063d529024d")
      }
    ){
      name
      _additional {
        certainty
      }
    }
  }
}
```

PS:
I remember we've had a similar issue but I can't find it. If only Github was using Weaviate 😇

**Comment by etiennedi** [comment]
I like this idea. I think we could just add a new field `beacon` inside `nearVector` which takes an existing beacon, e.g.:

```graphql
      nearVector: {
        beacon: "weaviate://localhost/27b5213d-e152-4fea-bd63-2063d529024d"
      }
```

which means: Take the vector position of the object you can find at this beacon and search around it.

cc @laura-ham

**Comment by laura-ham** [comment]
Good idea.

What about the following, to make it clear that the search is around an object?

```graphql
      nearObject: {
        beacon: "weaviate://localhost/27b5213d-e152-4fea-bd63-2063d529024d"
        id: "27b5213d-e152-4fea-bd63-2063d529024d" // alternative for local objects
      }
```

**Comment by bobvanluijt** [comment]
So, if I understand it correctly:

```graphql
 Get{
    Publication(
      nearText: {
        beacon: "weaviate://localhost/27b5213d-e152-4fea-bd63-2063d529024d"
        concepts: ["fashion"]
        certainty: 0.7
      }
    ){
      name
      _additional {
        certainty
      }
    }
  }
}
```

**Comment by etiennedi** [comment]
I really like @laura-ham's proposal, I think that's very clear. I'm not sure I understand @bobvanluijt's latest proposal. Why is `beacon` in `nearText`?

**Comment by bobvanluijt** [comment]
>  I'm not sure I understand @bobvanluijt's latest proposal

It's not a proposal ;-) I'm not sure I understand what a full query would look like

**Comment by etiennedi** [comment]
I understand it like this:

For an object of the same class:
```graphql
{
  Get{
    Publication(
      nearObject: {
        id: "27b5213d-e152-4fea-bd63-2063d529024d"
      }
    ){
      name
      _additional {
        certainty
      }
    }
  }
}
```

For an object of any class:
```graphql
{
  Get{
    Publication(
      nearObject: {
        beacon: "weaviate://localhost/27b5213d-e152-4fea-bd63-2063d529024d"
      }
    ){
      name
      _additional {
        certainty
      }
    }
  }
}
```

**Comment by bobvanluijt** [comment]
Gotcha – and this would also be possible, right?

```graphql
{
  Get{
    Publication(
      nearObject: {
        beacon: "weaviate://localhost/27b5213d-e152-4fea-bd63-2063d529024d"
        certainty: 0.7
      }
      nearText: {
        concepts: ["fashion"],
        certainty: 0.7
      }
    ){
      name
      _additional {
        certainty
      }
    }
  }
}
```

**Comment by etiennedi** [comment]
> Gotcha – and this would also be possible, right?

I think term "near" implies that can only be used once. Maybe we could add "object" to "moveTo" inside `nearText`?

Side-Note: Then we also need to restrict that only classes can be referenced which actually use the same vectorizer module.

**Comment by laura-ham** [comment]
You mean something like this @etiennedi? If we go for this, we should also support moving to `vector` inside `nearText` and the other way around. Not sure if we want to go this direction?

```graphql 
{
  Get{
    Publication(
      nearText: {
        concepts: ["fashion"],
        certainty: 0.7,
        moveTo: {
            objects: [{
                beacon: "weaviate://localhost/27b5213d-e152-4fea-bd63-2063d529024d"
            }, {
                id: "27b5213d-e152-4fea-bd63-2063d529024f" 
            }],
            force: 0.9
        }
      }
    ){
      name
      _additional {
        certainty
      }
    }
  }
}
```

and the other way around:

```graphql
{
  Get{
    Publication(
      nearObject: {
        beacon: "weaviate://localhost/27b5213d-e152-4fea-bd63-2063d529024d"
        certainty: 0.7,
        moveTo: {
            concepts: ["fashion"],
            force: 0.9
        }
      }
    ){
      name
      _additional {
        certainty
      }
    }
  }
}
```

**Comment by etiennedi** [comment]
@laura-ham 

I like your first suggestion (`nearText.moveTo.objects[]`), but I think the second one (`nearObject.moveTo.concepts`) is problematic, because we then mix up a Weaviate Core "Near"-Searcher with module-specific content ("concepts" depend on the `text2vec-contextionary` module).

As in it's fine for a module-specific searcher to depend on logic that's always present, but not the other way round.

**Comment by laura-ham** [comment]
Yes that's a fair point. We could for example decide that 
* Weaviate Core supports `nearVector` as already implemented
* Weaviate Core supports the new`nearObject` as: (where `beacon` or `id` is required)

```graphql{
  Get{
    Publication(
      nearObject: {
        beacon: "weaviate://localhost/27b5213d-e152-4fea-bd63-2063d529024d", // alternatively `id` if on same network
        certainty: 0.7
      }
    ){
      name
      _additional {
        certainty
      }
    }
  }
}
```

* `nearText` as: (`moveTo` and moveAwayFrom` will be extended with `objects:[{<id|beacon>:""}]`)
```graphql
{
  Get{
    Publication(
      nearText: {
        concepts: ["fashion"],
        certainty: 0.7,
        moveTo: {
            objects: [{
                beacon: "weaviate://localhost/27b5213d-e152-4fea-bd63-2063d529024d"
            }, {
                id: "27b5213d-e152-4fea-bd63-2063d529024f" 
            }],
            force: 0.9
        }
      }
    ){
      name
      _additional {
        certainty
      }
    }
  }
}```

What do you think?

**Comment by etiennedi** [comment]
> What do you think?

Sorry, I never replied. I think that covers everything. In my opinion we can go with this.
