### ISSUE TITLE
IDEA: Add an "Agent" object besides "data" objects

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#1428]
It is a bit abstract, but the concept solves a recurring request we are getting from users and that is that they want to be able to see how users search through the vector space.

I was thinking of making this one step more abstract and allow to store the location of an _Agent_ in the vector space at a specific time and save the timestamp. This allows seeing how an _Agent_ has moved through the vector space over time.

Use cases could be:

- An agent is an e-commerce user and we want to know how searches went over time and what pattern they followed.
- An agent is a document that changes based on content and while it changes, it moves conceptually to the vector space.
- etc.

An _Agent_ allows us to track something in the vector space to see how it developed and maybe even predict a direction for the future.

PS:
Related to [this](https://github.com/semi-technologies/weaviate/issues/1427) issue, it might also function as the input for a query.

**Comment by etiennedi** [comment]
Why would this need to be a new object type. This could be easily solved by just adding a new class `Agent` that has properties `timestamp date` and a vector. I think this should already be fully possible?

**Comment by bobvanluijt** [comment]
Good point – I need some time to think about it but I'll get back to it asap

**Comment by bobvanluijt** [comment]
Maybe a new object type isn't needed. Let me describe the use case for more context: _we want to somehow understand how a data object moved through the vector space over time._ If that would be a data type or a (time-series?) property doesn't really matter tbh.

**Comment by etiennedi** [comment]
Maybe a history feature? By "moving" I assume you mean altering it through updates, correct? Then we could have a feature (possibly through a module) that on update adds the old content to some sort of a history class and we could use cross-references to point to the next/last item. 

E.g. as pseudo-yaml

```
Company: # the user created this class
  name: "Apple"
  vector: [1,2] 

CompanySnapshot # the module created this class
  name: "Apple Inc"
  vector: [1.5, 2]
  historyVersion: 17
  historyTime: dateTime
  historyCurrent: CREF to most recent snapshot (20)
  historyPervious: CREF to previous history iteration (17)
  historyNext: CREF to next item in history (18)
```
