### ISSUE TITLE
documentationHref for text2vec-contextionary is incorrect

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#1443]
```
{
documentationHref: "https://www.semi.technology/documentation/weaviate/current/features/adding-synonyms.html",
href: "/v1/modules/text2vec-contextionary/concepts/:concept",
name: "search contextionary for concepts (part of the text2vec-contextionary module)"
},
{
documentationHref: "https://www.semi.technology/documentation/weaviate/current/features/adding-synonyms.html",
href: "/v1/modules/text2vec-contextionary/extensions",
name: "extend contextionary with custom extensions (part of the text2vec-contextionary module)"
}
```

leads to the wrong URL

**Comment by bobvanluijt** [comment]
This should be a small thing, no?

**Comment by etiennedi** [comment]
Absolutely, I think this somehow got lost in the void :) 

cc @antas-marcin maybe something for in between two issues :)

**Comment by etiennedi** [comment]
reopen

**Comment by omarzain27** [comment]
is this the updated link?
https://weaviate.io/developers/weaviate/current/modules/text2vec-contextionary.html

@etiennedi  @bobvanluijt

**Comment by soma2000-lang** [comment]
@bobvanluijt is this issue still available for working

**Comment by bobvanluijt** [comment]
@soma2000-lang – I actually don't know 🙈 

@etiennedi – do you know?

**Comment by bobvanluijt** [comment]
Turns out that all the `documentationHref`'s are still pointing to `semi.technology` this should become `weaviate.io` and they should be validated

**Comment by bobvanluijt** [comment]
@soma2000-lang feel free to update (also see the additional issue above) and create a pull request :)

**Comment by etiennedi** [comment]
I just merged a PR that fixes that. I manually validated them and they worked. So that should be fixed in the next release.
