### ISSUE TITLE
Suggestion: GraphQL Get references

### ISSUE THREAD

**Issue by AK89GIT** [semi-technologies/weaviate#1492]
Hi,

While playing with GraphQL in Weaviate console with the demo-set, 
I have noticed you have to put manually the attributes like "title" and "summary" everytime
if you want to query for these data's.

Now my question is, is it possible to have/create a query to get all attributes with 1 keyword (example: "allAttributes")?
Because from my point of view, when using the Weaviate console this would mean less code.

**Comment by etiennedi** [comment]
Responding with a quick video. Let me know if that helped.


https://user-images.githubusercontent.com/8974479/109814492-e0653100-7c2e-11eb-9714-0930ec029f40.mov

**Comment by AK89GIT** [comment]
> Responding with a quick video. Let me know if that helped.
> autoexpand.mov

Awesome! thank you Etienne! 
Super easy and quick solution, that helped a lot!

**Comment by etiennedi** [comment]
Great to hear, I'm closing this issue then.
