### ISSUE TITLE
meta does not list transformers modules under 'modules'

### ISSUE THREAD

**Issue by StefanBogdan** [semi-technologies/weaviate#1508]
I have noticed that if I get the meta data from weaviate (v1.2.0) with a transformer module, it does not display it under the 'module'.
```python
>>> client.get_meta()
{'hostname': 'http://[::]:8080', 'modules': {}, 'version': '1.2.0'}
```
Weaviate with a transformer model has the same META as weaviate without any module.

I would suggest to have something different for _transformers_ , so we can know what kind of module we have without checking the docker-compose/helm-chart. 

My suggestions are the following:

1. 'modules' : ['text2vec-transformers']
2. 'modules' : 'text2vec-transformers'
3. 'modules' : {'text2vec-transformers': {} } 

As we discussed the 3rd option is the best since it preserves the same format as for `text2vec-contextionary`.

If anyone has another suggestion, please feel free to comment it in this issue.

**Comment by antas-marcin** [comment]
PR #1506 fixed that issue, we went with option 3
