### ISSUE TITLE
SUGGESTION: Retrieve the vector representation of the object in GraphQL

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#1531]
Like:

```graphql
{
  Get{
    Article(
      explore: ["monkeys"]
    ){
      _additional {
        vectors
      }
    }
  }
}
```

**Comment by etiennedi** [comment]
Fully agreed, I don't actually know why we have this in REST, but not in GraphQL. I think I even ran into this an a demo when I wanted to show the vector position and then realized we don't have that feature in GraphQL.
