### ISSUE TITLE
Getting Started docker-compose.yml uses version 1.0.3 but docs suggest it should be 1.2.1

### ISSUE THREAD

**Issue by bkoltai** [semi-technologies/weaviate#1534]
I am working through the [Quick Start](https://www.semi.technology/developers/weaviate/current/getting-started/quick-start.html) in your documentation site and have downloaded the `docker-compose.yml` file. 

When I run the `curl -s http://localhost:8080/v1/meta` command, I get ` "version": "1.0.3"` instead of what is expressed in the docs as expecting ` "version": "v1.2.1"`

**Comment by etiennedi** [comment]
Hi @bkoltai - thanks for noticing. We'll look into it and make sure everything will get updated.

@laura-ham @bobvanluijt, the linked Quick-Start guide uses the [docker-compose of the newspub repo](https://raw.githubusercontent.com/semi-technologies/DEMO-datasets/master/newspublications/docker-compose.yml) which indeed still uses version `1.0.3`. Is there any particular reason? Can we just update it to the latest?

**Comment by bobvanluijt** [comment]
This is fixed, the [page](https://www.semi.technology/developers/weaviate/current/getting-started/quick-start.html) is updated. Thanks for noticing @bkoltai 

Additional note: the dataset uses the [transformers module](https://www.semi.technology/developers/weaviate/current/modules/text2vec-transformers.html) if you run it on CPU, it works but it will not be that fast. The exact same dataset is also available as an online demo dataset. You can start exploring it [here](https://console.semi.technology/console/query#weaviate_uri=https://demo.dataset.playground.semi.technology&graphql_query=%7B%0D%0A++Get+%7B%0D%0A++++Article+%7B%0D%0A++++++title%0D%0A++++++url%0D%0A++++++wordCount%0D%0A++++%7D%0D%0A++%7D%0D%0A%7D).
