### ISSUE TITLE
Encoding a taxonomy using contextionary

### ISSUE THREAD

**Issue by ali1k** [semi-technologies/weaviate#1548]
Hi there,
I would like to create a semantic context for my data before vectorizing the actual data.
Lets say we have a taxonomy where we have a set of domain specific concepts together with links to their related conecpts. Could you advise me what the best way is to encode not only those concept but also relations between them using contextionary?

**Comment by bobvanluijt** [comment]
Hi @ali1k – that's a great question. One request though, you would do us a huge favor by asking it on StackOverflow so that other with the same question might more easily find the answer. If thats not possible, no worries and I’ll answer it here :)

**Comment by ali1k** [comment]
Hi @bobvanluijt  here you go https://stackoverflow.com/questions/67175671/how-to-encode-a-taxonomy-in-weaviate-contextionary 

Looking forward to your answer...

**Comment by bobvanluijt** [comment]
Thanks @ali1k 🙏  – I'll answer asap, will also add a more elaborate answer to a blog post. Closing it here to continue on SO.
