### ISSUE TITLE
property names are a bit strict

### ISSUE THREAD

**Issue by michellemay** [semi-technologies/weaviate#1562]
Seems that only [a-z]* names are supported.  I cannot add field names to a class with number or underscored in them.

`Create class! Unexpected status code: 422, with response body: {'error': [{'message': "'label_a' is not a valid property name"}]}`
`Create class! Unexpected status code: 422, with response body: {'error': [{'message': "'label1' is not a valid property name"}]}`

**Comment by etiennedi** [comment]
Thanks for raising, you are making some valid points about this being unnecessarily restrictive.

@bobvanluijt @laura-ham @antas-marcin  I think this is mostly a leftover from the pre-modular era where ever class and property name had to be contextionary valid and adhere to the contextionary's camelCase convention.

I think we could either
(1) move this contextionary-specific validation into the contextionary module, so it only applies to classes where the contextionary is the vectorizer used or
(2) drop it alltogether. In this case we'd still honor camelCasing and splitting rules, but we'd accept any input. If the contextionary can't understand it, it cannot be used in vectorization. For vectorization (if desired) we'd use the same splitting rules as on data, i.e. split on any non-alphanumeric character.

What do you think?

**Comment by bobvanluijt** [comment]
I would suggest no.2

1. Assume `vectorize[ClassName/PropertyName] = false` and accept all honoring camelCasing.
2. If a user sets `vectorize[ClassName/PropertyName] = true`, fall back to what c11y supports (and maybe have a clear error message explaining this too)

**Comment by etiennedi** [comment]
Re 1:
Why restrict to camelCasing? I don't see any issue with a user naming their property `field_one`, etc. Especially if that's a naming convention they already have in their existing systems, switching to camelCasing would be a lot of manual effort. 

The only thing we need to restrict (because of internal conflicts) would be starting with an underscore. Additionally, for dataTypes we use the casing to distunguish between a ref type and a primitive type, so we'd still need to enforce that classes start uppercased and properties start lowercased. Other than that, I'd say anything would be fine.

Re 2:
a. Do you mean only when vectorizing with the Contextioary or also when vectorizing with something else, e.g. transformer?
b. There is already validation in place in the contextionary if there are no only words it understands (with an extensive error message I believe). For transformers they don't seem to care, as long as there's something, they seem to be able to produce a vector.

**Comment by bobvanluijt** [comment]
1. 👍 and also supported by GraphQL
2. I mean it more high level, if somebody sets (or doesn't set it and it defaults to the following) `vectorize[ClassName/PropertyName] = false` it can except anything as long as it is inline with the bullet point mentioned above

**Comment by eostis** [comment]
(image: semitechnologies/weaviate:1.5.0-rc.0)

I have the name validation issue with my property names:
"'_id' is not a valid property name"

I added  "vectorizePropertyName:  false," as stated in documentation https://www.semi.technology/developers/weaviate/current/restful-api-references/schema.html#add-a-property

After carefully reading this thread, I'm not sure how to prevent property validation?

**Comment by bobvanluijt** [comment]
> @eostis I'm not sure how to prevent property name validation?

My remark ([bullet 2](https://github.com/semi-technologies/weaviate/issues/1562#issuecomment-829091956)) has an impact when the property name is used in the vectorization process. So. if it's not used to create a vector _and_ if it is accepted by GraphQL anything should be possible

**Comment by eostis** [comment]
It's just that usually (SQL, WordPress, Solr, Elasticsearch), property names are meaningless while property values are meaningful. Therefore the names can be pretty much anything (but whitespaces):
- _price
- weight_in_kg
- weight-in-kg

For Elastisearch and Solr, fields can be indexed/queried without an analyser (filters). Or with an analyser for NLP search (tonenizer, stemming ,...). Or both: a field is used as a filter and concatenated to a giant text field with analysers.

Let's use the field "_price" in Weaviate for instance: we could use it as a [float] (filter and aggregation), and as a Vector (semantic).

**Comment by etiennedi** [comment]
Remove stale - this is prioritzied.

**Comment by etiennedi** [comment]
Some good and some not so good news:

Good: We have just planned this issue and it is now under active development.
Not-so-good: We have found out that GraphQL is quite restrictive with regards to property names (`/[_A-Za-z][_0-9A-Za-z]*/`). This is still better than what we currently have, i.e. it will allow for using underscores, will allow numbers and will fix the issue about trailing upper-case characters. But it won't allow for many other special characters, such as dash (`-`) or language-specific characters like Umlauts, etc.

**Comment by bobvanluijt** [comment]
@laura-ham please let me know when this is in the docs. Some people are asking for it :)
