### ISSUE TITLE
startPosition and endPosition not always available in qna-module

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#1575]
Can be replicated [here](https://console.semi.technology/console/query#weaviate_uri=https://demo.dataset.playground.semi.technology&graphql_query=%7B%0A%20%20Get%20%7B%0A%20%20%20%20Article(%0A%20%20%20%20%20%20ask%3A%20%7B%0A%20%20%20%20%20%20%20%20question%3A%20%22Who%20is%20the%20king%20of%20The%20Netherlands%3F%22%0A%20%20%20%20%20%20%20%20properties%3A%20%5B%22summary%22%5D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20limit%3A%201%0A%20%20%20%20)%20%7B%0A%20%20%20%20%20%20_additional%20%7B%0A%09%09%09%09answer%20%7B%0A%20%20%20%20%20%20%20%20%20%20result%0A%20%20%20%20%20%20%20%20%20%20startPosition%0A%20%20%20%20%20%20%20%20%20%20endPosition%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D).

This query:

```graphql
{
  Get {
    Article(
      ask: {
        question: "Who is the king of The Netherlands?"
        properties: ["summary"]
      }
      limit: 1
    ) {
      _additional {
				answer {
          result
          startPosition
          endPosition
        }
      }
    }
  }
}
```

results in:

```json
{
  "data": {
    "Get": {
      "Article": [
        {
          "_additional": {
            "answer": {
              "endPosition": 0,
              "result": "king willem - alexander",
              "startPosition": 0
            }
          }
        }
      ]
    }
  }
}
```

**Comment by etiennedi** [comment]
This should be in the docs (it was definitely in the release notes): The start/endPosition and property are determined by string matching. If the qna model formats the output differently than it is in the original text, it can't match it. 

We could try to come up with a more elaborate highlighting algorithm, but decided to go for a minimal approach first to have the module available sooner.

**Comment by bobvanluijt** [comment]
It [is in](https://www.semi.technology/developers/weaviate/current/modules/qna-transformers.html#graphql-response) the docs... Maybe I should read them better 🤓
