### ISSUE TITLE
Allow classes which aren't indexed in the vector index

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1579]
For example if a class only consists of Cross-References.

**Comment by bobvanluijt** [comment]
An additional thought:

- If a class in the schema has a setting that will result in a non-vectorized data object. It might be good to mention this when a schema is added to Weaviate in the logs.

**Comment by etiennedi** [comment]
By "non-vectorized" do you mean "identically vectorized"? I.e. something where all props are ignored, but only the class-name is vectorized? 

Because at the moment, we don't allow not vectorizing anything.

**Comment by bobvanluijt** [comment]
No - I mean a setting where literally _nothing_ is there to base a vector on.

_however_

This prompts a new (2nd) idea:

1. If a class in the schema has a setting that will result in a non-vectorized data object (i.e., no information to base a vector on). It might be good to mention this when a schema is added to Weaviate in the logs.
2. If a schema has a setting that will result in many identical vectors (e.g., only vectorize a class name) it would be good to mention this in the logs as well (e.g., as an undesired pattern). Or, to build in a smart pattern like: "If there is no data to vectorize on in the schema, set `vectorizeClassName` to `False` and set `vectorizePropertyname` to `False`"

An example of the 2nd point would be:

```js
{
    "class": "Order",
    "description": "Order",
    "moduleConfig": {
        "text2vec-contextionary": {
            "vectorizeClassName": true
        }
    },
    "properties": [
        {
            "name": "ofItems",
            "dataType": [
                "Items"
            ],
            "description": "Items",
            "indexInverted": true,
            "moduleConfig": {
                "text2vec-contextionary": {
                    "skip": true, <== note
                    "vectorizePropertyName": true
                }
            }
        },
        {
            "name": "foobar",
            "dataType": [
                "string"
            ],
            "description": "a foobar example",
            "indexInverted": true,
            "moduleConfig": {
                "text2vec-contextionary": {
                    "skip": true, <== note
                    "vectorizePropertyName": true
                }
            }
        }
    ]
}
```

**Comment by bobvanluijt** [comment]
Related to the above, if a schema contains a setting where a vector always will be impossible to generate with a vectorizer (e.g., if there are 0 `text` and `string` fields) it might be good to skip the vectorization process too.

Note:<br>This is most probably module related. I.e., if a module vectorizes based on a `blob` type or an `int` type. It should inform Weaviate about this

**Comment by etiennedi** [comment]
1. We currently don't allow this at all. We could a) always allow it and log or b) only allow it if the users explicitly configures not to index the class (<- my preference). 
2. I think we need to decouple "not indexing anything" and "detecting potential duplicates", because the first also needs to work when no vectorizer module is present, but the latter is specific to various modules.

**Comment by bobvanluijt** [comment]
1. Agreed with your preference
2. True, maybe in another GH issue?

**Comment by bobvanluijt** [comment]
That's fast

**Comment by bobvanluijt** [comment]
🚀

**Comment by etiennedi** [comment]
@bobvanluijt Haha, thanks :) For now the only feature that's implemented is vector-noindexing a specific class. So far nothing has changed about validation or duplicate detection which I'll add follow-up issues for.

**Comment by etiennedi** [comment]
The follow-ups are #1581 and #1582

**Comment by bobvanluijt** [comment]
> The follow-ups are #1581 and #1582

thx
