### ISSUE TITLE
Dynamic properties in Weaviate

### ISSUE THREAD

**Issue by venuraja79** [semi-technologies/weaviate#1587]
Thanks for building Weaviate, this is an amazing platform. 

How do we allow creation of dynamic properties (key/value pairs) in weaviate that aren't defined in a schema? This is similar to the dynamic field mapping in elastic search. I looked into the issues a little bit and found #1539 in the roadmap. 

Is there a hackish way to achieve this in the current version of Weaviate? Thank you very much for your help.

**Comment by etiennedi** [comment]
I've answered the [question about a workaround on the public Slack](https://weaviate.slack.com/archives/C017EG2SL3H/p1622279396032300?thread_ts=1622268024.031800&cid=C017EG2SL3H) and #1539 is the issue to track the implementation, I'm thus closing this one :)
