### ISSUE TITLE
AllNotEqual operator to collect results that not contain a specific 

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#1628]
There might be use cases where a user might want to receive results _where a cross-reference does not contain a string_ or even _not contain an array of strings_ (maybe this is also possible for other data types?). An example is outlined in the example below where we want a result where "milk" is not one of the ingredients.

Besides the technical implications (@etiennedi, @antas-marcin) I would like to understand what the potential UX (@laura-ham) implications are.

To kick off the discussion, I would propose the following from an interface POV (described following Weaviate's [GraphQL design principles](https://www.semi.technology/developers/weaviate/current/architecture/interface.html#graphql-design-principles)):

```graphql
{
    Get {
        Recipe(
            where: {
                operator: AllNotEqual # <== a first suggestion
                path: ["hasIngredients", "Ingredient", "name"]
                valueString: "milk"
                valueStringArray: ["milk", "honey"] # <== if we want to _not collect_ multiple results
            }
        ) {
            name
            hasIngredients {
                ... on Ingredient {
                    name
                }
            }
        }
    }
}
```

**Comment by etiennedi** [comment]
## UX
I wouldn't introduce `valueStringArray` for two reasons:
1. The standard practice to apply multiple filters is chaining using `And`. This works just as well here, so the user can just use `AND ( foo AllNotEqual bar, foo AllNotEqual baz)` without API inconsitencies
2. We're about to introduce new array types in #1611 and it wouldn't be clear how the above `valueStringArray` relates to those fields vs to regular string fields.

Other than that, I think `All...` operators make sense for all or most operators we have, e.g. `AllGreaterThan`, `AllEqual`, etc. have the same use cases as `AllNotEqual` in my opinion. 

## Technical
Hard to say at this point, would require some deeper investigation. I'm sure it's possible somehow.
