### ISSUE TITLE
benchmarks for read and write to hnsw

### ISSUE THREAD

**Issue by patelprateek** [semi-technologies/weaviate#1631]
Curios if you guys have any benchmarks for the custom hnsw implementation and how do they compare to the original implementation  : https://github.com/nmslib/hnswlib 
Perhaps some result around updates , deletion will also be useful.

Also curios about how do we handle billion scale document index here , since hnsw is all in-memory , do you guys shard the corpus and query each shard separately with some merge at the end 

Thanks

**Comment by etiennedi** [comment]
Hi @patelprateek, thanks for your interest in Weaviate.

We don't (yet) have any benchmarks published, but are planning on adding them. You mention a comparsion to `hnswlib`. We were planning on providing e2e benchmarks that show Weaviate's write and read speed in the same way that users would be able to use them. I.e. they'd contain the whole ordeal including http request, storing objects, building up inverted index etc on write. And on read a request contain the overhead for the http request, retrieving the object itself from the object store etc besides the pure ANN search. Naturally, comparing the end2end flow of a database to an ANN library would be comparing apples to oranges. 

We could however also benchmark the pure HNSW implementation against `hnswlib` - but I'm dubious about how helpful this will be to actual Weaviate users - who will use the whole database and not parts of its implementation as a library. Especially on sub-1ms ANN search times, the overhead for the request, etc. is more than the actual search. It might still make sense though as a way to signal to our users that the implementation is correct with regards to recall, etc.

As for datasets that are too large to fit on a single machine: Yes, you can shard datasets and results are automatically merged. Note that this is currently under development, multi-shard indices [are almost complete](https://github.com/semi-technologies/weaviate/commits/sharding), the next step is then to distribute shards in a cluster. To get a better understanding of our (distributed) architecture I can highly recommend the [recording of our last architecture focused meetup](https://www.youtube.com/watch?v=6hdEJdHWXRE) where I explained how we shard, how shards are distributed, what distributed databases inspired Weaviate, etc.

PS: Feel free to [join our Slack](https://join.slack.com/t/weaviate/shared_invite/zt-goaoifjr-o8FuVz9b1HLzhlUfyfddhw) if you haven't yet - that's the perfect place for questions, etc.
