### ISSUE TITLE
Disk (or mmap) based HNSW commit log condensor

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1652]
## Background

The current condensor loads an uncondensed commit log into memory and then writes the condensed version back to disk. This creates two problems:

1. Either we have massive memory spikes that would become very costly in larger datasets or we need to cap the max size of what can be condensed to something reasonable
2. With the max size being capped, over time we won't be able to condense logs anymore and a) we need too much disk space and b) we vastly increase the startup times of large datasets potentially impacting MTTR, etc.

cc @cdpierse

## Suggestion / Idea

A disk based condensor that either holds nothing in memory or just very simple index structures, so that the actual payload is written straight to disk. This way memory spikes would be minimal and we could tackle basically any size, eliminating the problems mentioned above.

**Comment by etiennedi** [comment]
Unmark stale.

**Comment by etiennedi** [comment]
Keep

**Comment by etiennedi** [comment]
Reopen

**Comment by etiennedi** [comment]
Keep

**Comment by parkerduckworth** [comment]
Stale bot is really trying to get rid of this one 💨
