### ISSUE TITLE
Hebrew model AlephBERT for a WooCommerce search and filters

### ISSUE THREAD

**Issue by eostis** [semi-technologies/weaviate#1671]
I noticed the recent release of a new Hebrew model [AlephBERT](https://huggingface.co/onlplab/alephbert-base) at HuggingFace.

I wonder if  this model could be used with [Weaviate as a transformer module](https://www.semi.technology/developers/weaviate/current/modules/text2vec-transformers.html#option-2-use-any-publically-available-huggingface-model)?

There is no efficient open-source solution for a Hebrew NLP search according to my WooCommerce customers. This could be very exciting, as it would be a real breakthrough.

**Comment by etiennedi** [comment]
There is a good chance this is already working with the [instructions to run with any public Huggingface model here](https://www.semi.technology/developers/weaviate/current/modules/text2vec-transformers.html#option-2-use-any-publically-available-huggingface-model). If it doesn't - for whatever reason - feel free to create an issue and we can see if we can change something about the module to make it compatible.

That said, there is somewhat of a disclaimer: Not every BERT model is suitable for semantic search. For english for example, we typically use the [Sentence BERT](https://www.sbert.net/) over pure BERT models - as those are trained to specifically create embeddings which work well with Semantic Search.

**Comment by eostis** [comment]
Thanks.
