### ISSUE TITLE
Delete objects by query

### ISSUE THREAD

**Issue by eostis** [semi-technologies/weaviate#1683]
Hi,

Current API can index data in batch, but can only delete objects one at a time.

According to documentation, objects must be deleted one by one:
https://www.semi.technology/developers/weaviate/current/restful-api-references/objects.html#delete-a-data-object

It would be great to enable deletion of objects by query: one call could delete all objects in a class or a group of objects in the class.

Something like:
https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-delete-by-query.html

**Comment by etiennedi** [comment]
Just FYI, you can delete all objects by simply deleting the entire class and recreating it.

As for the the "delete by query" idea. I'm absolutely open to such a feature, but given our limited resources, this would require a community contribution.
