### ISSUE TITLE
Upgrade PyTorch from 1.8.0 to 1.8.1 to avoid crash

### ISSUE THREAD

**Issue by joshuaeckroth** [semi-technologies/weaviate#1685]
I cannot import any objects with GPU support. I see that the semitechnologies/transformers-inference container is running PyTorch 1.8.0, which has a fatal flaw: https://github.com/pytorch/pytorch/issues/53336

The fix is to upgrade to PyTorch 1.8.1.

See below for an example of the flaw, running in the container:

```
import torch

print(torch.__version__)
print(torch.cuda.get_device_name(0))
print(torch.version.cuda)

mat1 = torch.randn(2,3).to(0)
mat2 = torch.randn(3,3).to(0)

y = torch.mm(mat1, mat2)
print(y)
```

```
$ docker exec -it 33efda937214 bash
root@33efda937214:/app# python
Python 3.9.7 (default, Sep  3 2021, 02:13:51) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> 
>>> print(torch.__version__)
1.8.0
>>> print(torch.cuda.get_device_name(0))
NVIDIA GeForce RTX 2070
>>> print(torch.version.cuda)
10.2
>>> 
>>> mat1 = torch.randn(2,3).to(0)
>>> mat2 = torch.randn(3,3).to(0)
>>> 
>>> y = torch.mm(mat1, mat2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasCreate(handle)`
```

**Comment by etiennedi** [comment]
Thank you very much! We noticed the same issue - but only on some devices - e.g. T4s were problematic, but P4s were fine. I was not aware that a patch is available now. Will make sure we publish new containers very shortly! I'll keep this open until they're live.

**Comment by etiennedi** [comment]
The newer models were released and there has been some positive feedback on the public Slack.
