### ISSUE TITLE
Aggregation on several properties?

### ISSUE THREAD

**Issue by eostis** [semi-technologies/weaviate#1687]
Hi,

I could not find a way to aggregate results on several properties.

Documentation https://www.semi.technology/developers/weaviate/current/graphql-references/aggregate.html shows only single property aggregations examples.

Is it possible?

**Comment by etiennedi** [comment]
Hi, could you elaborate (maybe with an example) on how you define "aggregate results on several properties"? Do you mean just multiple properties independently aggregated in the same query or a single aggregation spanning multiple fields? (cc @laura-ham)

**Comment by eostis** [comment]
The first, to build multiple facets from results:
`multiple properties independently aggregated in the same query`

**Comment by etiennedi** [comment]
Yes, that is possible by simply putting the properties next to each other. In the link you posted, the various types are not just alternatives, they can also be used together. For example:

```
{
  Aggregate {
    MyClass {
      myFirstProp{
        count
      }
      mySecondProp{
        count
      }
    }
  }
}
```

This should be a valid query. Does this answer the question? If yes, any suggestion on how to make that clearer in the docs?

**Comment by eostis** [comment]
I forgot to mention I need the GroupedBy syntax to retrieve facet items:

Here it is with one property:
`{
  Get {
    Weaviate {
      type
    }
  }
  Aggregate {
    Weaviate(groupBy: ["type"]) {
      meta {
        count
      }
      groupedBy {
        value
      }
    }
  }
}`

**Comment by etiennedi** [comment]
If they are grouped by the same grouping parameters, you can add multiple in a single query. If you need to set different grouping settings, you need to send multiple queries.

**Comment by eostis** [comment]
> you can add multiple in a single query

Do you have an example?
I tried everything I could imagine.

**Comment by etiennedi** [comment]
Here's an example where the grouping is done by `wordCount` and the aggregation contains two properties (`inPublication` and `title`):

https://console.semi.technology/console/query#weaviate_uri=https://demo.dataset.playground.semi.technology&graphql_query=%7B%0A%20%20Aggregate%20%7B%0A%20%20%20%20Article(groupBy%3A%5B%22wordCount%22%5D)%20%7B%0A%20%20%20%20%20%20meta%20%7B%0A%20%20%20%20%20%20%20%20count%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20groupedBy%7B%0A%20%20%20%20%20%20%20%20path%0A%20%20%20%20%20%20%20%20value%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20inPublication%20%7B%0A%20%20%20%20%20%20%20%20pointingTo%0A%20%20%20%20%20%20%20%20type%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20title%7B%0A%20%20%20%20%20%20%20%20topOccurrences%7B%0A%20%20%20%20%20%20%20%20%20%20value%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D&prettify=1

**Comment by eostis** [comment]
Thanks, but what I need is to count each property.'s value

For instance, get counts for a product's colors and sizes:
- Color: 
  - red (2)
  - blue (5)
- Size:
  - Small:3
  - Large:3
  - XXL: 1

Ideally, this should be done with one query, as some of my WooCommerce clients can have tens of product's attributes to aggregate.

**Comment by eostis** [comment]
Found it: use aliases!

```
{
  Get {
    Weaviate {
      type
      title
      author
    }
  }
type: Aggregate {
    Weaviate(groupBy: ["type"]) {
      meta {
        count
      }
      groupedBy {
        value
      }
    }
  }
author: Aggregate {
    Weaviate(groupBy: ["author"]) {
      meta {
        count
      }
      groupedBy {
        value
      }
    }
  }
}
```

**Comment by etiennedi** [comment]
Oh, that's really cool. I wasn't aware myself. @laura-ham maybe this is also interesting for the docs or for a FAQ question?

**Comment by eostis** [comment]
And each alias can get its own parameters: for instance min, max for scalar properties to build a  price slider on the UI side.
