### ISSUE TITLE
Sort ?

### ISSUE THREAD

**Issue by eostis** [semi-technologies/weaviate#1715]
I could not find any documentation on sorting results.

For instance, sort by price desc, stock desc, or date desc.

**Comment by eostis** [comment]
@laura-ham

**Comment by etiennedi** [comment]
Just to clarify, you are missing the sort on pure "list" requests such as `GET /v1/objects` and `Get { ClassName { } }`, correct? Because that should be quite straight forward, whereas combing sorting with a `near<Media/Vector>` search would lead us to a conflict of having two sources of order.

**Comment by eostis** [comment]
I could not find the syntax to sort a Get query in the whole documentation: sort by any indexed property, or by relevance.

**Comment by etiennedi** [comment]
You are correct, it doesn't exist, but just want to verify that you are indeed looking for sort on on "non-vector-search" type queries?

**Comment by eostis** [comment]
What syntax would not be compatible with a sort on properties?

**Comment by etiennedi** [comment]
@eostis, I'll message you on Slack, so we can determine the minimal feature set needed to start adding value. The smaller the feature set, the more likely that we can implement this shortly.

**Comment by eostis** [comment]
@etiennedi, any hope on this one?

**Comment by etiennedi** [comment]
@eostis We are currently building the roadmap for the large features, such as sorting. This is definitely high up on the list. Expect more details in early February.

**Comment by eostis** [comment]
@etiennedi Great.
