### ISSUE TITLE
Cannot filter on existing values

### ISSUE THREAD

**Issue by eostis** [semi-technologies/weaviate#1718]
Is there a way to filter existing values?
(and therefore non existing values with operator 'Not')

This is very useful with dynamic data. For instance, data imported that sometimes contain a property, sometimes not.

We should be able to filter objects with something like `{path: ["property_name"], operator: Exists, value: '*'} `:
a) If the property is not defined in the schema, the 'Exists' operator should return no object (and not trigger any error of course)
b) If the property is not set on an object, the 'Exists' operator should not return this object

- For Apache Solr, we can use the filter: `property_name:*`
- For Elasticsearch, we can use the filter: `['exists' => [ 'field' => 'property_name'] ]`

For Weaviate, I tested in vain:
```
{
 path: ["property_name"]
 operator: Equal
 valueString: null 
}

```
```
{
  search: Get {
    WeaviateWooCommerce(limit: 1) {
      wpsolr_product_visibility_str
    }
  }
}

{
  "data": {
    "search": {
      "WeaviateWooCommerce": [
        {
          "wpsolr_product_visibility_str": null
        }
      ]
    }
  }
}
```

```
{
  search: Get {
    WeaviateWooCommerce(
      limit: 1
      where: {operator: And, operands: [{path: ["wpsolr_product_visibility_str"], operator: Equal, valueString: null}]}
    ) {
      wpsolr_product_visibility_str
    }
  }
}

{
  "errors": [
    {
      "locations": [
        {
          "column": 113,
          "line": 5
        }
      ],
      "message": "Syntax Error GraphQL request (5:113) Unexpected Name \"null\"\n\n4:       limit: 1\n5:       where: {operator: And, operands: [{path: [\"wpsolr_product_visibility_str\"], operator: Equal, valueString: null}]}\n                                                                                                                   ^\n6:     ) {\n",
      "path": null
    }
  ]
}
```

**Comment by etiennedi** [comment]
Agreed, I don't think this currently exists. What's missing is that we don't write a null/not set entry in the inverted index. The only place where we do that is for the count of references where we write an explicit `0` if there are no references on a class. 

⬆️ is not meant as a pro/contra to this feature request, just a tech explanation of what would need to be done.

**Comment by eostis** [comment]
Sorry to bombard you with all those new issues, but I'm discovering missing features while integrating Weaviate to WooCommerce.

If you can implement those features, Weaviate will be on equal terms with Elasticsearch/Solr/Algolia on a standard WooCommerce site (available to normal WooCommerce site owners, without a deep knowledge of coding or AI models or vector search).
