### ISSUE TITLE
Speed Bottlenecks when server and client aren't in the same location

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1731]
## Background

Since Weaviate supports Horizontal Scalability there is a lot of motivation to run Weaviate in an actual Kubernetes cluster as opposed to locally on Docker-Compose. This means that we typically introduce an internet connection between server and client.

Some initial (unstructured) tests have shown that imports are considerably slower than without an internet connection and the server is often idle a significant percentage of the time.

This issue is about investigating what causes the bottlenecks and trying out possible remedies.

## Ideas

1. ### Too much data being set on batch requests, make fields optional

   During a batch request we send a lot of data to the server. This is something we cannot avoid, because the data needs to get there. However, we return even more data on the response, most of which is probably not needed. We typically return the entire object including the vector. If a vectorization module was used, then this means the response data is much larger than the request. In this case, we could simply trim down the response of a batch request and show the minimal data by default (nothing if success, errors if not success). Then we could introduce additional flags to optionally include more data if the user really needs it.
1. ### Gzip requests
   Requests are entirely uncompressed at the moment. If we have idle resources on the server we could use those to compress the response and make it smaller. The downside of this is that the client will also have to spend some resources on zipping/unzipping the data. Most likely the effect of this is limited if we already tackle the steps mentioned in (1)
1. ### Parsing JSON responses is a bottleneck - Side effect or cause?
   A simple test I ran showed that if a batch size is really large, a significant amount of time is spent on parsing the JSON responses in the clients. This may be an edge case because it mostly shows on batch sizes of 10k and the like. However, in a simple case I could show that using the go client about 3s were spent on parsing json. With python being slower than Go the same time there was even higher. However, this point may just be a side effect of sending too much data (Point 1). Maybe this is no longer relevant if we have already reduced the amount of data

**Comment by DmitryKey** [comment]
For 3 -- could try to parse JSON as it streams? Something like https://github.com/yonik/noggit (for Java)

**Comment by etiennedi** [comment]
Keep open. There has been great progress on profiling the clients from the community.
