### ISSUE TITLE
Showing a vector of a reference returns null

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#1735]
E.g.,

```
{
  Get {
    Article(limit: 1) {
      title
      hasParagraphs {
        ... on Paragraph {
          order
          content
          _additional {
            vector
          }
        }
      }
    }
  }
}
```

returns

```
{
  "data": {
    "Get": {
      "Article": [
        {
          "hasParagraphs": [
            {
              "_additional": null,
              "content": "Asociación Alumni, usually just Alumni, is an Argentine rugby union club located in Tortuguitas, Greater Buenos Aires. The senior squad currently competes at Top 12, the first division of the Unión de Rugby de Buenos Aires league system. The club has ties with former football club Alumni because both were established by Buenos Aires English High School students.La historia de Alumni: un club que respira rugby y está unido a la primera leyenda del fútbol argentino by Walter Raiño on Clarín, 26 Nov 2018 ",
              "order": 0
            },
etc...
```

PS:
I've validated that the crefs actually have vectors ;-)

**Comment by danieldaeschle** [comment]
I have this problem too. Is it possible to fix this? I can't image that GraphQL ist the limitation.

**Comment by etiennedi** [comment]
> I have this problem too. Is it possible to fix this? I can't image that GraphQL ist the limitation.

This should absolutely be possible to fix. My statement above is a bit misleading, I didn't mean that GraphQL was the limitation. What I meant more was: We never added support for `_additional{}` properties in resolved references, but because the GraphQL type is the same type as the root type it contains `_additional{}` in the GraphQL schema even without us adding an implementation for it.

**Comment by etiennedi** [comment]
I've added a `good-first-issue` label, maybe someone wants to make their first contribution to Weaviate :-)

**Comment by danieldaeschle** [comment]
I would like to fix it but I has no starting point where the _additional things are implemented. 
Also I'm on a windows machine. I think it does not run on that, right?

**Comment by etiennedi** [comment]
Closing as this has been fixed.
