### ISSUE TITLE
docker-compose fails to init CUDA with stock configuration

### ISSUE THREAD

**Issue by alexcannan** [semi-technologies/weaviate#1736]
Trying to spin up the GPU-enabled docker-compose I generated from [the installation page](https://www.semi.technology/developers/weaviate/current/getting-started/installation.html#customize-your-weaviate-setup), I ran into this error when each image was trying to spin up:

```
qna-transformers_1  |   File "/usr/local/lib/python3.9/site-packages/torch/cuda/__init__.py", line 170, in _lazy_init
qna-transformers_1  |     torch._C._cuda_init()
qna-transformers_1  | RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
```

Upon further investigation I noticed that trying to execute `nvidia-smi` on each image directly returned a CUDA version of n/a, which would explain the failed init.

I was able to fix this issue by adding `utility` and `compute` alongside `gpu` to the device capabilities in each gpu-enabled image in the `docker-compose.yml`. I believe only `compute` would be required, but `utility` is supposed to enable `nvidia-smi`.

This fixed the issue and the gpu-enabled docker-compose launches perfectly now. Hopefully this is helpful if people, and maybe it would be useful to add to the generated docker-compose?

**Comment by robomotic** [comment]
Hi folks, I have also a docker-nvida setup I can certainly try it shortly.
