### ISSUE TITLE
Add more distances in addition to cosine

### ISSUE THREAD

**Issue by robomotic** [semi-technologies/weaviate#1745]
Hi folks,
would  love to see the following metrics supported:

- Minkowski distance with p1= Manhattan and p2=Euclidean
- Manhatthan distance
- Hamming distance

As a data-scientist I use them quite a lot in different tasks.

**Comment by etiennedi** [comment]
Keep open

**Comment by sky-2002** [comment]
@etiennedi , I am willing to work on the issue mentioned by @robomotic , as I am familiar with these distance metrics. Could you please guide me on where to start?

**Comment by etiennedi** [comment]
@sky-2002 Thank you, this sounds great. I will come back with some getting started guidelines later today.

**Comment by etiennedi** [comment]
@sky-2002, I've recorded the video below which should contain all you need to get started. Thanks for your willingness to contribute!

https://user-images.githubusercontent.com/8974479/158564608-ba2b2aac-da66-4f01-b59b-1c8e7bb4c94e.mp4

**Comment by sky-2002** [comment]
@etiennedi , Thanks a lot for the video, it was quite helpful 😇.

**Comment by etiennedi** [comment]
Great to hear. This discussion (about exposing distances in the APIs) may be of interest to you too: https://github.com/semi-technologies/weaviate/issues/1863

**Comment by sky-2002** [comment]
@etiennedi , Hello ! I have written codes for manhattan, minowski, and hamming distances. Initially I want to begin with adding the manhattan distance metric and so I have added two files - manhattan_dist.go and manhattan_dist_test.go in this folder  -weaviate\adapters\repos\db\vector\hnsw\distancer. I am a little bit confused what to do next. 
I have the following queries :
1. Could you please explain what more changes do I need to make (in shard.go file and other files) ??. Apologies for asking this silly question even after seeing the video. As I am new to Go, it is taking time for me to understand the structure of the code. But I am finding it interesting to work on and use weaviate.
2. Could you also tell what can I do if I do not want to use reusable distancer ??
3. Also I have not understood the concept of reusable distancer, could you please explain why we need one and what problem it solves ??
4. What changes do I need to make in index.go file ?

Below is the manhattan_dist.go file :
```Go
package distancer

import (
	"fmt"
	"math"
)

// implementation for manhattan distance (this function has been tested independently on many vectors and works fine)
func manhattanDist(a, b []float32) (float32,error){
	if len(a) != len(b){
		return 0, fmt.Errorf("vectors have different dimensions")
	}
	var manhat float64 = 0
	//var length = len(a)
	for i := range a{
		manhat+= (math.Abs(float64(a[i]-b[i])))
	}
	return float32(manhat), nil
}

type ManhattanProvider struct{}

func (p ManhattanProvider) New(vec []float32) Distancer {
	return newReusableDistancer(vec)
        // I do not want to use reusable distancer, What else can I add here ??
}

func (p ManhattanProvider) SingleDist(vec1, vec2 []float32) (float32, bool, error) {
	res, err := manhattanDist(vec1, vec2)
	return res, err == nil, err
}

func (p ManhattanProvider) Type() string {
	return "manhattan"
}

func NewManhattanProvider() Provider {
	return ManhattanProvider{}
}
```

Similarly, I have written codes for hamming and minowski distances too. Once I understand what more changes to make, I will do the needful and open a PR.
I am having fun with weaviate and trying my best to understand and contribute to weaviate !!
And I look forward to implement all these distance metrics successfully !!

**Comment by murphp15** [comment]
Hey Guys, 
How long do you reckon it is till this feature is ready, this is something we really want?
