### ISSUE TITLE
Add Jaccard metric

### ISSUE THREAD

**Issue by robomotic** [semi-technologies/weaviate#1746]
Hi folks,
would like to see also Jaccard metric implemented as:

- Jaccard = J(A,B)
- Jaccard similarity = 1 - J(A,B)
- Dice coefficient

There is a very interesting [paper here](https://core.ac.uk/download/pdf/86430721.pdf) which shows you an actually combine cosine and Jaccard to improve clustering.
Besides that, Jaccad itself is very useful in certain problems.
Cheers.

**Comment by bobvanluijt** [comment]
Thank @robomotic – there is also a discussion about [clustering on our Slack](https://weaviate.slack.com/archives/C02S5NNRQHH/p1640870190016500?thread_ts=1640806814.013900&cid=C02S5NNRQHH)

@etiennedi – maybe good to create a single issue for this?
