### ISSUE TITLE
Make nearText available on aggregates

### ISSUE THREAD

**Issue by eostis** [semi-technologies/weaviate#1764]
It looks like aggregates do not support the “nearText” filter. Is it definitely not possible?

![image](https://user-images.githubusercontent.com/1785759/145463638-96ddfc66-cb36-4c6f-a7d5-3ab662a8e020.png)

**Comment by etiennedi** [comment]
Hi @eostis, I think this is a duplicate of #1739, can you confirm?

**Comment by eostis** [comment]
@etiennedi Indeed. I close this issue.
