### ISSUE TITLE
More relevant results are ranked with low certainty scores in nearText module unlike cosine scores

### ISSUE THREAD

**Issue by Harika-3196** [semi-technologies/weaviate#1776]
The nearText module gives less score for exact match.The order of results are not exactly same as cosine score.Is this due to sharding ? Is there a way to give more preference to exact match.

I used sentence-transformers/paraphrase-MiniLM-L12-v2 in custom weaviate install 

**weaviate query :**
{
  Get {
    Idea(group: {type: closest, force: 0.1}, nearText: {concepts: ["free same day delivery"]}) {
      idea_text
    }
  }
}

###**Example 1:**
**query term : 2 day delivery**

1. Few delivery and 2 day delivery. | 0.894269
2. Free two day delivery. | 0.888840
3. Two day delivery | 0.885815
4. Two day delivery | 0.885815
5. Two day delivery | 0.885815
6. Free 2 day delivery | 0.876131
7. Free 2 day delivery | 0.876131
8. Free 2 day delivery | 0.876131
9. Free 2 day delivery | 0.876131
10. Free 2 day delivery | 0.876131
11. free two-day delivery | 0.875738
12. 1-2 day delivery | 0.874515
13. 2 Day delivery | 0.868268
**14. 2 day delivery | 0.868268**
15. 2 DAY DELIVERY | 0.868268

Exact match is available is 14 th row but got less score.Is there a way to get exact same results first with high score followed by similar results

###**Example 2:**
**query term free same day delivery**

1. Same day free delivery | 0.936383
2. Free same day delivery | 0.931357
**3. free same day delivery | 0.931357**
4. Free same day delivery | 0.931357
5. Free same day delivery | 0.931357

Exact same match is available in db multiple times but not getting highest score

But this is not the case with same embeddings and cosine scores in python setup.If there is exact match we get score of 0.9999

**Comment by Gbellard** [comment]
Did you find a way to get exact match ranking higher ?
