### ISSUE TITLE
Date Range Filter

### ISSUE THREAD

**Issue by leejwsh** [semi-technologies/weaviate#1792]
Querying with a small date range filter returns results that are outside of the specified range.

An example query:

```graphql
{
  Get {
    Article (
      where: {
        operator: And
        operands: [{
          path: ["publicationDate"]
          operator: GreaterThanEqual
          valueDate: "2021-04-11T00:00:00Z"
        }, {
          path: ["publicationDate"]
          operator: LessThanEqual
          valueDate: "2021-04-11T00:01:00Z"
        }]
      }
    ) {
      publicationDate
    }
  }
}
```

This returns the result:

```json
{
  "data": {
    "Get": {
      "Article": [
        {
          "publicationDate": "2021-04-12T00:00:00Z"
        },
        ...
        {
          "publicationDate": "2021-04-21T00:00:00Z"
        },
      ]
    }
  }
}
```

**Comment by etiennedi** [comment]
Hi @leejwsh and thank you for reporting this. Can you specify which version you used in the above snippet? The reason I'm asking is that we just fixed a very similar-looking bug in `v1.9.1`, so before diving deeper into the investigation of this, I'd rule to see if it is maybe already fixed :-)

**Comment by leejwsh** [comment]
I ran this on the demo dataset at https://demo.dataset.playground.semi.technology using the [Weaviate Console](https://console.semi.technology/).

**Comment by etiennedi** [comment]
That is good news, I'll keep this issue open until we have updated the demo dataset to `v1.9.1`. Ideally, the bug will go away through that. If not, we can research further.
