### ISSUE TITLE
Weaviate console CORS error

### ISSUE THREAD

**Issue by eostis** [semi-technologies/weaviate#1795]
I got those error this morning. I cannot connect to a local, demo, or WCS instance anymore.

![image](https://user-images.githubusercontent.com/1785759/150538723-fc1a5f55-d582-4f85-8936-ac52d2f9d174.png)

**Comment by eostis** [comment]
@etiennedi  Any idea?

**Comment by IgorWang** [comment]
same issues
<img width="1431" alt="image" src="https://github.com/weaviate/weaviate/assets/10041387/f6a171c3-0260-4b0c-a355-280589e6bfbe">
