### ISSUE TITLE
(DOC) Clarify Vectorizer vs Reader modules in documentation

### ISSUE THREAD

**Issue by eostis** [semi-technologies/weaviate#1796]
I found hard to understand the concept of module in Weaviate's documentation.

It seems a module encapsulates 2 concepts: Vectorizer (indexer) and Inference (reader)

- Vectorizers: 
 text2vec-transformers, text2vec-contextionary, img2vec-neural, multi2vec-clip
- Readers: 
qna-transformers, ner-transformers, text-spellcheck

All Vectorizers are also readers. 

- Vectorizers that can be used  with other readers:
text2vec-transformers, text2vec-contextionary
- Vectorizers that cannot be used  with other readers:
 img2vec-neural, multi2vec-clip

**Comment by etiennedi** [comment]
Great point, we don't differentiate a lot in the docs between the different styles of modules. This is definitely something, we should add. 

> Vectorizers that cannot be used with other readers:
> img2vec-neural, multi2vec-clip

This part would probably have to be more fine-grained and/or we need to fix whatever limitations there are which shouldn't be there. I think the limitation is less on how they can be combined and more what the other modules, the ones you called "readers" require. One a one-by-one basis, I think this would be:

- **`qna-transformers`**: This model depends on a `nearText` functionality, so it needs any module that provides `nearText`. This would currently be `text2vec-transformers` and `text2vec-contextionary`. But I think also `multi2vec-clip` does so, so if that's a combination that's not currently possible, this should be something that we can fix.
- **`text-spellcheck`**: Same as above. It only really needs a `nearText` field. Where that comes from shouldn't matter.
- **`ner-transformers`**: This should have no dependencies and should therefore be able to be combined with any module, including an image-based module. The only real requirement is that there is at least one text field that the `ner` extraction can run on.

**Comment by eostis** [comment]
In WPSOLR, you must first set the vectorizer on any index (class). Then, depending on the vectorizer, you can perform some queries on the index

![image](https://user-images.githubusercontent.com/1785759/150675416-19929406-07d8-4a24-9673-57a65132feb5.png)
