### ISSUE TITLE
BM25

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1798]
This issue is a WIP!

## Background

This issue is not about any user-facing features of BM25. The general idea is that we want to develop user-facing features that make use of BM25 and therefore being able to perform BM25 searches becomes a requirement. This issue is about creating this functionality.

## Overview

Looking at the Lucene implementation we can see that to calculate the score we need to following values:
```
“tf, computed as freq / (freq + k1 * (1 — b + b * dl / avgdl)) from:”
“idf, computed as log(1 + (N — n + 0.5) / (n + 0.5)) from:”
```

Looking at the individual parameters they are defined as follows:

| param | Explanation | Source |
|---|---|---|
| `freq` | Frequency of term in each doc | ✅ analysis at import time, contained in inverted index result array element |
| `k1` | Static parameter to control | :x: default value from schema |
| `b` | Static parameter to control | :x: default value from schema |
| `dl` | Document / field length | :x: |
| `avgdl` | Mean document length | :x: |
| `N` | Number of total docs in the index | :x: |
| `n` | Number of matching docs for a particular term | ✅ len of inverted index result array | 

Anything marked with a :x: is something that's not currently present in Weaviate and needs to be added, see below.

### Static parameters `k1` and `b`
The assumption is that they rarely change. ~During development, they could be fixed in the code and eventually made part of the schema so that users can tweak them if they desire.~ Update: See @byronvoorbach's comment below, they should be configurable from the get go.

### Total doc count (#1811)
Currently, there is no good way to efficiently get the total number of documents. This has been a pain point in `{ Aggregate { meta { count } } }` for some time already. The challenge is that in an LSM-tree based index taking a simple count of the keys present does not yield the correct results. A future segment could have an id indexed only to attach a tombstone to an entry from a previous segment. This challenge needs to be overcome. In addition - due to this parameter being required in every read query, the value can be cached as long as indices haven't changed. This would be part of the LSMKV package.

## Implementation

* [x] obtain count from LSM bucket (#1811)
* [x] implement simple BM25 operator limited to single word no filters
  * In the first step fake `dl` and `averageDl` - to be added later
  * add to API
  * retrieve, then score
  * require explicit field for now, add BM25F support later
  * express limitations through validation
* [x] combine multiple words
  * TODO: decide on how to combine? addition? product? etc?
* [ ] combine bm25 with existing (binary) filters
  * narrow down the result set through filters
  * then intersect with bm25
  * only score after intersecting
* [ ] extend cross-cluster communication to support new type of search
* [x] get document length
  * consider storing it alongside frequency in inverted index with fallback for existing indices
* [x] get avg document length
  * ~consider using sampling that runs periodically~ Implementation now uses a bucketing approach that runs as part of the inverted index analysis and commits to disk just once per batch
* [ ] make `b1` and `k` configurable
* [ ] prevent running with index that was built prior
* [ ] improve speed at large scale. (No need for massive optimizations yet, but the most obvious ones should be tackled)
* [ ] introduce configurable stopword list

**Comment by byronvoorbach** [comment]
Hi @etiennedi!

Really looking forward to this implementation!

I would like to comment on the `k1` vs `b` discussion. Having developed quite some solutions for the e-commerce space, in my experience we play around with these parameters to tune for specific needs. Sometimes you don't want to take (avg) field length in to account, which is only possible by turning with these values. I understand that it might not be the highest priority while developing this feature, but Weaviate supporting a pluggable similarity model would be great down the road.

I'm open for contributing/helping/testing!! 😄

**Comment by etiennedi** [comment]
@byronvoorbach, this is amazing feedback. Thank you. I read a few articles on BM25 and one article mentioned something along the lines of "these rarely require adjusting in real life" which I trusted blindly. Knowing that there is actual value in adjusting those, we will absolutely make them configurable. It's not much effort to expose them as part of the config and if you have use cases for it, I'm all for it!

**Comment by bobvanluijt** [comment]
> I'm open for contributing/helping/testing!! 😄

Thanks @byronvoorbach!

**Comment by pommedeterresautee** [comment]
Just for the documentation (about configurable hyper params):
- https://www.elastic.co/fr/blog/practical-bm25-part-3-considerations-for-picking-b-and-k1-in-elasticsearch
- https://github.com/castorini/anserini/blob/master/docs/experiments-msmarco-doc.md#bm25-tuning

(not) Tweaking k/b params has been a hot topic few years ago when first DL algo was compared to BM25 (default param don't work well on MsMarco for instance, MsMarco being the defacto standard reranking dataset nowaday).
As you can see in the 2nd link `As expected, BM25 tuning makes a big difference!` :-)

**Comment by etiennedi** [comment]
@pommedeterresautee Great input and resources. Thanks for sharing.

**Comment by pommedeterresautee** [comment]
You're welcome!

2 things which comes in mind regarding this issue:

* in multi fields docs (in particular titles + content), how will it work? In search, in this case, BM25F is the standard and is known to work very well. It has recently been added to ES (https://opensourceconnections.com/blog/2021/06/30/better-term-centric-scoring-in-elasticsearch-with-bm25f-and-the-combined_fields-query/ for more info). If not BM25F, 2 options remaining: flatten all texts in a single field (may be okish), or compute 1 score per field but then you need to provide some way to merge signals (aka the API is complex like ES/SolR, which I don't think is a good idea as Weaviate is more vector oriented). The good thing about BM25F is that it's a good default for most cases and may keep the API simple. 
* you may want to provide a multi lingual stemmer somewhere, or plural of common words will get super high scores, etc. If not provided by Weaviate, then the user should be able to provide 2 flows of texts, a stemmed one and one to store as a meta to retrieve (may increase memory footprint, etc.). If you decide to provide a stemmer, porter is very well known and of low quality outside english. Unine is less well known and provide good results. Both are provided in Lucene (Unine is the light stemmer option of several languages).

**Comment by byronvoorbach** [comment]
I agree with @pommedeterresautee on the stemmer part. I've had good results with hunspell, but that requires a dictionary per language.. Might be a bit too much to include for a first round. Could argue the same for stopwords actually as well now that I think about it. Default Lucene stopword lists are sometimes a bit too broad setup for different use cases. 
Having a multi-field type setup (like we would always use in ES) has a preference, but not sure what the impact would be for implementing such a feature into Weaviate. Being able to combine scores for these fields (dismax / bool) would be a requirement then as well.

**Comment by etiennedi** [comment]
Thanks, both. This discussion is such a great example of great help from the open-source community. Very happy to be able to build on your experience around these topics.

Before diving into the two specific topics, let me preface this by saying that the goal right now is to keep it simple without obstructing future extension potential. Generally, Weaviate is a vector-first search engine and the goal is to use BM25 (and potentially other ranking metrics in the future) to aid vector search. This may also mean that the BM25 implementation itself may not be as powerful as those in keyword/BM25-centric search engines, but can still provide a lot of value as its main purpose is to overcome the limitations of pure vector search. 

Now to the individual topics:

- **Multi-Field Documents**
  Currently, we use the inverted index to fuel the filters in Weaviate which treat fields independently. I.e. the term frequencies, etc. are also calculated on a per-field basis. We do not (yet) capture avg document length, etc., but my intuition would say it makes the most sense to also keep doing this on a per-field basis. I have not looked into BM25F in detail yet, but from my understanding, it's a simple weighing of the individual fields. This also seems quite intuitive to me. We could pick best practice defaults and expose this through configuration. So that if a user really needs to change the ratio e.g. between title and body, they can. Flattening all into a single field is definitely also an option. The downside here would be that we would have a lot of duplication in the inverted index, as we'd have each field individually for the filters and then have another field itself containing all fields for BM25. This makes me prefer individual fields and an aggregation a la BM25F with the simplest possible API.
  
- **Stemming**
  I was originally thinking of stemmers being a "future improvement" to keep this is as small as possible and be able to move as quickly as possible. But you do raise a great point about giving way too much score to plurals of frequent words. Under the above considerations of BM25 in Weaviate being more of an aid to vector search, we might go the route of ignoring this for now and adding a stemmer later if we see this being a problem. If we come to the conclusion that we will add a stemmer, I'll definitely check out all three suggestions from above. *tl;dr: I don't know how big of a problem this really is for our use cases and would prefer to run into this issue before trying to fix it.*
  
- **Stopwords**
  Stopwords introduce another problem other than search result quality: Being super common they tend to blow up the inverted index. This has both an impact on disk footprint as well as memory and CPU time when a query contains stopwords. So, at least eliminating the most common ones for each language should add a lot of value. In my head, I'm thinking of a very simple API where you could select a default (e.g. `en`), but could also add and remove individual stopwords to customize it. If the default is `none`, you can just add whatever you like to create your own stopword list. Since the defaults will be very simple data structures, it should be quite easy to contribute more lists for speakers of not-yet-supported languages. 
  
Again, thanks for all the help in designing this feature and setting the correct priorities!

**Comment by eostis** [comment]
Do we need BM25?
I thought using nearText with a transformer model brings all the Lucene analysers like stemming and stopwords.
After all, those analysers (or others like OpenNLP) were built to bring some semantic to Lucene before the edge of transformers and vector search..

**Comment by etiennedi** [comment]
> I thought using nearText with a transformer model brings all the Lucene analysers like stemming and stopwords.

There are cases where out-of-domain searches with transformers models simply don't perform as well as BM25. Or other scenarios where a semantic search might be aided by keyword matching. For example, think of matching a webshop search query that needs to match a specific brand, but the transformer model does not understand the brand name. By taking the best of both worlds we can achieve better search results than either method on its own could do.

> After all, those analysers (or others like OpenNLP) were built to bring some semantic to Lucene before the edge of transformers and vector search.

Some of them, yes. But as @pommedeterresautee pointed out, without stemming, for example, we consider some words to be rarer than they are, giving them too much weight, resulting in a worse score.

As outlined above: The main goal of BM25 in Weaviate is to overcome the limitations of semantic search, not replace it. I see BM25 basically as "keyword matching with a score" (as opposed to binary keyword-based filtering). How that score gets combined with semantic search scores is a completely different topic and may indeed not be needed in some cases, but very much so in others.

**Comment by pommedeterresautee** [comment]
In the use case we have in our company for Weaviate (document search), a basic support of lexical search (BM25) would be enough for us to drop ElasticSearch and build only around Weaviate as our single source of candidates to rerank. I am under the impression that our use case is quite common for vector db users.

Regarding stop list, the right list is ALWAYS custom whatever the use case (even if it starts with a standard one), so just having a simple way to provide one is definitely a good solution.

Regarding the stemmer, without it, search results may be very wrong and hide the advantage of having lexical search. I have understood that on Vespa which has several internet scale users, it's common to just import some content pre tokenized / stemmed ready to be indexed (you can also build your own Java module to prepare content). Doing similar thing on Weaviate would free you from maintaining that part but it will make the feature less accessible to new users (which can have decent results from dense embeddings only indexation in any case).

**Comment by eostis** [comment]
I think we should decouple the topics of BM25 (ranking) from analysers (data prep).

OpenNLP provides ML analysers (used by ES, Solr, and Vespa). Could it be integrated as a module/step in Weaviate?

**Comment by etiennedi** [comment]
@pommedeterresautee 
> Regarding stop list, the right list is ALWAYS custom whatever the use case (even if it starts with a standard one), so just having a simple way to provide one is definitely a good solution.

Great point, the goal here should be the ease of use to set it. Could also mean file-based at runtime, etc. Want to keep the "how" open for now, but the goal should be ease-of-use and flexibility.

@pommedeterresautee 
> Doing similar thing on Weaviate would free you from maintaining that part but it will make the feature less accessible to new users

@eostis 
> Could it be integrated as a module/step in Weaviate?

I really like the idea of handling this in a module. So that by default there would be no stemming or a very minimal stemming, but any kind of pre-processing could be replaced by either a more complex or a completely custom module.

@pommedeterresautee 
> And regarding the mixing of scores, IMO it's definitely outside the scope of the vector DB. There are simple ways of doing it (like weighting each score) and there are tons of more complex fusion strategies (you can check papers in DL search from 2017-2019 for some inspiration).

Our goal is to both serve power users like yourself who want and appreciate full control over distinct search types. As well as provide an easy way to get started for beginners. This could mean that you could do two searches (bm25, vector) and combine the results in any way you like in your application logic. But, additionally, a simple "hybrid" mode could use simple mechanisms (like weighting each score) to optionally combine this inside the DB already - for those who don't have or don't want to have an elaborate application logic on top.

**Comment by pommedeterresautee** [comment]
about fusing lists from 2 systems -> https://twitter.com/jobergum/status/1488778519110946817?s=20&t=xl09YQ88wTeG1X0YjoEC7Q
Paper:
https://arxiv.org/pdf/2010.00200.pdf
