### ISSUE TITLE
make file for build

### ISSUE THREAD

**Issue by gedw99** [semi-technologies/weaviate#1815]
I cant work out how to gen and build.

Is there a makefile ?

**Comment by etiennedi** [comment]
For a local build env, see [Development environment](https://www.semi.technology/developers/contributor-guide/v1.9.0/weaviate-core/setup.html).

To see how a production build is built, take a look at the [Dockerfile](https://github.com/semi-technologies/weaviate/blob/master/Dockerfile).

Hope this answers your questions. If not, feel free to reopen.

**Comment by chris-aeviator** [comment]
@etiennedi I cannot find the local-development docs anymore (404), could you please point to an updated version?

**Comment by joeblew99** [comment]
I also have trouble understanding how to built this.

**Comment by etiennedi** [comment]
Thanks for letting us know. I'll make sure we fix the broken link and then also add some helpful instructions to the README.
