### ISSUE TITLE
Open AI module: provide API key at query time

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1816]
## Background

Right now the key must be set globally as an env var. This is fine when self-hosting, but does not work for SaaS-style services like the WCS.

## Goals

- [x] The module can startup without a key being set
- [x] If no key is set in the env config, it must be provided at each request that makes a request to OpenAI (i.e. import/vectorize, vectorize at query time)
- [x] If a key is set in the env, no extra key must be provided
- [x] If the key is provided neither globally nor at query time the request fails with a descriptive error message

## Notes

See [this commit](https://github.com/semi-technologies/weaviate/commit/90bc8c205e9d3dd42333de79f7c5ba07da2780b1) which adds the ability to inject arbitrary http headers into the context so that the module can read them. Using this we could intorduce something like `X-OPENAI-API-KEY`.

Note that Go changes the capitalizatoin in headers, in my test it looked like each new word is capitalized regardless of the previous input, so the header above would be stored as `X-Openai-Api-Key` in the `context.Context`.

**Comment by dandv** [comment]
Is there a way to provide the Open AI API key in the WCS?

**Comment by awhillas** [comment]
how _do_ you get to the GraphiQL console? Whats the URL?
