### ISSUE TITLE
Loading Weaviate Vectors (Manually Inserted Vectors of 256 dim) into GPU and doing dot product based top-k retrival

### ISSUE THREAD

**Issue by astar10239** [semi-technologies/weaviate#1820]
How can i load all my 256 dimension custom vectors to GPU for search (just like faiss-gpu) and get a dot product similarity instead of cosine

Update [I tried this but same]:

  weaviate:
    image: name-of-your-weaviate-image
    ports:
      - 8080:8080
    environment:
       ENABLE_CUDA: 1

**Comment by etiennedi** [comment]
Hi @astar10239 

Weaviate does not currently support GPU-based search. The similarity comparisons run on CPUs. GPUs are only supported for model inference (at either import or query time). 

Please see this [tutorial on how to import your custom vectors](https://www.semi.technology/developers/weaviate/current/tutorials/how-to-use-weaviate-without-modules.html).

For questions you can also refer to StackOverflow (tagged with `weaviate`) or join our Slack channel.

Hope this helps.
