### ISSUE TITLE
semantic search score

### ISSUE THREAD

**Issue by tesla-cat** [semi-technologies/weaviate#1825]
- when i search, many irrelevant results shows up. How to define a score requirement to filter the result? for example, match if score > 0.8, also the results should contain the score:  response: 
```js
[  {doc: 'a', score: 0.88}, {doc: 'b', score: 0.83}, ...]
```

**Comment by byronvoorbach** [comment]
https://weaviate.io/developers/weaviate/current/tutorials/how-to-perform-a-semantic-search.html#neartext-filter

Have you seen the 'certainty' parameter? Does exactly what you want!
