### ISSUE TITLE
"description" is required for reference properties

### ISSUE THREAD

**Issue by ju-bezdek** [semi-technologies/weaviate#1826]
"description" is required for reference properties, and I think it shouldn't be

If there is a valid reason, it should be it in documentation.

If not, it seems to be a quick fix:
_create_complex_properties_from_class
weaviate/schema/crud_schema.py
![image](https://user-images.githubusercontent.com/27913091/155199286-64a387e3-4fc6-4678-8c9d-a151e2710d41.png)

Another weird behaviour that I encountered is automatic property name casing conversion...
I create property "MyProperty" >> but created is "myProperty" ... later i get error when trying to create document, stating that "myProperty" already exists.
It should be at least better explained in documentation, but I would rather add some validation

**Comment by StefanBogdan** [comment]
Hi @ju-bezdek , this is a python-client related Issue and it was already fixed in the `weaviate-client>=3.4.0` (currently the latest is `3.5.0`).

**Comment by ju-bezdek** [comment]
Great:)
This issue was filed at the time when 3.3 was the latest :)
