### ISSUE TITLE
Add text2text (generation) transformer module

### ISSUE THREAD

**Issue by vblagoje** [semi-technologies/weaviate#1831]
After reviewing available Weaviate modules geared towards integration with HuggingFace, I think it would be great to add a text2text transformer module to Weaviate. 

Although developers could interact with Weaviate via Python client and perform the same functionality, a single text2text module could potentially cover a variety of NLP tasks. The tasks range from summarization, translation, long-form question answering, to any other text2text transformation involving data stored in Weaviate and transformed via text2text module to its task's goal. 

I propose a careful review of HF [pipelines](https://huggingface.co/docs/transformers/main_classes/pipelines) and then devise a plan on how to cover some of these important tasks with a single Weaviate module.

**Comment by laura-ham** [comment]
Thanks @vblagoje!

@etiennedi @antas-marcin would it be feasible to make one Weaviate module that supports more HF pipelines? Otherwise, let's make separate issues per module that we want to make (e.g. QnA generation, Summerization, etc)
