### ISSUE TITLE
Unable to run Quickstart 

### ISSUE THREAD

**Issue by argonaut76** [semi-technologies/weaviate#1846]
The instructions on the Quickstart page are not working. Steps to reproduce:

1. Download the recommended docker compose file:
`curl -o docker-compose.yml https://raw.githubusercontent.com/semi-technologies/weaviate-examples/main/weaviate-transformers-newspublications/docker-compose.yaml
`
2. Start the containers
`docker-compose up`

Containers appear to start, but then the following error is printed:

`weaviate_1          | {"action":"ner_remote_wait_for_startup","error":"send check ready request: Get \"http://ner-transformers:8080/.well-known/ready\": dial tcp: lookup ner-transformers on 127.0.0.11:53: no such host","level":"warning","msg":"ner remote service not ready","time":"2022-03-08T18:44:00Z"}`

I am trying to run this on a MacBook Pro running Big Sur.

**Comment by YASH-GU24** [comment]
Hello @argonaut76 i kind of faced similar issue during installation from quick start page.
Then i tried to use the docker file that was generated from here under "Customize your Weaviate Setup" section:- https://weaviate.io/developers/weaviate/current/getting-started/installation.html
And that docker file worked correctly, So i recommend you to try using this.

**Comment by etiennedi** [comment]
Thanks, @argonaut76, for reporting this, and thanks @YASH-GU24 for proposing a workaround.

@laura-ham or @StefanBogdan could one of you investigate what is wrong with the quickstart page? Seems it's related to the `newspublications` demo data set.

**Comment by laura-ham** [comment]
Thanks for raising the issue! I'll update the Quickstart with a working docker-compose file :)

**Comment by laura-ham** [comment]
Changed it on website, so closing this issue! https://github.com/semi-technologies/weaviate-io/commit/39801d8a0550da01b12c5b9c3452a5132b965c1d
