### ISSUE TITLE
Weaviate support Arabic language 

### ISSUE THREAD

**Issue by omarzain27** [semi-technologies/weaviate#1854]
<em>Add Arabic language to weaviate.</em>

**System information** 
- Programming language: Python
- Are you willing to contribute it (Yes/No): I will do my best

**Describe the feature and the current behavior/state:**

This feature allows users to use the Arabic language in Weaviate which is a useful thing and make more people use it.

**Will this change the current API? How?**

This will be a new feature added to python library and no changes in the API will occur

**Who will benefit from this feature?**

The end-user of Weaviate will surely benefit from this since Arabic is mostly carried out. so much a feature will also help in the organization's growth.

**Comment by etiennedi** [comment]
Hi @omarzain27,

thanks for your comment. Could you elaborate a bit on where you are looking for Arabic support? Weaviate is generally agnostic of languages, so I'm wondering what's keeping you from using it with Arabic already?

- Are there any issues occurring when using Arabic characters which don't occur with Latin characters?
- Are you looking for Arabic text2vec-models that can be integrated as part of a Weaviate module?
