### ISSUE TITLE
UX Discussion: certainty / score / distance

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1863]
I would like to discuss the terms `score`, `certainty`, and `distance` in a bit more detail with regards to their UX impact. Most likely we will need to make some sort of a change as the original assumptions when we came up with those terms no longer hold true.

## Background

In the past, the only thing that could determine the order was a vector search. We only supported cosine distance which has fixed bounds from `-1` to `+1`. `certainty` is currently defined as a score between `0` and `1`. For example, this means that a cosine sim of `-1` would lead to the lowest possible certainty (`0`), whereas a cosine sim of `1` would lead to the highest possible certainty (`1`) and values in between would be represented accordingly.

## Problem

This is not compatible with some of the following scenarios which will all happen:

* Introduction of new distances which aren't bounded. A lot of distance metrics that we need to support, do not have a fixed scope. For example, a pure dot product has no upper bound. Therefore the certainty guarantee may fail on a pure vector search
* For a pure BM25 search the score has no upper bound. The lower bound is 0. The assumption is that if we combine dense+sparse search there will also be no upper bound since one of the inputs already has no upper bound.
* An arbitrary re-ranking model may or may not have boundaries for its scores. Since we want to allow any model, we must run under the assumption that scores are sometimes unbounded. This is in line with what we see with a lot of models.
* If we want to allow users to provide custom modules/logic to boost scores etc, we must assume that they are no longer bound.

How do we want to deal with this situation? I would like to start with a proposal, but I'm absolutely open to other proposals as well. I would suggest:

## Suggestion

1. As @bobvanluijt suggested in #1128, we deprecate the term `certainty`. It will not be removed until the next major version. It will stay working under the above guarantees for those distance types where it is possible. It may not work for new unbounded distance types
2. We introduce a new metric called `distance`. It will expose the raw distance that is used. E.g. for cosine, the bounds would be `-1..+1`, for dot product there would be no bounds.
3. We introduce a new metric called `score` which is equal to the negative `distance`. 

Why both `score` and `distance` if one can be calculated from the other? Because some metrics are really scores, others are distance metrics. By exposing both we can make sure that the users can use whatever they are familiar with. For example, if they want to boost something they will most likely work with `scores`, if they want to know how far one is from another they would most likely use `distance`. By offering them both they do not have to worry about converting back and forth.

@laura-ham @bobvanluijt @antas-marcin @byronvoorbach I'm very curious to hear your thoughts on this.

**Comment by laura-ham** [comment]
Agree to what you propose above!

My only concern is that the 'scale' of the `distance` and `score` might not be understood by users if this is not normalized by e.g. taking the cosine distance but instead going for a Euclidian distance, or having something without upper boundaries like BM25. Would it be helpful to also introduce a `normalized_score`, next to `score` and `distance`? (Although I'm not sure how to choose the best normalization function.. perhaps we can ask current users whether they would like to have a `normalization_score` and with which formula?)

**Comment by etiennedi** [comment]
Apologies if that is a stupid question: Is it even possible to normalize an unbounded score? 

Might also make sense to ask some users of existing systems:
* ES uses BM25 (by default) so users of ES should be used to seeing scores without an upper bound should be common to them?
* Maybe also ask Data Scientists who currently work with unbounded similarity/distance metrics if their workflow expects them to have scores in a normalized range or not?

**Comment by laura-ham** [comment]
> Is it even possible to normalize an unbounded score?

Yeah you need to reference points, so usually you take the highest and lowest score and you calculate the normalized score on that scale.

But for sure we need to validate if that is a useful thing to do or not ;)

**Comment by bobvanluijt** [comment]
Just opening this up again because it's something which comes back every so often

**Comment by etiennedi** [comment]
The proposal outlined above is part of the v1.14 release, so should be fixed once and for all.

**Comment by bobvanluijt** [comment]
🥳
