### ISSUE TITLE
Syntax error 

### ISSUE THREAD

**Issue by omarzain27** [semi-technologies/weaviate#1874]
there is a syntax error when I try this code 

![error](https://user-images.githubusercontent.com/87146656/159712749-2159c028-91b8-420a-bf2e-6130cc14a692.PNG)

should be a comma between label name and image 

this is the link https://weaviate.io/developers/weaviate/current/retriever-vectorizer-modules/img2vec-neural.html

**Comment by etiennedi** [comment]
Thanks for spotting this, @omarzain27. @StefanBogdan could you update this snippet in the docs for the python client?

**Comment by laura-ham** [comment]
Thanks for noticing @omarzain27, I've updated the website (it will take a few minutes before it's updated online)
