### ISSUE TITLE
Schema "add properties" does not set "skip" parameter properly

### ISSUE THREAD

**Issue by clharman** [semi-technologies/weaviate#1913]
When adding a property to the schema using the Python client, the "skip" field of moduleConfig.text2vec-transformers will not be set to "true" when that is specified. Full reproduction process:

weaviate-client==3.3.0
weaviate 1.11.0

`curl -o docker-compose.yml "https://configuration.semi.technology/v2/docker-compose/docker-compose.yml?enterprise_usage_collector=false&gpu_support=false&media_type=text&ner_module=false&qna_module=false&runtime=docker-compose&spellcheck_module=false&text_module=text2vec-transformers&transformers_model=sentence-transformers-multi-qa-MiniLM-L6-cos-v1&weaviate_version=v1.11.0"`

`docker-compose up`

```
import weaviate
client = weaviate.Client("http://localhost:8080")

schema = {
    "classes": [
        {
            "class": "Source",
            "description": "A passage from a document",
            "properties": [
            ]
        }
    ]
}
client.schema.create(schema)

add_prop = {
    "dataType": [
    "string"
    ],
    "moduleConfig": {
        "text2vec-transformers": {
        "skip": True,
        "vectorizePropertyName": False,
        }
    },
    "description": "sentiment",
    "name": "sentiment"
}

client.schema.property.create("Source", add_prop)
```

<img width="425" alt="image" src="https://user-images.githubusercontent.com/6020766/163287659-b40ba49d-addf-4e51-a1f3-02c57098a92e.png">

**Comment by etiennedi** [comment]
Thanks again for discovering this and thanks for the perfect reproducing example. We'll look into it and keep you in the loop.
