### ISSUE TITLE
documentationHrefs on Weaviate root url outdated

### ISSUE THREAD

**Issue by laura-ham** [semi-technologies/weaviate#1919]
`documentationHref`s (defined in /adapters/handlers/rest/handlers_misc.go) are outdated. They are pointing to `semi.technoloy` website, but the docs are now live at `weaviate.io`, so some links lead to a 404 page. 

e.g. https://github.com/semi-technologies/weaviate/blob/d169ea75ea3565aff589ee86fb157b379600953e/adapters/handlers/rest/handlers_misc.go#L92

**Comment by soma2000-lang** [comment]
@laura-ham I am working on this
