### ISSUE TITLE
Providing a wrongly formated datetime field as string silently leads to empty Get requests

### ISSUE THREAD

**Issue by chris-aeviator** [semi-technologies/weaviate#1929]
Weaviate V1.12.1

When ingesting a datetime field as `str(datetime.datetime.utcnow())`, my batch ingest runs successfully, I can also see Utilization on the t2v-transformers container, but a query for the class will resolve in a `[]` for all fields in the class.

## Update

The correct way of providing the date for me was `datetime.datetime.now(datetime.timezone.utc).isoformat()`

**Comment by chris-aeviator** [comment]
this seems to have been an issue with `batch_create` not throwing import errors and my disk having crossed ` DISK_USE_READONLY_PERCENTAGE` without me noticing, will update this when having tested my initial assumptions about date strings.

**Comment by etiennedi** [comment]
Thanks, @chris-aeviator 

Also looping in @StefanBogdan in case the missed errors are related to the python client.

**Comment by StefanBogdan** [comment]
Weaviate accepts dates in RFC3339 format. I use [this](https://pypi.org/project/rfc3339/) library to convert timestamp objects into string in RFC3339 format.

Here is a short example:
```
import rfc3339
import datetime

date_str = rfc3339.rfc3339(
    datetime.datetime.now(),
    utc=False,
    use_system_timezone=True,
)
print(date_str)
```

Batch creation skips some validations, so this could be one of those validations that is skipped.
