### ISSUE TITLE
Support for filtering unicode emoji

### ISSUE THREAD

**Issue by ju-bezdek** [semi-technologies/weaviate#1934]
Hi, I would like to find all documents that contains particular emoji... for instance 😂

However this query
```
query = {
                'operator': 'And',
                'operands': [
                    {
                        'path': [TextDocument.COL_TEXT],
                        'operator': 'Like',
                        'valueText': "*😂*"
                        
                    },
                ]
            }
```
            
will return everything... (condition is ignored, returns data without any emoji at all...)

where as 

```
query = {
                'operator': 'And',
                'operands': [
                    {
                        'path': [TextDocument.COL_TEXT],
                        'operator': 'Equal',
                        'valueText': "😂"
                        
                    },
                ]
            }

```
will raise an weird error:
`'explorer: list class: search: object search at index p_testdownloadandprocessdata: shard p_testdownloadandprocessdata_xnDNB996p5Gx: nested clause at pos 0: invalid search term, only stopwords provided. Stopwords can be configured in class.invertedIndexConfig.stopwords'`

and this error is raise even if I turn of all stop words in schema:
```
"stopwords": { 
                            "preset": "none",
                            "additionals":[],
                            "removals":[]
                        },
```

**Comment by parkerduckworth** [comment]
Hey @ju-bezdek, here is some information regarding the implications of using emoji for filtering.

In the example you have provided above, `TextDocument.COL_TEXT` is of property type `text`. When you run a query with a `where` filter, using the `path` of a `text` property, Weaviate attempts to tokenize the `valueText` by splitting the value on all non-alphanumeric characters. Seeing as 😂 is not an alphanumeric character, passing just `*😂*` as `valueText` results in Weaviate determining the value is empty after tokenization. This is the reason for the `only stopwords provided` error message.

However, if you were to change the property type of `TextDocument.COL_TEXT` to type `string`, this limitation no longer applies, and your example query should work with no issues.

Here is some code for a simple reproducible example:

1. Start a Weaviate instance with no modules

2. Create the schema:
    ```
    curl -X POST -H 'content-type: application/json' -d \
        '{"class": "Emoji", "properties": [{"dataType": ["string"], "name": "foo"}]}' \
        localhost:8080/v1/schema
    ```

3. Create 2 objects, one containing emoji:
    ```
    curl -X POST -H 'content-type: application/json' -d \
        '{"class": "Emoji", "properties": {"foo": "😂"}}' \
        localhost:8080/v1/objects

    curl -X POST -H 'content-type: application/json' -d \
        '{"class": "Emoji", "properties": {"foo": "bar"}}' \
        localhost:8080/v1/objects
    ```

4. Run the search:
    - Shell:
        ```
        curl -X POST -H 'content-type: application/json' -d \
            '{"query": "{ Get { Emoji (where: {operator: Like, path: [\"foo\"], valueString: \"*😂*\"}) { foo _additional { id }}}}"}' \
            localhost:8080/v1/graphql
        ```
    - GQL Console:
        ```graphql
        {
          Get {
            Emoji(
              where: {
                operator: Like,
                path: ["foo"],
                valueString: "*😂*"
              }
            ) 
            { 
              foo 
              _additional { 
                id 
              }
            }
          }
        }
        ```

**Comment by ju-bezdek** [comment]
Oh OK.. however I think that emojis would be more likely in text columns... I'd say that string column is meant for "enum-like" fields and text is meant for columns that are expected to be plain human generated text.

Especially when I'm using like with "*" wildcard ... I think that in this case weaviate is not using inverted index for word-tokenised text (or is it?) so why is it performing tokenisation on query value here?

Another idea to consider could be distinguishing based upon id I've used valueString or valueText here...  by the way, I don't really understand why it needs to match here since it's basically the same type.

The logic in my application here is to use like when "*" is present, and Equal if it's not... so changing datatype to string is not really option (unless I mirror the field and use appropriate field based on operation)
