### ISSUE TITLE
Bug: Patching object without vector leads to error

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1936]
## Background

In a recent version we added support for importing objects without a vector, so that it can be replaced later. 

## Bug

It seems that when using `PATCH` on an object without a vector and no vector is being added through the `PATCH` either, an error is thrown.

This is outlined in this [StackOverflow post](https://stackoverflow.com/questions/72004257/bug-in-weaviate-update-data-object-instance-python-client). 

## Status 
We have not yet validated if we can reproduce this bug, hence also no steps to reproduce from our side. However, the SO post seems to contain a reproducing example.

**Comment by parkerduckworth** [comment]
Update: able to reproduce, bugfix PR incoming
