### ISSUE TITLE
How to get ALL records of an index? (above the `QUERY_MAXIMUM_RESULTS`)

### ISSUE THREAD

**Issue by zoltan-fedor** [semi-technologies/weaviate#1947]
Haystack to work with Weaviate as a document store needs to update the embedding of all records of an index stored in Weaviate, but unfortunately there is no obvious way to retrieve **all records** of a Weaviate index due to the `QUERY_MAXIMUM_RESULTS` limit of Weaviate - which cannot be increased unlimited due to memory limitations. As such there is no clear way how to query all records from Weaviate to update the embeddings of all records.

This unfortunately currently makes the Weaviate-Haystack integration not to work - at least not for large datasets (ones with size above the `QUERY_MAXIMUM_RESULTS` limit).
See Haystack bug I have raised: https://github.com/deepset-ai/haystack/issues/2517

**Comment by etiennedi** [comment]
Keep-Alive.

This requires a cursor API.

**Comment by zoltan-fedor** [comment]
Thanks.

Actually I have worked around this by calculating the embedding before upload into Weaviate, so I didn't need to call the `.update_embedding()` to update all records at once.
That one is actually better, as it allows chunked uploading, while `.update_embedding()` would update all records at once - which obviously can take for a long time if you have a large dataset.

But it is good to know that I can also use keep-alive with the cursor API.

I will close this now.

**Comment by Heucles** [comment]
> Thanks.
> 
> Actually I have worked around this by calculating the embedding before upload into Weaviate, so I didn't need to call the `.update_embedding()` to update all records at once. That one is actually better, as it allows chunked uploading, while `.update_embedding()` would update all records at once - which obviously can take for a long time if you have a large dataset.
> 
> But it is good to know that I can also use keep-alive with the cursor API.
> 
> I will close this now.

Hey @zoltan-fedor hope you are doing well, can you share an example on how you got to calculate the embeddings before uploading them into weaviate? 

I'm facing the exactly same issue, I was able to get it to work doubling QUERY_MAXIMUM_RESULTS, which was quite hidden in the docs IMHO, but anyway, I'm very interested on your approach since it is way more efficient, also I was about to make a PR into Haystack to get this cursor working on this class https://github.com/deepset-ai/haystack/blob/main/haystack/document_stores/weaviate.py but since you didn't do it yourself I figure your way is better. 

I am also facing the issue while trying to follow this tutorial: https://www.youtube.com/watch?v=BkozaOnZpJI

Thanks in advance

Heucles

**Comment by zoltan-fedor** [comment]
Hi @Heucles,

The logic is simple:
1. Create Haystack docs out of all your docs
2. Calculate the embeddings (you can use the Haystack `embed_documents()` method on retrievers, including your own custom ones for custom model serving backends)
3. Attach the embeddings to the Haystack docs created above
4. Upload the Haystack docs to Weaviate in chunks

**Comment by Heucles** [comment]
Hey @zoltan-fedor 
Hey @fvanlitsenburg thank you very much for the explanation and attention, I was able to get it to work combining your suggestions and @fvanlitsenburg 's , I thank you both very much! Here is the final code: 

```Python
import weaviate
import pandas as pd
import os

from haystack.utils import clean_wiki_text
from haystack import Document
import pandas as pd

def pre_embedder(docs, haystack_document_store, embedding_model, model_format):
    print('Running the pre-embedding')
    retriever = EmbeddingRetriever(
    document_store=haystack_document_store,
    embedding_model=embedding_model,
    model_format=model_format
    )
    embeds = retriever.embed_documents(docs)
    for doc, emb in zip(docs,embeds):
        doc.embedding = emb
    return docs



harry = pd.read_csv("documents/harry_potter_wiki.csv")

dicts = []

for ix, row in harry.iterrows():
    dic = Document(
        content=clean_wiki_text(row.text),
          meta={'name': row['name'], 
                'url': row.url})
    
    dicts.append(dic)

print('Running the pre-embedding and writing the documents so there is no need to update')
from haystack.nodes import EmbeddingRetriever
from haystack.document_stores import InMemoryDocumentStore
from haystack.document_stores import WeaviateDocumentStore
weaviate_document_store = WeaviateDocumentStore() # assumes Weaviate is running on http://localhost:8080
BATCH_SIZE = 500
dict_embeddings = []
in_memory_document_store = InMemoryDocumentStore()
for i, dic in enumerate(dicts):
    dict_embeddings.append(dic)
    if i>0 and i % BATCH_SIZE == 0:
        print ('----------------------------------------------------------------------------')
        print(f'Batching and inserting from: {i - BATCH_SIZE} till {i}')
        print ('----------------------------------------------------------------------------')
        dict_embeddings = pre_embedder(docs=dict_embeddings, haystack_document_store=in_memory_document_store, model_format="sentence_transformers", embedding_model="sentence-transformers/multi-qa-mpnet-base-dot-v1",)
        weaviate_document_store.write_documents(dict_embeddings, index='potterDocuments')
        in_memory_document_store = InMemoryDocumentStore()
        dict_embeddings = []
        
```

One thing if might add, is that I needed to cast the objects into a [Haystack Document](https://docs.haystack.deepset.ai/docs/documents_answers_labels#document), but other than that it was fairly easy! Thank you very much again!
