### ISSUE TITLE
Aggregate - nearObject -> is ignoring certainty

### ISSUE THREAD

**Issue by ju-bezdek** [semi-technologies/weaviate#1970]
This kind of query should return very little results... since certainty 0.99 is very hard to achieve

```graphql
{
  Aggregate {
    P_374c4574_88bd_48e8_b842_82ea56c1b1e5(
      groupBy: ["labels"]
      nearObject: {id: "62739671-d833-47b5-b049-a9746f70065f", certainty: 0.99}
    ) {
      groupedBy {
        value
      }
      meta {
        count
      }
    }
  }
}
```

however... it returns lots of results...

the results are the same as for 0.09
so I assume certainty is being ignored.

I think certainty should limit data that are taken in consideration... I don't see any value to allow nearObject, without allowing limiting certainty, since all of the data have some similarity to the target object.

**Comment by ju-bezdek** [comment]
I forgot - im running v1.13.2

**Comment by eostis** [comment]
I was about to write the same issue !

The certainty works for near search, aggregation, but not for group by.
With group by, results are always the same, with a certainty of 0 or 1.

**Comment by parkerduckworth** [comment]
I have provided a fix for this issue in the [PR linked above](https://github.com/semi-technologies/weaviate/pull/1975). I was able to reproduce the same issue that @ju-bezdek described, and this fix seems to introduce the correct behavior. @ju-bezdek @eostis please feel free to reopen this issue if for some reason the problem persists for you after using the latest build.
