### ISSUE TITLE
Cannot aggregate on a date field

### ISSUE THREAD

**Issue by eostis** [semi-technologies/weaviate#1982]
Here is the content of the date field:
<img width="1451" alt="image" src="https://user-images.githubusercontent.com/1785759/173571157-cceff50a-bce6-49f0-98a3-8735c4374ec3.png">

And here is the min/max aggregations queries:

<img width="1508" alt="image" src="https://user-images.githubusercontent.com/1785759/173571560-41a7a8ce-37eb-4e42-8f75-1c4267da5bbb.png">

<img width="1500" alt="image" src="https://user-images.githubusercontent.com/1785759/173571864-06a811f3-c1f1-434d-932c-fe950c5a55d5.png">

**Comment by parkerduckworth** [comment]
@eostis thanks for raising this issue. With the addition of PR #1987, aggregating on date fields is now supported.
