### ISSUE TITLE
Create a script or function to re-index existing data while switching/updating to a new model

### ISSUE THREAD

**Issue by tacohiddink** [semi-technologies/weaviate#1983]
When switching to a different t2v-transformers model, do I have to re-index the current data that is already in Weaviate? Or does weaviate replace the vectors automatically? I am wondering what happens or what to do with existing data (that probably has vectors based on the old model)

I would consider it a valid use-case as models get better over time and one would probably switch to a newer model then. Probably need to re-index the whole db from scratch then.

Can a command be created to facilitate such a usse-case?

**Comment by zoltan-fedor** [comment]
I was thinking about the same.

I could imagine a similar process as to what you have when you do key rotation in a key-based authentication.

Basically having two embeddings, where the second one is the one currently built and once the build is complete, then you switch from the first to the second one.
