### ISSUE TITLE
(bug) Sort depending on limit

### ISSUE THREAD

**Issue by eostis** [semi-technologies/weaviate#2003]
Below are 2 sorts that should order results in the same way.

 
With limit 30 (5th results is 41):
<img width="1621" alt="image" src="https://user-images.githubusercontent.com/1785759/175786422-957d3906-9175-487a-a411-ba2d1cf983c0.png">

With limit 5 (5th results should also be 41, but is 30):
<img width="1448" alt="image" src="https://user-images.githubusercontent.com/1785759/175786452-de295368-dc3a-41bf-b185-436150b49617.png">

**Comment by etiennedi** [comment]
Thanks for reporting this. Can you elaborate what you had to do to run into this? Does this only occur when sorting by two fields or only with one?

**Comment by antas-marcin** [comment]
Can you also verify one thing for me, can you add `id` (`_additional { id }`) to your query and check if there any objects with duplicate ids in the results of your query?

**Comment by eostis** [comment]
- It happens with 2 sort fields only.
- Class has default docker settings (one shard I guess).
- Version was 'latest' at the time of the issue.
- id is unique.

**Comment by eostis** [comment]
👍
