### ISSUE TITLE
Module behaviour on OpenAI request content is to large

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#2024]
Currently, the OpenAI module might return:

```
{
    'error': [
        {
            'message': "failed with status: 400 error: This model's maximum context length is 2046 tokens, however, you requested 142471 tokens (142471 in your prompt; 0 for the completion). Please reduce your prompt; or completion length."
        }
    ]
}
```

Can this be handled in the module? E.g., for this specific example that the `142471` token string is split into (`142471/2046`) 70 snippets, and a centroid is calculated and stored?

**Comment by etiennedi** [comment]
Great find! Indeed the other modules are handling this as part of the inference, I'm surprised OpenAI does not handle this server-side. Do we know if the 2046 is a global limit that we can hard-code or does this depend on the model selected?

**Comment by bobvanluijt** [comment]
Asked it [here](https://community.openai.com/t/is-the-2046-token-limit-embeddings-api-a-global-limit/19476)
