### ISSUE TITLE
Bug (?): Referenced class does not vector on _additional { vector }

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#2035]
Example from [Slack](https://weaviate.slack.com/archives/C017EG2SL3H/p1658147302507679):

```
{
  Get {
    Document(nearText: { concepts: ["test"] }) {
      content
      sentences {
        ... on Sentence {
          _additional {
              vector # this seems not to work because it's always null
          }
        }
      }
    }
  }
}
```

returns a `null` vector even when the vector is set.

Is there a technical limitation for this or is it simply missing?

**Comment by danieldaeschle** [comment]
There is also this which looks the same: https://github.com/semi-technologies/weaviate/issues/1735

**Comment by etiennedi** [comment]
Indeed, closing this as duplicate and continue on the other one.
