### ISSUE TITLE
(bug) WCS sandbox cluster wizard not showing modules anymore

### ISSUE THREAD

**Issue by eostis** [semi-technologies/weaviate#2058]
The modules list is empty while creating a new sandbox cluster on WCS:
<img width="961" alt="image" src="https://user-images.githubusercontent.com/1785759/181258505-f205d0f3-0c59-4e03-8a3d-e6d780e7e184.png">

**Comment by bobvanluijt** [comment]
hi @eostis –

That's for now a conscious decision. We are ramping up the Weaviate Cluster Service team and also how modules are handled (pragmatically, the transformers module couldn't be used in production for sandboxes). You can still generate them locally [here](https://weaviate.io/developers/weaviate/current/getting-started/installation.html#customize-your-weaviate-setup). If you need something specific, feel free to reach out to me (under my name) on our Slack channel [here](https://join.slack.com/t/weaviate/shared_invite/zt-goaoifjr-o8FuVz9b1HLzhlUfyfddhw).

Closing for now assuming that your question is answered :-)

**Comment by eostis** [comment]
Thanks!

I could indeed create a class with my sandbox cluster, with no module (from WPSOLR's WooCommerce add-on)

![image](https://user-images.githubusercontent.com/1785759/181312891-a0c4ef32-d727-45d0-83cf-e5f21a7a2137.png)

**Comment by bobvanluijt** [comment]
Hi @eostis –

We have now launched the renewed WCS, this comes with OOTB integrations for OpenAI and Huggingface Inference.

**Comment by eostis** [comment]
Thanks @bobvanluijt 

It makes sense to deport the heavy GPU Vectorization to external APIs for the free tier.

I just have now to add the [Huggingface module ](https://weaviate.io/developers/weaviate/current/retriever-vectorizer-modules/text2vec-huggingface.html) to [WPSOLR](https://www.wpsolr.com), as I did with the [OpenAI module](https://weaviate.io/developers/weaviate/current/retriever-vectorizer-modules/text2vec-openai.html), to get a free access to hosted Weaviate with thousands of transformer models.

**Comment by bobvanluijt** [comment]
That's great news! @sebawita, maybe we can help with a demo or so ⏫ ?
