### ISSUE TITLE
Allowing BM25 search to be combined with filters

### ISSUE THREAD

**Issue by zoltan-fedor** [semi-technologies/weaviate#2061]
I know that BM25 is still experimental - and so this might be coming, but I just wanted to make sure to note one of the big shortcomings of the current experimental BM25 support, namely that the BM25 search currently cannot be combined with filters.

So the request is to get full filtering support added to the BM25 search.

Thanks

**Comment by zoltan-fedor** [comment]
The same has been raised again at https://github.com/semi-technologies/weaviate/issues/2393, please follow that issue.

**Comment by etiennedi** [comment]
Check, closing this one since the other one already has votes now.
