### ISSUE TITLE
Document upgrade and downgrade processes

### ISSUE THREAD

**Issue by zamazan4ik** [semi-technologies/weaviate#2100]
Hi.

After reading the documentation it is not clear for me, how upgrade and downgrade processes should be performed over the solution. Could you please describe somewhere in the documentation:

- How to upgrade Weaviate to the newer version without downtime
- How to downgrade Weaviate to the older version (hopefully with no downtime)
- Maybe some compatibility policies and notes between versions

Thanks in advance!

**Comment by witwit-manish** [comment]
Hi,
I am also interested in knowing the process for upgrade and rollback.

Thanks
