### ISSUE TITLE
[new feature] Reranking models after retrieval

### ISSUE THREAD

**Issue by eostis** [semi-technologies/weaviate#2105]
Following up @laura-ham 's article on [cross-encoder reranking ](https://weaviate.io/blog/2022/08/Using-Cross-Encoders-as-reranker-in-multistage-vector-search.html)

This would be a great idea to add a reranking inference setup in Weaviate's modules !!! (like [Vespa](https://docs.vespa.ai/en/reranking-in-searcher.html )?)

**Comment by etiennedi** [comment]
We are currently evaluating a few possible Pipeline options internally and will start going public once we have agreed on an initial draft. :-)

**Comment by eostis** [comment]
Duplicate of #2111
