### ISSUE TITLE
Support sharding by fields other than `_id`

### ISSUE THREAD

**Issue by trengrj** [semi-technologies/weaviate#2149]
Currently this error occurs when trying to shard by another field:

```json
"shardingConfig": {
        "key": "partition_group",
        "strategy": "hash",
        "function": "murmur3"
}
```

```
Create class! Unexpected status code: 422, with response body: {'error': [{'message': "parse vector index config: sharding only supported on key '_id' for now, got: partition_group"}]}
```

Sharding by alternative fields would allow for filters to be more efficient. For example if each query has a filter by `partition_group`, only one shard will have this data and so a filtered vector search would reduce to a non-filtered vector search on a reduced set of shards.

**Comment by etiennedi** [comment]
Agreed about the filters, this was the original motivation behind making that configurable (even when only one option is supported right now).

I think that this comes with two downsides that we need to be aware of:
* Any get-by-id-style request would be considerably more expensive, as it would essentially turn into a search that needs to hit all shards.
* We could remedy the above by giving the user an option to provide the sharding-key
* Resolving cross-references is essentially a lookup-by id, so a setup that makes use of lots of cross-references would lead to increased inter-node traffic.

It's difficult for me to say with certainty how big of a feature request this would be. I think it would be a considerable change, but not massive. Still, I would say that this could make the most sense after the replication milestone?

**Comment by etiennedi** [comment]
> only one shard will have this data and so a filtered vector search would reduce to a non-filtered vector search on a reduced set of shards.

I'm not sure if this is always true. I agree with the part that a single shard can serve the request. But will it always become an unfiltered one? I don't think so, as this shard could still host multiple partitions. E.g. Let's say we have two shards and four possible values. We assume it's distributed evenly, so each shard holds two value partitions. We'd still need the filter then to narrow it down from two to one.

Nevertheless, this should considerably improve throughput if queries are partitioned well across a multi-node setup.

**Comment by trengrj** [comment]
Yes you are right that we would need to provide a sharding-key for any update, get, and search request.

In other search implementations this is known as the `routing` parameter. Elasticsearch parses this as a query parameter, Solr can do this routing using a "composite id" https://lucidworks.com/post/solr-cloud-document-routing/ where the id of the document is of the form `shard_key!document_id`.

Here are two use cases for the feature:

**Use case 1:**
Medium (millions) scale dataset with queries filtered on the language field (10 x languages). One shard per node. Queries filter on language.

With a routing flag on language, queries on a single language would route to a single shard. It may not remove the filter completely as it depends if multiple languages map to the same shard.

**Use case 2:**
Large (billion) scale dataset with queries filtered on the user field with each user having ~ 10,000 objects. In this example routing on user would mean query would map to single shard. One issue here is that the 10,000 matching objects would be < 15% of the large dataset and so Weaviate would execute as a flat HNSW search.

**Comment by plv** [comment]
@trengrj @etiennedi Did this ever end up getting implemented?
