### ISSUE TITLE
Error when deploying weaviate as Azure Web app

### ISSUE THREAD

**Issue by krlng** [semi-technologies/weaviate#2165]
Hello,

I tried to deploy weaviate (version 1.14.0) as an Azure Web App using docker. I get this cryptic error:
`create member list: Failed to get final advertise address: No private IP address found, and explicit IP not provided`

When searching for this error, I find similar issues of other libraries that can be deployed in a cluster-way (loki, prometheus, etc.), when they are deployed to a container management service such as kubernetes or in this case azure web app. The problem seams to be, that the ip-range used within the cluster conflicts somehow with the one used by the management service. 

As I am unable to change the ip-ranges used by azure web apps, is there some config to change within weaviate?

**Comment by kishore25kumar** [comment]
+1

**Comment by kishore25kumar** [comment]
@krlng Were you able to resolve this issue?

**Comment by krlng** [comment]
I avoided it by using docker compose, even that this brings new difficulties with azure apps

**Comment by kishore25kumar** [comment]
@krlng You used preview feature of docker compose to deploy it? I will give it a try but what are the challenges you faced when deploying it as docker compose?

**Comment by krlng** [comment]
Yes, actually I had a docker-compose before anyway. I thought of switching as I wanted to use proper Azure authentication methods which are not supported in the docker-comose preview, so I thought I run both containers on their own, then stumbled across this issue here and switched back.

**Comment by felixng313** [comment]
+1
