### ISSUE TITLE
No way to configure Auto-schema defaults

### ISSUE THREAD

**Issue by adlerfaulkner** [semi-technologies/weaviate#2290]
There currently seems to be no way to configure the default `vectorIndexConfig` settings for auto-schemas. I would like to use auto-schemas but have them default to using `l2-squared` distance comparison rather than `cosine`. 

Perhaps this could be done through an environment variable or a config file?

**Comment by etiennedi** [comment]
This idea makes perfect sense to me. Cc @antas-marcin - I believe we already have some default env vars for auto-schema, right? Maybe we can extend this to include a default for the distance metric?

**Comment by adlerfaulkner** [comment]
It seems like all the `vectorIndexConfig` values are defaulted here:
https://github.com/semi-technologies/weaviate/blob/96ac00500c6231094c9789f857ac739a281631e0/entities/vectorindex/hnsw/config.go#L32-L44

From what I've found the only env vars dealing with auto-schema are `AUTOSCHEMA_ENABLED`, `AUTOSCHEMA_DEFAULT_STRING`, `AUTOSCHEMA_DEFAULT_NUMBER`, `AUTOSCHEMA_DEFAULT_DATE`

I can add `AUTOSCHEMA_DEFAULT_DISTANCE_METRIC`

**Comment by etiennedi** [comment]
After thinking a bit more about this, it might make sense to do this independent of auto-schema and just have a `DEFAULT_VECTOR_DISTANCE_METRIC` or something like that. The difference to `AUTOSCHEMA_DEFAULT_DISTANCE_METRIC` is subtle, but I think there is one key difference:

* Set `AUTOSCHEMA_DEFAULT_DISTANCE_METRIC=l2-squared`. Now any implicitly created class will be of type `l2-squared`. But any explicitly created class that no distance metric set, would still default to `cosine`. That might be confusing.
* Set `DEFAULT_VECTOR_DISTANCE_METRIC=l2-squared`. Any new class - whether implicitly created through auto-schema or explicitly created without a distance metric set - would now default to `l2-squared`. I think that's less confusing.

**Comment by adlerfaulkner** [comment]
Yeah, makes sense. Makes the change simpler too.

**Comment by eostis** [comment]
It would be great to have AUTOSCHEMA_ENABLED configured from the API too!
