### ISSUE TITLE
Console errors with Chrome

### ISSUE THREAD

**Issue by eostis** [semi-technologies/weaviate#2305]
I currently cannot login to the console on Chrome. It's fine on Firefox.

<img width="1788" alt="image" src="https://user-images.githubusercontent.com/1785759/196198483-82793e12-f3ea-4832-9c9e-59c41fb028dc.png">

**Comment by eostis** [comment]
Chrome: Version 106.0.5249.119 (Official Build) (x86_64)
OS: MacOS Monterey 12.6

**Comment by trengrj** [comment]
Currently it is working for me on Chrome: Version 106.0.5249.119 (Official Build) (arm64). Have you tried running in an incognito window or clearing you cache?

@antas-marcin

**Comment by eostis** [comment]
incognito window is fine, cache is not.

I'm closing the issue, as it looks like my problem.
