### ISSUE TITLE
Error sent from Weaviate: oidc auth is not configured, please try another auth scheme or set up weaviate with OIDC configured

### ISSUE THREAD

**Issue by eostis** [semi-technologies/weaviate#2334]
Hi,

I created a sandbox WCS cluster, with OIDC turned off.

When I connect to the cluster, using the WCS account's email/password, I get this OIDC error message (see title above).

![image](https://user-images.githubusercontent.com/1785759/199218807-2f5c58d7-2321-4b65-ab2a-9b36aaa55dd3.png)

**Comment by samos123** [comment]
I'm seeing the same after reconnecting to my WCS instance which has OIDC authentication disabled. Feel free to ping me for the cluster ID.

**Comment by eostis** [comment]
@samos123 Thanks. My cluster id: wpsolr-demos (nothing confidential)

**Comment by samos123** [comment]
I found a workaround. Disconnect from the cluster and then reconnect through WCS. 

More details: I had 2 clusters, I connected to my other cluster and then reconnected to broken cluster that had the issue but after reconnecting it worked again.

**Comment by eostis** [comment]
I tried your workaround, with no success.

**Comment by Victor94-king** [comment]
halo , could you plz tell me how did u made it work? I faced the same issue like u

**Comment by eostis** [comment]
@Victor94-king I'm not using WCS anymore, sorry. Due to https://github.com/weaviate/weaviate/issues/2429.
