### ISSUE TITLE
Stemming instead of 'Like' operator 

### ISSUE THREAD

**Issue by PlkMarudny** [semi-technologies/weaviate#2428]
Would it be beneficial to use stemming instead of 'Like' operator? Sure, inverted index would be bigger, but tokenization based on word boundaries is not enough sometimes. In fact, quite often.

**Comment by etiennedi** [comment]
I've created a [Feature Request for Stemming here](https://github.com/semi-technologies/weaviate/issues/2439). Feel free to upvote it.

**Comment by PlkMarudny** [comment]
Well, no, I do not use Like operator, this is too expensive for a big data
set. Would prefer to have a proper inverted index for scalar searches.

**Comment by etiennedi** [comment]
That makes sense, it's a very expensive operator. So to make sure I understand your original title for this issue; you're saying: Since there is no stemming support, I need to either accept that some similar words don't match or I would have to start using a Like operator which is too expensive. Correct?

**Comment by PlkMarudny** [comment]
Yes, that's correct. I had some success using "autocorrect", but well, it
is not exactly the same.

**Comment by PlkMarudny** [comment]
To give more perspective: I have hundreds thousands of videos, some with
good description, tagged using some image recognition, audio transcripted
and so on. Vector search is a great help, of course, but sometimes pure
scalar search makes sense as well. And this is where Weaviate falls short
somehow. Imagine a situation, where an user searches for an event in a city
with unknown exact spelling. Very unlikely it can be found at all.

**Comment by etiennedi** [comment]
That makes sense; thanks for elaborating. I'm closing this one, as the "official" issue to track stemming is now #2439.
