### ISSUE TITLE
Support OpenAI `text-embedding-ada-002` in `text2vec-openai`

### ISSUE THREAD

**Issue by kcm** [semi-technologies/weaviate#2449]
OpenAI released a new embedding model, `text-embedding-ada-002`. This outperforms the previous models in almost every situation, and is vastly cheaper (99% less!).

https://openai.com/blog/new-and-improved-embedding-model/
https://beta.openai.com/docs/guides/embeddings

> Unification of capabilities. We have significantly simplified the interface of the [/embeddings](https://beta.openai.com/docs/api-reference/embeddings) endpoint by merging the five separate models shown above (text-similarity, text-search-query, text-search-doc, code-search-text and code-search-code) into a single new model. This single representation performs better than our previous embedding models across a diverse set of text search, sentence similarity, and code search benchmarks.

> Longer context. The context length of the new model is increased by a factor of four, from 2048 to 8192, making it more convenient to work with long documents.

> Smaller embedding size. The new embeddings have only 1536 dimensions, one-eighth the size of davinci-001 embeddings, making the new embeddings more cost effective in working with vector databases.

> Reduced price. We have reduced the price of new embedding models by 90% compared to old models of the same size. The new model achieves better or similar performance as the old Davinci models at a 99.8% lower price.

We should support this in Weaviate as an option for the `text2vec-openai` model. It may even make sense to default to this model going forward if one is not specified explicitly, as it has virtually no drawbacks per OpenAI's announcement and documentation.

**Comment by kcm** [comment]
https://github.com/semi-technologies/weaviate/pull/2448

**Comment by eostis** [comment]
The model names of the openAI vectorizer should align with the model name of QnA #2432

(Use full name like "text-embedding-ada-002" rather than build it from type and model)

**Comment by etiennedi** [comment]
Closing as complete. For arbitrary model strings, see #2452.
