### ISSUE TITLE
[text2vec-openai] 1.16.8 using wrong model for graphql get

### ISSUE THREAD

**Issue by adambeer** [semi-technologies/weaviate#2458]
When setting the model to ada and modelVersion to 002, calling /graphql Get seems to be using the old ada model. I am getting this error when making the /graphql call:

> explorer: get class: vector search: object vector search at index document: shard document_HUM50X6K4c8M: vector search: knn search: distance between entrypoint and query node: vector lengths don't match: 1536 vs 1024

**Comment by adambeer** [comment]
I can confirm this because on our OpenAI account all tests were charged using 'text-search-ada'.

**Comment by etiennedi** [comment]
Thanks for the report, will look into it.

**Comment by etiennedi** [comment]
I can confirm (and reproduce) this – looking into a solution now.

**Comment by etiennedi** [comment]
A fix is available in this [preview image](https://github.com/semi-technologies/weaviate/actions/runs/3719127033#summary-10155766402). Can you confirm that this is also fixed for you? Then we can release this as `v1.16.9`.

**Comment by adambeer** [comment]
Looks like that fixed it!

**Comment by etiennedi** [comment]
Fixed in `v1.16.9`.
