### ISSUE TITLE
Does hybrid search work with all vectorizers?

### ISSUE THREAD

**Issue by eostis** [semi-technologies/weaviate#2479]

**Comment by etiennedi** [comment]
We have evaluated it with

✅ `text2vec-transformers`
:white_check_mark: `text2vec-huggingface`
:white_check_mark: `text2vec-contextionary`
:white_check_mark: `text2vec-openai`
:white_check_mark: `text2vec-cohere`
:white_check_mark: `multi2vec-clip`

I think that should be all, so I would say "yes".
