### ISSUE TITLE
Updating OpenAI module config

### ISSUE THREAD

**Issue by george-i** [semi-technologies/weaviate#2492]
As you probably know, on 16th of Dec 2022 OpenAI has released a new embedding model, cheaper and more powerful.
On my Weaviate cloud space I have a class for which I want to change the embedding model to the new one.
I tried the request below, but it doesn't lead anywhere.

```
curl --location --request PUT 'https://[my-workspace].semi.network/v1/schema/Posts/' \
--header 'Content-Type: application/json' \
--data-raw '{
    "class": "Posts",
    "vectorizer": "text2vec-openai",
    "moduleConfig": {
        "text2vec-openai": {
            "model": "ada",
            "modelVersion": "002",
            "type": "text"
        }
    }
}'
```

The response was 
```
{
    "error": [
        {
            "message": "properties cannot be updated through updating the class. Use the add property feature (e.g. \"POST /v1/schema/{className}/properties\") to add additional properties"
        }
    ]
}
```

**Comment by trengrj** [comment]
Hi @george-i, the issue with changing the vectorizer model in a class is that the distances and distributions of the vectors change (i.e. "dog" in ada-001 is no longer close to "dog" in ada-002).

Recommendation here would be to create a new class and copy old data over. This should be easier soon with the planned [reindex api](https://github.com/semi-technologies/weaviate/issues/2359).
