### ISSUE TITLE
(feature request) For real search usage (asymmetric), implement a multi-stage search with cross-encoder reranking

### ISSUE THREAD

**Issue by eostis** [semi-technologies/weaviate#2513]
([As described on Weaviate blog post](https://weaviate.io/blog/2022/08/Using-Cross-Encoders-as-reranker-in-multistage-vector-search.html))

Arguments:
- Most searches are asymmetric: query is much shorter than the corpus. Especially e-commerce (and for my use case WooCommerce)
- Asymmetric models are cross-encoders like MS-MARCO (see https://www.sbert.net/examples/applications/semantic-search/README.html?highlight=asymmetric)
![image](https://user-images.githubusercontent.com/1785759/211193911-3154aaf4-73bf-44f4-843f-c7a89c55f997.png)
- Cross-encoders cannot be used on first retrieval stage for performance reasons mentioned in the blog post

Conclusion: for a realistic search, we need a 2 stages search: a bi-encoder/BM25 retrieval followed with a cross-encoder re-ranking !!

(Of course it should work with filters, aggregations, and hybrid mode)

**Comment by etiennedi** [comment]
Is this a duplicate of https://github.com/semi-technologies/weaviate/issues/2111?

**Comment by eostis** [comment]
Yes!
