### ISSUE TITLE
Feature Request: Retrieve objects based on the keywords in fields

### ISSUE THREAD

**Issue by wyzhangyuhan** [semi-technologies/weaviate#2528]
In my case, I not only need to search by my own vector, but also by some keywords in different fields.

Browsering through  the weaviate document, I cannot find the function.

Has weaviate considered supporting vector search as well as keyword search in some paticular fields?

In my opnion, this feature is very common in many real businesses. Hope to support this feature in the future

**Comment by etiennedi** [comment]
Yes, this is supported using the `where` filter, see [Where Filter](https://weaviate.io/developers/weaviate/current/graphql-references/filters.html#where-filter). Please let me know if that answers your question, if not feel free to re-open.
