### ISSUE TITLE
Weaviate on Kubernetes is totally unavailable during Helm upgrade

### ISSUE THREAD

**Issue by eostis** [semi-technologies/weaviate#2536]
Hi,

(Testing on Google Cloud Kubernetes)

I noticed that when updating Weaviate (for instance activating a module in values.yaml with helm upgrade), the whole Weaviate access is 404 (admin REST API, indexing, querying) for several minutes.
This is a bit unnerving on a production environment.

**Comment by trengrj** [comment]
Are you able to provide:
- The total number of objects in Weaviate
- What version you were upgrading from and to?

**Comment by etiennedi** [comment]
Do you use Replication (introduced in v1.17.0)? For a zero-downtime upgrade, you need to have more than a single pod that can serve traffic.

**Comment by eostis** [comment]
The replication makes sense. I'll try that.
