### ISSUE TITLE
Extend wordlist to have different kinds of words

### ISSUE THREAD

**Issue by moretea** [semi-technologies/weaviate#365]
Must be able to look up the kind of a word.

* unknown / other
* noun, singular
* noun, plural
* verb

Can be build with:
https://wordnet.princeton.edu/download/current-version

**Comment by bobvanluijt** [comment]
Currently looking at using a model because wordnet covers about 15% of the Contextionary.

**Comment by etiennedi** [comment]
Closing as obsolote.
