### ISSUE TITLE
Check test for ontology property datatype rules

### ISSUE THREAD

**Issue by laura-ham** [semi-technologies/weaviate#385]
Current implementation: test checks if datatype of class properties in the ontology contains _either_
- Classes (one or multiple)
- _One_ of the following datatypes: string, integer, number, date, boolean.

Proposed is that property datatypes can contain both:
- Classes (one or multiple)
- _One_ of the following datatypes: string, integer, number, date, boolean. ( _not_ multiple)

This should therefore be changed so that when Weaviate initializes a new ontology this will pass the

**Comment by bobvanluijt** [comment]
@moretea is this still open / relevant?

**Comment by etiennedi** [comment]
Closing as obsolote.
