### ISSUE TITLE
Run multiple instances of weaviate in one process

### ISSUE THREAD

**Issue by moretea** [semi-technologies/weaviate#407]
This would enable testing networking scenario's way faster then when we would have to run multiple Weaviate instances in different processes.

**Comment by etiennedi** [comment]
@moretea Can you elaborate a bit on what you mean by "in one process" as opposed to "in different processes"?. This sounds quite close to our Slack conversation (attached below for those that weren't part of it ;-)) about a potential development environment when testing the p2p feature.

> etienne [10:09 PM]
> I just had some random thoughts about a potential development environment for the P2P feature. Do you think it's feasible to run two complete weaviate's in a single docker-compose setup? Just tried spinning up a second instance with a different project name. This fails of course because we expose ports that are then already occupied.
> 
> So a couple of options I currently see are
> - Not forwarding so many ports to the host machine. Since we only interact with the weaviate API we'd only need 8080 there. For a second instance we could use `8081:8080` or something. This could make a multi-weaviate setup on a single docker machine feasible
> - Using the helm-chart and deploy two instances in two namespaces on minikube. While the sepearation works great here, I have bad experience with relying on minikube and fear long feedback cycles
> - Rely heavily on contract testing / fakes and only very rarely actually spin up a multi-weaviate setup, for example on an actual cluster (<-- currently my favorite)
> 
> Any thoughts on this? (edited)
> 
> 
> Maarten Hoogendoorn [10:42 AM]
> I'd indeed go for the latter
> That is a good way to have fast feedback cycles.
> I would abstract requests over the netwerk by some interface. You can then simply mock this out, and simulate different kind of failures
> Then I'd include a few happy path tests with a full setup of two instances of Weaviate.
> 
> etienne [10:45 AM]
> Great. That sounds indeed like a good plan.
> 
> Maarten Hoogendoorn [10:45 AM]
> I thought before about introducing some kind of prefix so that we can reuse a janus instance
> but that is proably very tricky
> in principle you can have multiple graphs (e.g. USE $graphname in SQL), but I've no idea how that actually works

**Comment by etiennedi** [comment]
Closing as obsolote.
