### ISSUE TITLE
'meta' as reserved property name in schema

### ISSUE THREAD

**Issue by laura-ham** [semi-technologies/weaviate#440]
'meta' is used for querying meta information about classes and instances by GraphQL at the same level as properties, so using this word is not possible to use as property name in a Weaviate Schema. 
This should be checked in the schema validation test when starting Weaviate.

**Comment by bobvanluijt** [comment]
@laura-ham can you elaborate a bit more?

**Comment by laura-ham** [comment]
> @laura-ham can you elaborate a bit more?

@bobvanluijt `meta` is used on the same level as property names in the `GetMeta` GraphQL query. Therefore, "meta" should not be used in the ontology schema as property name. 
See https://github.com/creativesoftwarefdn/weaviate/blob/develop/docs/en/use/graphql_local.md#getmeta-function how `meta` is used in the `GetMeta` query.

**Comment by etiennedi** [comment]
@laura-ham I just discovered this quite old issue. Reading through it I think it still makes sense, so I think we should keep it. Agreed, or has anything changed? (other than the query being `Aggregate ... { meta { count } }` instead of `Meta ... { meta { count } }`)

**Comment by laura-ham** [comment]
@etiennedi Yeah I'm still all for it since we still use `meta` in standard GraphQL queries

**Comment by bobvanluijt** [comment]
@laura-ham is this still relevant?
