### ISSUE TITLE
Properly handle errors in GraphQL endpoint.

### ISSUE THREAD

**Issue by moretea** [semi-technologies/weaviate#447]
in `api.GraphqlWeaviateGraphqlPostHandler`:

- `errorResponse.Error.Error.Message` is not never set.
- Currently we return an OK status, even if the query failed. We probably should return an error state there too
    - This need to be verified with what GraphQL endpoints are expected to do.
    - If this is indeed expected, extend API to return error type with JSON doc that describes the error.

**Comment by bobvanluijt** [comment]
note to self: research and resolve.

**Comment by etiennedi** [comment]
Closing as the current status seems to be in line with GraphQL best practices.
