### ISSUE TITLE
Make configuration easier

### ISSUE THREAD

**Issue by moretea** [semi-technologies/weaviate#450]
I propose to drop storing different environments in one file, and using YAML instead of JSON.

May production systems (e.g. Postgres, janusGraph) don't support configuring multiple "environments" in one file. In fact, this goes directly against the widely accepted 12 factor applications, see their page about [configuration](https://12factor.net/config)

One thing they all _do_ support though, is a configuration format that allows for comments.

This will enable us to write a default configuration file with all options mentioned, but commented out.

**Comment by bobvanluijt** [comment]
Yes, we have to discuss how to move forward with this. The original concept was based on running the server via the command line (port, host, etc) and configuration via a configuration file.

- I'm all for dropping multiple environments in a single file.
- I think that _only_ working with a config file might even better, we do break Go-Swagger's command line implementation, though.

Curious what your thoughts are @moretea

**Comment by moretea** [comment]
In Cloud Native systems, we try to make applications behave in such a way that they need a minimum set of options, and provide sane default, so that you can quickly run your system.

Do you configure your web browser before you first start it? No. It provides sane defaults. 

From an operations perspective, it is way easier if _everything_ can be configured in a few different ways;

1. Sane defaults
2. Optional configuration file
3. Environmental Variables
3. Command line parameters

This also ties into your question about #420. If the database schema lives _in_ Weaviate (like most data stores behave), we won't need files with the schemas either.

**Comment by moretea** [comment]
We can do an experiment to see what is actually overwritten by go-swagger, and maybe even automatically undo that in the `tools/gen-code-from-swagger.sh` script.

**Comment by bobvanluijt** [comment]
Agreed.

On the wider topic of schema: https://github.com/creativesoftwarefdn/weaviate/issues/420#issuecomment-415967238

**Comment by bobvanluijt** [comment]
Temporarily assign to self

**Comment by etiennedi** [comment]
I never knew this issue existed, I actually opened (and fixed) a very similiar at some point, so this is definitely resolved (#800). Closing.
