### ISSUE TITLE
Require root key for GraphQL endpoint

### ISSUE THREAD

**Issue by moretea** [semi-technologies/weaviate#457]
We are  not sure how keys and the network queries will interact.

To not do more work than is necessary (#453), we'll require a root key to use the GraphQL endpoint for now, since it'll have access to all data.

- [ ] Add root key check
- [ ] Update documentation about GraphQL endpoint.

**Comment by bobvanluijt** [comment]
Is this still relevant @moretea?

**Comment by etiennedi** [comment]
Obsolete as key auth has been replaced by auth plugins (mostly OIDC in the wild).
