### ISSUE TITLE
Safe mode

### ISSUE THREAD

**Issue by moretea** [semi-technologies/weaviate#520]
This feature introduces a 'safe mode', in which the users of a Weaviate instance can *only* modify the schema.

The safe mode is entered when:
1. A weaviate cluster is starting
2. The schema is not semantically grounded.  This means that the names from the local ontology are not grounded in the contextionary. To be precise, these names are the the class names/keywords, and the property names/keywords.

Network and local operations will be disabled until the schema is semantically grounded.

In the safe mode, a 500 error (internal service error) will be returned on all non-schema requests, with a body explaining the service mode, and the ungrounded class/property names/keywords.

Note: This does _not_ apply to schema operations that would add e.g. a class with a bogus word that is not grounded in the contextionary. Those operations will not be accepted.

This implementation issue replaces the discussion in gh-517.

**Comment by bobvanluijt** [comment]
Yes, agreed. I'll take care of this in the documentation.

**Comment by bobvanluijt** [comment]
Quick question regarding nomenclature for the docs, is the following correct;

- `operation mode` = the way a Weaviate operates.
- `safe mode` = only the schema endpoint is available.
- `fully operational mode` = full Weaviate.

**Comment by moretea** [comment]
Yep.

**Comment by bobvanluijt** [comment]
What is the current status of this feature branch @moretea?

**Comment by etiennedi** [comment]
Obsolete as this idea was tied closly to the idea of the connector which is no longer part of the strategy starting with `0.20.0`. Closing.
