### ISSUE TITLE
Wrong schemas loaded in prototype?

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#527]
Note [line 894](https://github.com/creativesoftwarefdn/weaviate/blob/feature/travis-docs/graphqlapi/prototype/prototype-server.js#L894)

```js
var actionsFile = './network/' + weaviate + '/things_schema.json';
```

Should this not be `/actions_schema.json`?

Changing it makes the prototype fail.

**Comment by etiennedi** [comment]
Obsolete, as prototype has been deprecated. Closing.
