### ISSUE TITLE
Update schemas in graphql prototype

### ISSUE THREAD

**Issue by laura-ham** [semi-technologies/weaviate#551]
Four actions are required:

- [x] Delete superfluous schemas
- [x] Add schema's to run the examples in the documentation
- [x] Add schema options to arguments of the script
- [x] Document how to use the prototype with arguments for different schemas in dev docs

**Comment by laura-ham** [comment]
@bobvanluijt and/or @moretea, is there a reason to keep all the test schema's in the prototype? If not I will throw them out. 
According to @JeroenStravers1 I can delete them since he's using a different source for testschemas.

**Comment by bobvanluijt** [comment]
If @JeroenStravers1 doesn't need them you can remove them. Please note that you could even go as far as using [these](https://github.com/creativesoftwarefdn/weaviate/tree/develop/tools/dev/schema) in the prototype.

So you would have;
- Test schema
- Bigger schema for readability.

PS:
Please also check with Dominique if he isn't using them.

**Comment by etiennedi** [comment]
Closing as prototype has been deprecated.
