### ISSUE TITLE
Disallow dropping Classes that are referenced in the schema

### ISSUE THREAD

**Issue by moretea** [semi-technologies/weaviate#556]

**Comment by bobvanluijt** [comment]
Is this still relevant @moretea? 

Temporarily assigning this to @etiennedi depending on the answer.

**Comment by etiennedi** [comment]
This sounds worth keeping. I need to research a bit what the implication is of deleting a referenced class, but I assume it's rather catastrophic ... so some sort of protection sounds good

cc @laura-ham

**Comment by bobvanluijt** [comment]
Relevant but trivial
