### ISSUE TITLE
Add additional type Text

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#586]
A new type needs to be added which is called `text` for things and actions.

Text properties;
- `Text` is stored as a string but _not_ indexed.
- `Text` should not be searchable in GraphQL. For example in a where clause, if the path contains a `text` value it should not be processed.

Todo:
- [x] @laura-ham, add above-mentioned behavior to the prototype.
- [x] @JeroenStravers1,  implement Laura's implementation.
- [ ] @JeroenStravers1, handle filtering. If -for example- in a [`Get{}` clause](https://github.com/creativesoftwarefdn/weaviate/blob/develop/docs/en/use/graphql_filters_local.md)  the type `text` is used, respond with an error that texts are not searchable.
- [ ] @moretea, add the functionality as mentioned above, behavior can be the same as a string with the exception that the content is _not_ indexed.

An example in ontology: https://github.com/creativesoftwarefdn/weaviate/blob/develop/docs/en/use/ontology-schema.md

**Comment by bobvanluijt** [comment]
cc: @etiennedi for your test script ⬆️

**Comment by etiennedi** [comment]
Someone ping me please once this is implemented in weaviate itself, I can easily add this to the verification script then. - Don't think it makes sense to do it in parallel as it'll just fail all the time until the field is ready.

**Comment by etiennedi** [comment]
This is complete and the meaning of text has changed a bit with `0.20.0`.
