### ISSUE TITLE
DataTypeText not implemented in JanusGraph code

### ISSUE THREAD

**Issue by JeroenStravers1** [semi-technologies/weaviate#624]
## Background
I kept getting errors at the `DataType Text` property when implementing this property option (when running `tools/schema_loader/schema_loader.go`). I traced this error to `database/connectors/janusgraph`; `DataTypeText` handling was not yet implemented there. 

## Current situation
`DataTypeText` uses the same code as `DataTypeString` in GraphQL, so I implemented `DataTypeText` in the JanusGraph connector by copying the code for strings. This is not a stable or safe solution (I lack the relevant expertise), but running the `schema_loader.go` script works now.

## Proposed fix
Have someone with knowledge of JanusGraph and filter resolving look at my fix.

I edited the following files:
- `database/connector/janusgraph/resolverget`
- `database/connector/janusgraph/migrator`
- `database/connector/janusgraph/helper`

**Comment by bobvanluijt** [comment]
Hi @JeroenStravers1, can you please add the commit where these files are changed?

The _only_ difference with a string is that they are not indexed, so that's fine for now.

**Comment by JeroenStravers1** [comment]
If I remember correctly we should also return an error when DataTypeText is used in a filter. This error throwing should be implemented in the JanusGraph code, where the filters are interpreted. Using a Text property in a filter is currently perfectly legal.

**Comment by etiennedi** [comment]
> This error throwing should be implemented in the JanusGraph code

I'm not so sure about this. I think it's business logic, rather than database logic. On a business (API) level, we already say that text can never be indexed and used as a filter. So we can already validate this when parsing the filters. This way it only has to be done once as opposed to in every database connector out there.

**Comment by etiennedi** [comment]
Obosolete since 0.20.0, closing.
