### ISSUE TITLE
Create mapping endpoint to visualise the network

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#625]
- Create new `/tools/maps` endpoint.
- Show map data from: `zero point position`, `center of self`, `center of other`, `center of concept`.

Results should include:
- Location of concepts.
- things and actions.
- distance to benchmark point.

**Comment by etiennedi** [comment]
Closing as this doesn't seem a pressing issue. Feel free to reopen once this becomes relevant again.
