### ISSUE TITLE
Rename GraphQL filter typenames

### ISSUE THREAD

**Issue by dljcollette** [semi-technologies/weaviate#671]
@laura-ham The typenames for the filter `where` objects are specific to a class, however, the properties of the object seem to be generic. Is this done op purpose? Would it make more sense to either make the typenames generic (more flexibility) or the properties specific to the class (better type safety)?

**Comment by dljcollette** [comment]
Sure! For example, when looking at `BuyAction` and `Flight` action in the GraphQL schema, they have their typenames for the `where` field defined as `WeaviateLocalGetActionsBuyActionWhereInpObj` and `WeaviateLocalGetActionsFlightWhereInpObj`. However, the properties of these objects are equal:
```
path: [String]
Specify the path from the Things or Actions fields to the property name (e.g. ['Things', 'City', 'population'] leads to the 'population' property of a 'City' object)

valueInt: Int
Specify an Integer value that the target property will be compared to

operands: [WeaviateLocalGetActionsFlightWhereOperandsInpObj]
Contains the Operands that can be applied to a 'where' filter

operator: WeaviateLocalGetActionsFlightWhereOperatorEnum
Contains the Operators that can be applied to a 'where' filter

valueDate: String
Specify a String value that the target property will be compared to

valueBoolean: Boolean
Specify a Boolean value that the target property will be compared to

valueString: String
Specify a String value that the target property will be compared to

valueText: String
Specify a Text value that the target property will be compared to

valueNumber: Float
Specify a Float value that the target property will be compared to
```

**Comment by JeroenStravers1** [comment]
True, I had to change the names for the where, operator and operands elements to keep a pre-existing test from failing. They were generic before. 

I'm fine with renaming the other properties (valueX) to something more specific, but making the names for where, operator and operands generic won't work.

**Comment by bobvanluijt** [comment]
Please do so @JeroenStravers1 but also align with @laura-ham (for the prototype) and @etiennedi (for potential impact on the implementation).

**Comment by etiennedi** [comment]
Assuming this is obsolete. Closing.
