### ISSUE TITLE
Add healthcheck endpoint(s) to Weaviate

### ISSUE THREAD

**Issue by idcrosby** [semi-technologies/weaviate#674]
Weaviate should have a simple healthcheck endpoint which external platforms (e.g. Kubernetes) can use to determine when the application is healthy and ready to receive traffic.

**Comment by etiennedi** [comment]
Proposal:
* `/.well-known/live` -> 204 as soon as the API is able to handle any request
* `/.well-known/ready` -> 204 when startup routines have completed successfully

*Question*: Should we check whether the backing db is reachable as part of the readiness checks?
*Pro*: there's no point in operating weaviate without a backing db. So let's say a new version somehow destroys the db-connector, it would never receive traffic in a rolling-update scenario
*Con*: Not really isolated from the external dependency (12-factor). If the db is not available but weaviate is up, we can at least return meaningful error messages, whereas all pods in unready state would lead to not very meaningful responses from the k8s svc or ingress-controller

I'm leaning towards readiness should not depend on db health.... what do you think?

**Comment by idcrosby** [comment]
@etiennedi very good question. As you point out, in terms of best practices we should not rely on downstream dependencies for health checks, risks of cascading failures, etc. However in a scenario where we have multiple instances running and one (for whatever reason) cannot connect to the db, it would be nice to avoid sending it traffic.

So I could see an argument for both cases, but I agree with you in preferring the solution where it does not depend on db health. We will need some good monitoring in place to be able to catch these scenarios.

**Comment by etiennedi** [comment]
We still need this. Need to prioritize this.
