### ISSUE TITLE
Set correct hostname in /meta endpoint

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#676]
On the Weaviate `/meta` endpoint.  The hostname should be formatted as: `weaviate+[SCHEMA]://[NAME]`. For example: `weaviate+http://weaviate-b`.

This is needed to determine what the name of the host Weaviate is, for example during importing.

**Comment by etiennedi** [comment]
Closing as 
> This is needed to determine what the name of the host Weaviate is, for example during importing.

doesn't seem to be an issue in all our automated importing scripts.

Feel free to reopen if this becomes critical (again).
