### ISSUE TITLE
Refactor restapi package: Split up into subpackages and improve handling of app-wide state

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#723]
There are two major problems with this package:
* It's way to big and touches upon many concerns that can be decoupled very well by using subpackages, similar to how we've done this for [the new batch api](https://github.com/creativesoftwarefdn/weaviate/tree/a4340b5b3ea8b1d2770b316509367bc4cc5f96e6/restapi/batch)
* There are package-wide global variables everywhere and it's impossible to deduce the correct data flow. A first step towards at least grouping what is application-wide state has been done for the `batch` feature/package as well, see: https://github.com/creativesoftwarefdn/weaviate/blob/ad43baf230ac24dbd5af1ca572242ae73ad999ef/restapi/state/state.go#L20-L27
  Ideally we could group stuff further into a custom type to make sure we don't have sooo many package-wide global vars.

**Comment by bobvanluijt** [comment]
Please bear in mind the role of the `weaviate_config.go` file. You want to always keep that one for go-swagger.

**Comment by etiennedi** [comment]
Do you mean `configure_weaviate.go`? That's fine it'll be what ties the subpackages together in the end. That's already how it's done for the new batch subpackage as well.

See

https://github.com/creativesoftwarefdn/weaviate/blob/ad43baf230ac24dbd5af1ca572242ae73ad999ef/restapi/configure_weaviate.go#L205

and

https://github.com/creativesoftwarefdn/weaviate/blob/ad43baf230ac24dbd5af1ca572242ae73ad999ef/restapi/configure_weaviate.go#L419-L423

**Comment by bobvanluijt** [comment]
👌

**Comment by etiennedi** [comment]
Closing as complete.
