### ISSUE TITLE
Local cache of schema state means horizontal replicas are out of sync after a schema change

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#725]
The schema state is no longer managed in `weaviate` itself, but in `etcd`. However, there seems to be a local cache of the schema state as well, because changes aren't immediately propagated to other instances.

## Solution
fix this

## Workaround Alternative 1:
1. Scale weaviate to 1 replica
2. Make schema changes
3. Scale weaviate up to desired no. of replicas

## Workaround Alternative 2:
1. Scale weaviate to desired no of replicas immediately
2. Make schema changes
3. Delete all pods and wait for them to come up again

**Comment by etiennedi** [comment]
An easy fix could be to just watch the key and invalidate the cache if it changes, as described in here: https://godoc.org/github.com/coreos/etcd/clientv3#example-Watcher--Watch

**Comment by etiennedi** [comment]
Still relevant. @fefi42 did you ever run into this issue in the wild? Or did we not have the need to horizontally scale the weaviate pods yet?

**Comment by fefi42** [comment]
I did not scale weaviate pods yet.

**Comment by etiennedi** [comment]
Still relevant for as long as we have etcd, i.e. probably 1.0.0
