### ISSUE TITLE
Remove Graphiql from Weaviate

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#727]
Can now directly be used from the Playground.

**Comment by etiennedi** [comment]
Closing as completed.

**Comment by mingfang** [comment]
can you please revert this and put Graphiql back?
Without Graphiql I had to run Hasura just so that I can query Weaviate.

**Comment by bobvanluijt** [comment]
Hi @mingfang – you can actually do this via the [Weaviate Console](https://console.semi.technology) without logging in. You don't need the Graphiql end-point.

If we can improve this in the docs, just let me know

**Comment by mingfang** [comment]
Yes I'm aware of the Weaviate Console, but due to the security in our network, we can not use an external cloud based tool.
We only have access to services running inside our network.
It would be great if the Console can come as part of the core weaviate service, like Graphiql was.

**Comment by bobvanluijt** [comment]
Hi @mingfang – that shouldn't be an issue. As long as your machine is available to connect to the Weaviate instance, you can use the console. There is 0 cloud interaction involved. The browser directly connects to Weaviate :)
