### ISSUE TITLE
Add sentence context logic to Contextionary

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#728]
Sentence context is built on top of the Contextionary's `ComputeCentroid()` function.

- Update the generator to generate a word occurrence CBOR file.
- The sentence is split per word creating a `Vector{}` array.
- Weights are determined on the occurrence of the word (Contextionary needs to be extended with word count vocab file to determine how often a word appears).
- Add to contribute docs

**Comment by etiennedi** [comment]
Closing as complete. Was implemented in the c11y microservice, as well as in #947 for the `c11y` endpoint.
