### ISSUE TITLE
Extract contextionary into separate microservice

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#730]
## Why?
* so we can deploy weaviate without including the contextionary
* so we can scale weaviate independent of the contextionary

## Proposed architecture
see https://github.com/creativesoftwarefdn/weaviate/issues/730#issuecomment-467892860

**Comment by bobvanluijt** [comment]
Curious to know how you are thinking of having the microservice exposing the Contextionary. Do you mean as (simple as) a cross container download or something more sophisticated?

**Comment by etiennedi** [comment]
Slightly more sophisticated. If we do a cross-container download, we'd have the same coupling regarding scaling: Every weaviate container would need to download it at startup. Even though this is much faster than downloading from the internet, it would still delay startup. Additionally each container would then need to keep it either in the file system or in memory, which takes unnecessary resources.

So my idea is to have "contextionary as a service" with two goals:
- The current `contextionary` package becomes it's own microsoervice
- They scale entirely independently
- From a weaviate DX perspective you don't really notice that the contextionary is not part of itself anymore. To achieve this, see proposal below:

I think the simplest option would be a very small grpc interface in the contextionary microservice (like so https://grpc.io/docs/tutorials/basic/go.html#simple-rpc) From weaviate it would feel like calling a local method, but it would actually be a grpc network call.

**Comment by bobvanluijt** [comment]
Interesting, but would make Weaviate depend on Docker?

**Comment by etiennedi** [comment]
No, the contextionary could of course also be its own VM, bare metal server or just run in a different process on the same machine. There's nothing docker-specific about it. It's just decoupling of concerns, the same way that janus is its own microservice, cassandra is its own service, etc.

Weaviate is at the verge of becoming a big monolithic application (this is creating issues for us, for example the ones we want to fix in the original post), so it's only natural to start extracting stuff out into independent microservices.

This all assumes that we want to build a microservice application of course, and not a monolith. However, running a monolith in the cloud is much, much more complicated, then running a microservice setup. So, I'm strongly in favor of a microservice architecture.

**Comment by etiennedi** [comment]
I did a small investigation yesterday of what is required and to get an understanding of how big or small the change would be.

## Architecture
### Current
Currently the Contextionary exists in the following places
* `contextionary`: The library package that describes the core contextionary
* `database/schema_contextionary`: which is basically an extension of the contextionary, enriched with schema class and property centroids
* the raw contextionary is enriched which schema classes upon schema change in the `restapi` package
* this constantly updated contextionary is passed to 
  * the graphql api for SchemaSearches on `Local Fetch`
  * the `database/schema_manager` has its own validation and uses the contextionary to check if class/prop names are present.

## Proposed
* Both library and the enriched schema contextionary move to a separate service
* For current usage this service has to expose only two gRPC methods via a simple contextionary client:
  * `WordPresent(Word) bool` -> to be used in validation
  * `SchemaSearch(Word) WordList` -> to be used in Local Fetch
* Additionally the contextionary needs to add newly added schema classes and props on change. For this it can simply watch the `etcd` key containing the schema.

**Comment by bobvanluijt** [comment]
Just to make sure, if we make changes to the contextionary we can do this directly in the new contextionary repo, right?

**Comment by etiennedi** [comment]
Correct, they won't be usable yet in weaviate, but we're only about a day's worth of work away from using the extracted contextionary there (I don't have this currently prioritized - in favor of Spark - but can do this at any time if you need it.)

**Comment by bobvanluijt** [comment]
Cool, thanks.

**Comment by Krijger** [comment]
I'm curious. If you would want to update the contextionary while running Weaviate. Would that work? How would it look?

This question is of course about a production situation, not the development docker-compose setup (although with volume mounted contextionary files, this may still be interesting).

**Comment by etiennedi** [comment]
@Krijger I'll answer this in two ways for the setup prior to the proposal outlined in here and after:

## Current Setup (contextionary part of weaviate)
Right now, weaviate builds an in-memory representation (technically a memory-mapped file) at startup. So if you were to change the contextionary files, you'd have to trigger a restart. If zero-downtime is a concern, then you have to run weaviate in a HA-fashion (i.e. at least 3 horizontal replicas). You could then trigger a rolling-restart. However the update would not be atomic. I can't imagine a situation where an atomic update of the contextionary would be necessary, though.

(I'm assuming a Kubernetes production setup, let me know if this is incorrect) As you correctly pointed out, in order to change the contextionary of a running pod, you'd have to provide it form the outside through a volume mounted to the pod. 

So the process would be: 

1. First add the new files in the volume. In order for this to be non-breaking, don't replace them, but add them side-by-side. 
1. Then change the config maps to point to the new files. 
1. Finally trigger a rolling restart for weaviate to actually make use of the new files. 
1. It is now safe to delete the old files from the volume

## With the contextionary as a separate service (i.e. after this issue)
WIth the new setup there are more flexible options. For example you could deploy the old and new contextionary along-side each other and independently of weaviate validate that they are usable. If you are sure, the new version works, simply update the weaviate configuration url to point to the new contextionary. (Right now configuration is only parsed at startup, so you'd still need a rolling-restart in this scenario, however, that's something that could easily be changed as part of #800)

**Comment by Krijger** [comment]
O, it appears the life cycle of the contextionary is even more complicated. I now read

> Because all nodes on the network use the same contextionary, Weaviates can interact with each other based on the context determined by the contextionary.

[here](https://github.com/creativesoftwarefdn/weaviate/blob/master/docs/en/contribute/contextionary.md). Up to you if this makes my previous question invalid, or more interesting :)

**Comment by etiennedi** [comment]
> Up to you if this makes my previous question invalid, or more interesting :)

Definitely not invalid and surely a bit more interesting: This is right now a very theoretical case. The exact network design specifications might change based on usage metrics and user feedback. There are many solutions to the distributed network problem, though, each come with their own drawbacks. For example:

- Coordinated Updates. This makes sense if the entire Network is owned by one Party. They could run a maximum of two versions side-by-side and require that all peers update to the newer of the version within a specified time frame

- The above is still possible even if the network is more distributed. Then (at least in the current implementation) there is a coordinating component: The Keyper (previously "Genesis"), which can simply send warnings to peers that their contextionary version is considered depracted and ultimately kick them out of the network.

- If a network has very rapidly changing contextionaries, there could be a trade-off to centralize the contextionary and have each peer be agnostic about the version currently in use (Note this will only be possible after this issue is completed). The cost of this is that each contextionary request will be a call to the central instance. So if this central instance is "far away" (in network hops) from the peers, this could lead to delays. This could in turn be mitigated with caching.

- There are other possible solutions that might make sense to the specific problems once we encouter them. :)

**Comment by etiennedi** [comment]
Closing as complete, not sure why this one stayed open, probably forgot to reference it in the PR.
