### ISSUE TITLE
PROPOSAL: rename dataType to dataFormat and use dataFormat as format

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#743]
Currently, we use: "Data Type and Data Formatting" as defined [here](https://github.com/creativesoftwarefdn/weaviate/blob/develop/docs/en/use/ontology-schema.md#property-datatypes).

However, in the ontology definition, we use: `@dataType` but I think this should be `@dataFormat`. Where the data type defines _how_ something is stored and the format _what_ is stored.

Also see: https://github.com/creativesoftwarefdn/weaviate/issues/729#issuecomment-467774557

Proposal:
1. Be more strict about using `dataType` and `dataFormat`.
2. Have users _only_ use `dataFormat`.
3. Rename `dataType` to `dataFormat` in the ontology definition.

**Comment by etiennedi** [comment]
Are the proposals alternatives or individual steps of one proposal?

**Comment by etiennedi** [comment]
Even though I'm not in favor of increasing the scope for `v1.0.0`. This sounds like something that would be quite breaking to change it later. So we should probably tackle this before major 1.

**Comment by laura-ham** [comment]
The "`dataTypes`" are distinct from each other in their format and not in type (e.g. string and date are both of type `string`, but formatted differently), as you mention [here](https://github.com/creativesoftwarefdn/weaviate/blob/develop/docs/en/use/ontology-schema.md#property-datatypes). 

So yes, I agree that the correct name for this would be `@dataFormat`.
