### ISSUE TITLE
Add unit of distance to WithinGeoRange filter (on geoCoordinates)

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#746]
Currently, the distance is always in kilometers.

The user should be able to choose the type of distance;
- Fathoms
- Feet
- Furlongs
- Meters
- Miles 
- Nautical Miles
- Yards

**Comment by etiennedi** [comment]
Planned for after MVP phase, correct?

**Comment by bobvanluijt** [comment]
Yes
