### ISSUE TITLE
Release process / Use semantic versioning in docker tags

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#753]
Update: Tackling the tagging strategy is closely aligned with managing releases. See the current proposal in https://github.com/creativesoftwarefdn/weaviate/issues/753#issuecomment-469691969

## Current problem
Currently we are doing a few anti-patterns in tagging our containers:

* We are over-writing the same tag on subsequent builds (i.e. either `unstable` or `stable`)
* There is no clear way to determine which version build a specific tag

This leads to several problems:
* We have no way of knowing which version is currently used in a production setting
* Updates are very cumbersome because users have to make sure they actually re-download an image that their docker daemon tells them they already have present.
* Coordination is required if changes are breaking.

## Proposal

Use proper semantic versioning in docker tags and remove `"stable"` or `"unstable"` tags:

- E.g.`creativesoftwarefdn/weaviate:0.1.0-e6c913b` to replace unstable
- E.g.`creativesoftwarefdn/weaviate:0.1.0` to replace stable (only created on releases)

The unstable option would be compatible with semantic versioning:
> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes. Pre-release versions have a lower precedence than the associated normal version. *A pre-release version indicates that the version is unstable* and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92. 

[Source](https://semver.org/)

**Comment by bobvanluijt** [comment]
Some questions;
- would we keep the master and develop branch? Master == stable and develop would == unstable? If not, how would the flow work to determine stable or unstable?
- we should auto update the docs, right?

**Comment by etiennedi** [comment]
@bobvanluijt 
> would we keep the master and develop branch? Master == stable and develop would == unstable? If not, how would the flow work to determine stable or unstable

Currently I could see the following working:
* Remove the differentiation between `develop` and `master`
* No auto-bump happens on merge
* Every merged PR will automatically be pusehd as `<previousSemVer>-gitHash` (formerly unstable)
* We manually create a `git tag` when we want to release. This tag will be next semver version and a human (not a script) has to decide whether it's a patch/minor/major bump. I think keeping this process manual makes sense, because we also want to write release notes, take strategic timing into account, etc. Basically I see deployment as a tech process that should entirely be automated, but see releases as a business process, that should involve a human (at least at the moment)
* Whenever a new tag is pushed (i.e. an official release), we push a docker image that follows the stable convention, i.e. `:x.x.x` without the suffix. Additionally we can tag this as `:latest` if we want too.
* If we want to we can also create a release branch for each tag. This would make hot-fixing previous releases easier. However, since we're still below major v1, I'm fine with only supporting a single version at the moment. I.e. if a user needs a patch, they have to upgrade to whatever the latest is at the moment. (This would be a somewhat arrogant attitude with a major >= 1, but I think for the current state this is fair - We simply don't have the capcity to support more than one version at the moment).

This is a setup I've used before and I think it would be very helpful for our setup as well. @idcrosby Very happy to hear your thoughts on this as well. If we can improve it, very happy to hear your input. Does it reflect best practices around releasing, continuous delivery, etc.?

> we should auto update the docs, right?

Can you elaborate what you mean by that?

**Comment by bobvanluijt** [comment]
Can you confirm that we;
- remove master completely (develop = default branch already).
- autobumps happens _except_ when PR or merge in develop.
- the pre-release (with gitHash) happens automatically when in develop.
- we tag and release (without gitHash) manually.

About the docs, if we _don’t_ use something like `:latest` the docs need to be updated manually.

**Comment by etiennedi** [comment]
> * remove master completely (develop = default branch already)

I'd prefer to merge everything into `master` once. Make this the default and keep that one around. Simply because `master` is the most intuitive name for a trunk branch. If that is too much effort though, your proposal should also work. I guess we can always rename it in the future.

> * autobumps happens except when PR or merge in develop.

What would we auto-bump? Every time we change the major/minor/patch an actual release (manual) needs to happen, otherwise from a users perspective we'd be skipping versions.

And for the pre-release (which is the same major/minor/patch) we don't need to bump anything?

> * the pre-release (with gitHash) happens automatically when in develop.

Agreed.

> * we tag and release (without gitHash) manually.

Agreed.

**Comment by bobvanluijt** [comment]
Thank @etiennedi.

Per open bullets;
1. I would suggest "removing master", "rename develop to master" instead of releasing in master and remove develop. I'm worried we might break the Merkle tree.
2. I see, completely clear. Nothing happens regarding versions in feature branches.

One thing though, we now not use `feature/*` always when working on features. I would really like to have this in though. It makes it more clear what is happening.

**Comment by etiennedi** [comment]
1. fine with me :)

> One thing though, we now not use feature/* always when working on features. I would really like to have this in though. It makes it more clear what is happening.

Agreed. This is essentially the [GitHub Flow](https://help.github.com/en/articles/github-flow#following-the-github-flow) which is a form of trunk-based development in my mind. 

I also like the distinction between `feature/*` and `bugfix/*` in branch names. 

We also have a huge amount of branches that were never merged (and thus deleted). We might use this opportunity to delete some of them as well. My gut feeling would be that most of them aren't needed anymore.

**Comment by bobvanluijt** [comment]
True, I'm all for also including `bugfix/*`. It is more that I would like to have it organized :-P

I'm going to experiment in an empty temporary repo with this.

**Comment by bobvanluijt** [comment]
With the latest updates, there is one last issue and that sits in the running-weaviate docs.

What would be the easiest to indicate:
- This is how you get the latest release?
- This is how you get the latest pre-release?

Would this be as simple as automatically update the docs? Or am I missing a more appropriate solution @etiennedi?

**Comment by etiennedi** [comment]
My pragmatic suggestion would be
> This is how you get the latest release?

Let's also tag the regular releases as `:latest` and reference `:latest` in the docs

> This is how you get the latest pre-release?

Let's make releases frequent enough that users don't see a reason to get a pre-release. If they really have to for whatever reason they could still manually check the build logs what the latest tag was.

**Comment by etiennedi** [comment]
Closing as complete (see PR #771)
