### ISSUE TITLE
Adding crefs via /things/{thingId}/references/{refName} doesn't work

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#756]
Adding CREFS following the following curl works perfectly fine;

```bash
$ curl -X PATCH http://localhost:8080/weaviate/v1/things/3c6ac167-d7e5-4479-a726-8341b9113e40 -H "Content-Type: application/json" -d '[
  {
    "op": "add",
    "path": "/schema/hasAnimals",
    "value": [
      {
        "$cref": "weaviate://localhost/things/ac19c17b-63df-4d6f-9015-9086bb3466c4"
      },
      {
        "$cref": "weaviate://localhost/things/82f91e01-37b4-431c-98d1-43ebb48bca0f"
      }
    ]
  }
]'
```

However, the equivalent with `/things/{thingId}/properties/{propertyName}` doesn't work;

```bash
$ curl -X POST http://localhost:8080/weaviate/v1/things/3c6ac167-d7e5-4479-a726-8341b9113e40 -H "Content-Type: application/json" -d '[
      {
        "$cref": "weaviate://localhost/things/ac19c17b-63df-4d6f-9015-9086bb3466c4"
      },
      {
        "$cref": "weaviate://localhost/things/82f91e01-37b4-431c-98d1-43ebb48bca0f"
      }
    ]'
```

Results in: `{"error":[{"message":"Illegal value for property inCity"}]}`

PS:
I did not validate `/Actions` but I'll assume the behavior will be similar.

**Comment by etiennedi** [comment]
@bobvanluijt I just noticed that you are trying to add two resources at the same time with `POST`. That's not possible, `POST` must add exactly one resource (the resource being the cross-ref in this case). Did you try adding them one at a time? Might be that it works as intended, just the error message is bad?

**Comment by bobvanluijt** [comment]
No, I did not try that. But if that would work, wouldn’t the array input be a bit misleading?

**Comment by etiennedi** [comment]
Definitely, let me check if that is actually the case.

**Comment by etiennedi** [comment]
According to the swagger docs this endpoint takes a single object: 

![image](https://user-images.githubusercontent.com/8974479/56115235-3f4e2e00-5f63-11e9-9736-4a01cfef0dc2.png)

Is it possible you actually tried the `PUT` endpoint which does take an array?

**Comment by bobvanluijt** [comment]
Hi @etiennedi, still validated that this is still an issue.

Some more info, this _only_ happens when the cardinality is set to `many`.

**Comment by etiennedi** [comment]
Changed the title to rename `properties` to `references` as this issues was originally opened, before the change was applied in #826.

**Comment by etiennedi** [comment]
The issue is fixed, as can be seen through this (now green) acceptance test which recreates this issue: https://github.com/semi-technologies/weaviate/blob/ea4221b0370a9e25ebe62b36aa705098b9750dab/test/acceptance/things/crefs_cardinality_many_test.go#L156-L271

**Comment by bobvanluijt** [comment]
Awesome, thanks @etiennedi
