### ISSUE TITLE
Resolve automatically in GraphQL when @dataType length == 1

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#757]
When adding a Thing or Action we define the `@dataType` like this:

```json
{
    "class": "Animal",
    "keywords": [
        {
            "keyword": "beast",
            "weight": 0.01
        }
    ],
    "description": "Animals",
    "properties": [
        {
            "@dataType": [
                "string"
            ],
            "description": "Name of the Animal",
            "name": "name",
            "keywords": [
                {
                    "keyword": "identifier",
                    "weight": 0.01
                }
            ]
        },
        {
            "@dataType": [
                "ZooKeeper"
            ],
            "cardinality": "many",
            "description": "People that take care of the Animals",
            "name": "hasZookeepers",
            "keywords": []
        }
    ]
}
```

To query the above with GQL I need to do this:

```graphql
{
  Local{
    Get{
      Things{
        Animal {
          hasZookeepers{
            ... on ZooKeeper {
              name
            }
          }
        }
      }
    }
  }
}
```

But if the amount of `@dataType`'s == 1, we can allready resolve _without_ using the `... on ZooKeeper` functionality.

For example:

```graphql
{
  Local{
    Get{
      Things{
        Animal {
          hasZookeepers{
            name
          }
        }
      }
    }
  }
}
```

# Proposal

Automatically resolve the type in GraphQL when the count of `@dataType`'s == 1.

**Comment by etiennedi** [comment]
> Automatically resolve the type in GraphQL when the count of @dataType's == 1.

I think this would actually make UX worse. This would mean if we start out with a schema where the count of `@dataType` is 1 and then we update this at some point in the future to include a second type, all existing queries would break.

**Comment by laura-ham** [comment]
I agree with @etiennedi 's argument. Also, keeping `... on <classname>` as in the current design means that it is consistent for all properties that have datatype of one or more cross references.

**Comment by etiennedi** [comment]
While we discarded this original proposal for the reasons of a consistent API (see two posts above), a similar requests has been made by a user.

I tried to find a middleground in this post here: https://github.com/semi-technologies/weaviate/issues/972#issuecomment-539017441

@bobvanluijt @laura-ham @fefi42 Happy to hear your feedback on the above.

Keeping this one open in the meantime.

**Comment by fefi42** [comment]
If we implement this then I would not make it the default behavior.

**Comment by etiennedi** [comment]
Closing as stale, feel free to reopen.
