### ISSUE TITLE
Travis fails when trying to download mods for license checker

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#768]
High priority, since this is blocking (pre-)releases.

See https://travis-ci.org/creativesoftwarefdn/weaviate/builds/503127274#L2712-L2754

**Comment by etiennedi** [comment]
License checker has been deactivated temporarily, to unblock the release path.

**Comment by bobvanluijt** [comment]
Check @etiennedi, I've assigned this one to myself to solve later.

**Comment by etiennedi** [comment]
> Check @etiennedi, I've assigned this one to myself to solve later.

Any update on this? @bobvanluijt

**Comment by bobvanluijt** [comment]
Nope, is this still an issue though?
