### ISSUE TITLE
Sentence to Contextionary array

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#770]
Add sentence functionality to the Contextionary;

1. [ ] Sentence to C11y array.
2. [ ] Sentence to sentence distance.
3. [ ] Create a weighted centroid of a sentence.
4. [ ] Concept to sentence functionality.

Notes:
- _WIP: I will add detailed workings to the docs directly rather than the issue._
- @etiennedi FYI: this is related to the new functionality @laura-ham and myself are designing.

**Comment by etiennedi** [comment]
Hello @bobvanluijt and @laura-ham,

as mentioned in #730 I want to extract the contextionary to a separate service. I'm just seeing if I can get a development environment up quickly. This will serve two purposes:

* Anything you add (while I'm moving) we don't have to sync, but you could just add it to the new repo already
* You have a dev environment which is completely decoupled from weaviate. You could easily try out your new functionality from unit tests without having to run a full weaviate.

No guaranteees though, I don't how big of a process this, I'll keep you updated.

**Comment by etiennedi** [comment]
@bobvanluijt @laura-ham 

Success!

I've ported over the contextionary to https://github.com/creativesoftwarefdn/contextionary/tree/master/contextionary/core

Additionally, I've added a sample test file for you in which you can use a full contextionary: https://github.com/creativesoftwarefdn/contextionary/blob/6a65a62eeb0197421c9df8f218bbe4c3a2b85cfa/contextionary/core/component_test.go#L10-L24

Notice that I've added a build flag `sentence`, make sure you reference this when running your tests like so:
```bash
go test -tags=sentence ./contextionary/core
```

This should then print something like:
```
here's the c11y, do whatever you want with it: &contextionary.mmappedIndex{word_index:(*contextionary.Wordlist)(0xc0000a3b00), knn:0x4700220}--- FAIL: TestDevelopmentEnvironmentForContextionary (0.00s)
    component_test.go:23: ... add whatever you like!
```

Have fun developing on the contextionary completely decoupled from weaviate :)

**Comment by bobvanluijt** [comment]
Thanks @etiennedi

**Comment by etiennedi** [comment]
Closing as complete. I assume the above was the first steps which initially turned into the current vector-search features with occurrence, etc. The above also mentions "sentence to sentence distance". While that is technically not an explicit feature it can still be achieved in vector searches. Thus closing as complete, feel free to reopen if this is not the case.
