### ISSUE TITLE
context for contacting etcd expires on startup on some machines

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#789]
On some machines, we currently can't start up the `./docker-compose/runtime` setup because the first request to etcd fails.

Most notably this happened when @bobvanluijt tried the docker-compose setup on a small-ish GCP VM and currently it's happening on @dljcollette's machine. 

After trying to debug the issue together with @dljcollette, here is a copy of our findings from Slack:

> We didn’t solve the problem yet, but we got a bit closer: It’s currently failing with a timeout similiar to the one you saw on a smaller GCP machine. However, I have no idea what the root cause is yet. We know the following:
> - If he runs “the dev setup”, i.e. everything in docker, but weaviate locally, all is fine and it’s super quick to start up
> - If he runs the `runtime` docker setup, the first interaction with etcd is timing out
> - While debugging we tried entering the weaviate container and manually making a connection to etcd: It’s working fine and is instant
> - We also noticed that once after about 6 minutes and once after around 4 minutes, everything suddenly started working
>
> All extremly odd, but since this is most likely the same issue that you [Bob] had on a small GCP vm, it might be worth trying to fix whatever the root cause is.

**Comment by etiennedi** [comment]
I have another idea what the problem could be: I also noticed that when using the docker setup it took quite some time until we saw the first log output. The way contexts work in Go is that they can have a timeout and at any time during an operation you can check your context whether you have enough time left to perform an operation. (Additionally you can use a channel to get a message once it is expired). So you can be actively or passively informed of a context deadline.

Most of the times this is used to notice if a network request times out. This is also why I was debugging the network connection to `etcd` all the time. However, it could also be, that in the container the startup routine simply takes so long that it never actually has any time left in the context to even make the request. This would be somewhat consistent with the fact that it takes some time until we see the first log output. Maybe the startup routine inside docker is so slow that by the time we want to make the first request to `etcd` our context has simply already expired, because the context was created immediately, but it took too long to get to the place where we want to use it.

**Comment by bobvanluijt** [comment]
Sorry for late response, missed this issue. Any progress here?

**Comment by etiennedi** [comment]
I think the proposed fix worked for most cases. Definitely seemed to have fixed the issue for @dljcollette. The only thing we need to still test is if the setup now works on much smaller GCP VMs as before. My guess would be yes. Let me know if you have some time to run a test (@bobvanluijt) otherwise I could also do that, so that we can then close this issue.

**Comment by bobvanluijt** [comment]
Just to make sure, is this with the current `:latest` version already possible?

**Comment by etiennedi** [comment]
Yes, the last tag for `:latest` was done 11 days ago, the last commit here is 20 days old. So, yes :)

**Comment by bobvanluijt** [comment]
Haha, I was confused is the solution was part of the latest PR or already is part of latest.

**Comment by etiennedi** [comment]
Ah, no, since this was blocking @dljcollette this was pushed straight to master.

**Comment by etiennedi** [comment]
Closing as fixed.
