### ISSUE TITLE
Travis (on master) incorrectly green if post-test docker build fails

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#790]
## What happened:
Due to Travis network flakiness the final `docker build` step (before the `docker push` failed). However the pipeline was still green.

## Possible reason:
Possibly missing an `|| travis terminate 1` somewhere?

## Logs:
Unfortunately I clicked "restart build" in hopes of fixing the issue, so now the logs are gone (i.e. replaced with those from the new build :( )

**Comment by bobvanluijt** [comment]
Hmm, that's weird. Can you please send the link to the Travis you mention so I can check?

**Comment by etiennedi** [comment]
Unofortunately not, because of
> Unfortunately I clicked "restart build" in hopes of fixing the issue, so now the logs are gone (i.e. replaced with those from the new build :( )

I think to reproduce this we'd have to force a docker build that fails. I think in the original attempt it failed due to network flakiness. Maybe we could recreate this on a branch. Remove the tests, make sure the docker build fails, and then see if the pipeline is green as outlined in the OP.

**Comment by etiennedi** [comment]
@bobvanluijt I ran into the situation again:

The docker build/push clearly failed (due to another error that I've fixed in the meantime):
<img width="1254" alt="Screenshot 2019-04-16 at 10 25 06" src="https://user-images.githubusercontent.com/8974479/56193976-324c4000-6032-11e9-89ae-7dfc1bcfc7b2.png">

But the build was still considered a success
<img width="1096" alt="Screenshot 2019-04-16 at 10 25 13" src="https://user-images.githubusercontent.com/8974479/56193949-1fd20680-6032-11e9-8bb2-16e65e7f09cc.png">

See: https://travis-ci.org/creativesoftwarefdn/weaviate/builds/519259851#L3838

**Comment by bobvanluijt** [comment]
Ahh, that is shitty. I've lost the context of where we are with this though...

**Comment by etiennedi** [comment]
Dont worry, I’ll address this. Just wanted to update you since you were
originally involved as well. :)


-- 
Etienne Dilocker, Inhaber
Dilocker IT

Grundwiesenweg 30a
D-67434 Neustadt an der Weinstraße

Mobil: +49 (0) 175 932 5406
etienne@dilocker.de
www.dilocker.de
https://www.xing.com/profile/Etienne_Dilocker

USt-ID-Nr: DE269867749
