### ISSUE TITLE
Improve UX when external analytics engine is used

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#809]
With #720 we introduced an MVP style way of running background analytical jobs with an external analytics engine (In the case of Janusgraph this means Spark).

**After the MVP** we want to improve the UX as outline on Slack with @laura-ham and @bobvanluijt as follows:

* [ ] Improve hashing/caching algorithm so that follow-up queries using fewer fields than a cached query can still be served from cache (right now they'd be interpreted as a new query and trigger a new run)
* [ ] Improve user feedback regarding timing
  * [ ] add "running for x minute"
  * [ ] add expected runtime based on averages of past runs
* [ ] instead of returning "job started" as an error, use an `extension`, see: https://facebook.github.io/graphql/June2018/#sec-Response-Format
* [ ] in `error` and `extension` response return objects, so information can be more easily retrieved

**Comment by bobvanluijt** [comment]
+1 for the `extension`. I could see more future use cases there.

**Comment by etiennedi** [comment]
Closing as the external analytics engine is no longer in use with 0.20.0.
