### ISSUE TITLE
add jq to the docs

### ISSUE THREAD

**Issue by rafaelcanalesduron** [semi-technologies/weaviate#815]
When preparing to run Weaviate jq is needed, but not mentioned in the docs as something to check.

Another point to consider is to make sure Docker memory is checked before running docker compose (in the preparation section perhaps) and not after if you run into issues.

**Comment by etiennedi** [comment]
Can we remove the dependency to `jq`? The point of the `docker-runtime` setup is to try it out and how weaviate comes with "batteries included". First requiring the user to install `jq` is the exact opposite of that philosophy.

**Comment by etiennedi** [comment]
Closing, as the "how to get started" section has been massively reworked in the latest iteration of the docs. Also, they're no longer in the responsibility of this repo.
