### ISSUE TITLE
PUT /schema/<kind>/<class> and PUT /schema/<kind>/<class>/properties ignore options other than name or keyword

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#832]
In #826 we made sure that the PUT handlers would have the same request body as the other fields. However, we did not yet add new implementation, so currently specifying fields other than those that previously existed have no effect.

**Comment by etiennedi** [comment]
This must also involve some heavy validation of which fields we actually want to allow to change. Changing the type would be impossible for example if there are any class instances out there already. Since this is hard to check (at scale), we'll most likely have to make `dataType` and therefore `cardinality` immutable. It should still be fine to change `name`, `keywords`, and `description` though.

**Comment by dljcollette** [comment]
Ok, I'll make sure all fields are disabled except for `name`, `keywords` and `description`. I guess the body could include all fields but just not adjust all of them?
