### ISSUE TITLE
Add test/validation stage to CI

### ISSUE THREAD

**Issue by idcrosby** [semi-technologies/weaviate#857]

**Comment by etiennedi** [comment]
To add some more details to this: What we need is a kind of smoke test. We do extensive user acceptance testing before deploying, so this test does not need to go over every single acceptance case again. Especially as some of them would depend on a specific state (such as an import schema and imported fixtures).

This test should verify that the deployment was successful (beyond a passed health check) and that a representative business transaction (comparable to a "Synthetic Transaction") can successfully be completed after the rolling update.
