### ISSUE TITLE
documentation: running latest version, first curl command requires dependency 'jq' to be installed on your system

### ISSUE THREAD

**Issue by StudioSpindle** [semi-technologies/weaviate#862]
See step: https://github.com/semi-technologies/weaviate/blob/master/docs/en/use/running-weaviate.md#running-the-latest-version

**Comment by etiennedi** [comment]
@bobvanluijt @laura-ham Has this been reflected in the docs? 

If not, please repopen a respective issue on the `semi-website` repo. Closing here as the docs are no longer in the responsibility of this repo.
