### ISSUE TITLE
Can't connect Weaviate instance to Weaviate playground (receiving panick's)

### ISSUE THREAD

**Issue by StudioSpindle** [semi-technologies/weaviate#865]
This is a follow-up on the discussion in the Slack general channel. 

The service seems to be restarting once you try to make a connection.

## Steps to reproduce:
- Installing the Weaviate Playground on your local machine [Install Manual](https://github.com/semi-technologies/weaviate-playground)
- Installing a Weaviate as described in the [docs of Weaviate](https://github.com/semi-technologies/weaviate/blob/master/docs/en/use/running-weaviate.md#attaching-to-the-log-output-of-only-weaviate)
- In the root folder for Weaviate Playground run `$ yarn start`
- In the root folder of the Weaviate instance run `$ docker-compose up -d && docker-compose logs -f weaviate`

Then wait for it to finish. To verify if it's finished correctly, try the following in a curl or browser:
- Verify whether the Weaviate is working: `http://localhost:8080/weaviate/v1/meta` <- This should show an empty Weaviate
- Then verify this URL: `http://localhost:8080/weaviate/v1/graphql` <- This should give a 405 response "method GET is not allowed, but [POST] are"

If both are true then:
- Open the Chrome browser on `http://localhost:3000/`. This opens the index page for the playground
- Then in the Weaviate URL paste: `http://localhost:8080/weaviate/v1/graphql`. 

## Here is where the error occurs.

It produces one of two things:
1. After clicking on connect immediately the error is thrown: "Network error: Failed to fetch". If you then in another tab try to open `http://localhost:8080/weaviate/v1/graphql` again that suddenly isn't working anymore.
2. Other times it starts loading the app. This hangs for quite some time. Finally it comes back and throws and  

### Debugging info:
As stated in the Weaviate documentation logs can be used to see the type of error. This is a snippet of the feedback containing the *'panicks'*:

![Screenshot 2019-05-10 at 11 58 56](https://user-images.githubusercontent.com/9882035/57566822-e1c9c780-73d0-11e9-9af3-1aae7e83bcca.png)

Docker was running:

![screenshot_2019-05-10_at_11 57 43](https://user-images.githubusercontent.com/9882035/57566826-e8f0d580-73d0-11e9-9409-d4a8abfe3892.png)

## What fixed it for me:

Using another sandboxed Weaviate URL which in the local Playground did work.

The solution was to add `127.0.0.1  weaviate001` to the hosts file on the local machine and flushing the DNS. (`$ sudo nano /etc/hosts` and `$ sudo killall -HUP mDNSResponder`. Depending on the OSX you're running this command could differ)

And then restart the docker instance (`$ docker-compose down`) and then bringing it up again (`$ docker-compose up`).

**Comment by etiennedi** [comment]
closed through #878
