### ISSUE TITLE
Incorrect error message when adding multiple crefs to atMostOne properties

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#866]
When a CREF is set to `atMostOne` but > 1 CREFs are added.

The error message is:

```json
{
    "code": 404,
    "message": "path /weaviate/v1/things/[ID]/properties/[prop] was not found"
}
```

But should be: `Can't add more than one CREF to this propery`

**Comment by etiennedi** [comment]
@bobvanluijt Could it be that the 404 is occurring not because of the incorrect cardinality, but because the endpoint was renamed from `[...]/properties/[...]` to `[...]/references/[...]`? 😉

**Comment by bobvanluijt** [comment]
Yes, correct. Was the old syntax 🐸
