### ISSUE TITLE
List endpoints not rendering in K8s setup

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#869]
After adding about 100k of things. The `/things` endpoint results in:

```json
{
    "things": []
}
```

This endpoint is used by [weaviate-cli](https://github.com/semi-technologies/weaviate-cli) to manage individual concepts, currently, this is not possible.

PS:
Waited 15 min (maybe some processing time?) but still a result of 0.

PPS:
Pointing directly to individual concepts works well.

**Comment by etiennedi** [comment]
Thanks for finding this. The k8s setup seemed to have had an incorrect configuration key for the query limit, accidentally setting the limit to `0`.

This was adressed in helm chart release: https://github.com/semi-technologies/weaviate-helm/releases/tag/v0.2.3.

The fix mentioned above has already been rolled out to all known customer K8s deployments and manually verified. Thus closing.

Additionally, please keep in mind, that the current default limit is 100. It can be overwritten on a per deployment basis. However, this is currently blocked by https://github.com/semi-technologies/weaviate-helm/issues/5. The latter should not be much work, but I'm focusing on the other blocker tickets first. If this becomes blocking, please elevate the ticket status to blocker there as well.
