### ISSUE TITLE
Rename all related to "telemetrics" to "monitoring".

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#872]
_Self descriptive_

**Comment by etiennedi** [comment]
@bobvanluijt  I'm not quite sure how to interpret the title, but it sounds as it was the opposite direction I was suggesting. My suggestion was:

* Monitoring: An operation term, classic monitoring to meassure response times, meassure error counts, meassure latencies, meassure resilience, i.e. something an Operator uses to judge whether the setup is performing well or whether they need to interfere.
* Telemetry or Telemetrics or a third term: The business feature that allows remote usage analytics which can be used for billing

I.e. the existing business feature should be renamed *to* telemetry or telemetrics.

**Comment by bobvanluijt** [comment]
Now I'm confused. The terminology _is_ already telemetrics, right?

**Comment by etiennedi** [comment]
Closing as not-in-focus at the moment. Feel free to reopen if this becomes pressing.
