### ISSUE TITLE
Suggestion: "Like" operator

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#882]
Suggestion: there is currently no `LIKE` operator. The syntax would be:

```graphql
{
  Local {
    Get {
      Things {
        Place(where: {
                path: ["name"], operator: Like,
                valueString: "Park%"}
              ) {
          name
          uuid
        }
      }
    }
  }
}
```

**Comment by etiennedi** [comment]
Good idea, I think this should be relatively easy to do. Our current Janus/C*/ES stack definitely supports something like this.

**Comment by etiennedi** [comment]
Changed the syntax from `%` to `*` as that's the more common in modern searches, e.g. Elasticsearch.
