### ISSUE TITLE
Create ability to request the issuer provider login URL

### ISSUE THREAD

**Issue by StudioSpindle** [semi-technologies/weaviate#889]
At the moment the token issuer provider URL is a manual setting in the playground. 

A local version of keycloack would for example have the URL: http://localhost:9090/auth/realms/weaviate/.well-known/openid-configuration

However, this information is already available in Weaviate. 

Would be ideal if there was an endpoint in Weaviate where you could request the token issuer URL.

**Comment by StudioSpindle** [comment]
Ideally a JSON file would come back with: `{ authorization_endpoint: string }`.

**Comment by etiennedi** [comment]
Do I understand you correctly that you wouldn't even need to consult the OIDC disovery page (`.well-known/openid-configuration`) anymore if weaviate provided you with the full `authorization_endpoint`? Or do you consume any other info from that page?

**Comment by StudioSpindle** [comment]
At the moment not. Not sure what the outcome will be of the integration of Github OAuth setup.

**Comment by etiennedi** [comment]
An alternative could also be to implement
```/weaviate/v1/.well-known/open-idconfiguration``` 
in weaviate itself and when you access the page you simply get redirected to the configured token issuers page. Then you have all the info from the OIDC discovery page in case you need other info in the future
