### ISSUE TITLE
Bug: GQL API not present after restart if no network is configured

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#890]
Seems to have missed our tests because we use a network in the tests

## Reproduce

1. Run weaviate without network
1. Import a schema
1. Verify that GQL works
1. Restart weaviate

## Expected
GQL should still work

## Actual
We get an error message that no schema is present and GQL can't be provided

**Comment by bobvanluijt** [comment]
That's some quick fixing :-)

**Comment by etiennedi** [comment]
As it should be on a blocker :)

**Comment by etiennedi** [comment]
Fixed in 0.14.3 (commit accidentally tagged with #980 instead of of #890)
