### ISSUE TITLE
Where operator _and_ not always showing the expected results

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#894]
Take the following query:

```graphql
{
  Local {
    Get {
      Things {
        Sentiment(where:{
          operator: And
          operands: [{
            operator: GreaterThan
            valueInt: 7
            path: ["score"]
          }, {
            operator:Equal
            valueString: "positive"
            path: ["emotion"]
          }, {
            operator:Equal
            valueString:"Berlin"
            path: ["HasPlaces", "Place", "InCity", "City", "name"]
          }]
        }){
          emotion
          score
          HasPlaces{
            ... on Place {
              name
              InCity{
                ... on City{
                  name
                }
              }
            }
          }
        }
      }
    }
  }
}
```

This results in _only the first result_ being from Berlin. Removing the equal operator for Berlin results in "just" all places.

## Expected behavior

All the places shown should be from Berlin.

_Note: if this is a syntaxtical issue, we should resolve this in the docs, but for now it is unclear how to only represent results from Berlin._

**Comment by etiennedi** [comment]
@bobvanluijt At first sight the query looks correct and should indeed work as you expect it. Could you provide me with a schema and data set so I can easily reproduce this? Thanks.

**Comment by bobvanluijt** [comment]
Yes, will respond on Slack

**Comment by etiennedi** [comment]
@bobvanluijt  I've tried to recreate this and I think it's working as intended. However, the output can be a bit confusing, let me demonstrate with an example:

This is a result that I'm getting for the above query: ```
{
  "data": {
    "Local": {
      "Get": {
        "Things": {
          "Sentiment": [
            {
              "HasPlaces": [
                {
                  "InCity": [
                    {
                      "name": "Berlin"
                    }
                  ],
                  "name": "Place in Berlin"
                },
                {
                  "InCity": [
                    {
                      "name": "Amsterdam"
                    }
                  ],
                  "name": "Place in Amsterdam"
                }
              ],
              "emotion": "positive",
              "score": null
            }
          ]
        }
      }
    }
  },
  "errors": null
}
```

It might be confusing at first that you see results from both Amsterdam and Berlin in the result set, however that is entirely correct. Here's what's happening:

1. You are asking for Sentiments
2. You only want to include Sentiments where `emotion=positive`
3. You only want to include Sentiments where `score > 7`
4. You only want to include Sentiments which have a Place which is located in Berlin (note that this doesn't mean exclude sentiments which also have a Place which is not in Berlin!)

Then you are displaying the Sentiments with all it's `HasPlaces` cross-refs. The where filters don't filter the output of course, they only filter which concept you select. 

To solve your query, you would need to query "Give me all the all the places which have `inCity.Name=Berlin` which have an **incoming** reference from a Sentiment class where `score>7` and `emotion=positive`." This is currently not possible with weaviate. See my email from Feb 16 10:51 for a proposal to make this possible.

**Comment by bobvanluijt** [comment]
Although I understand. I'm worried that this is confusing from a UX perspective.

Is the proposal also part of an issue @etiennedi?

**Comment by etiennedi** [comment]
> Although I understand. I'm worried that this is confusing from a UX perspective.

If you have a less confusing proposal, I'm all ears.

> Is the proposal also part of an issue @etiennedi?

Don't think so, I'll add it when I find the time.

**Comment by bobvanluijt** [comment]
> If you have a less confusing proposal, I'm all ears.

I hope that the proposal solves this ;-)

**Comment by etiennedi** [comment]
The proposal would add a (new) way to solve your query, however, it would not change the results of the query above. So if you consider it confusing now, it would also stay confusing after the proposal.
