### ISSUE TITLE
Move Explore/Concepts -> Explore, Rename Words->Concepts

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#904]
```gql
{
  Local{
    Explore{
        concepts: ["GTA", "5", "reviews"],
        limit: 100,
        moveTo: {
      		concepts: ["positive"],
		force: 0.5
        },
        moveAwayFrom: {
      		concepts: ["epic"],
		force: 0.25
        }
      ){
        beacon
        className
        distance
      }
  }
}
```

**Comment by etiennedi** [comment]
@bobvanluijt Feel free to use the latest version of the docker-compose file of the mvp2 branch. It now contains both the API changes from #906 and this issue: https://github.com/semi-technologies/weaviate/blob/3539d5e8b3232a5a36fe6e16c04b2427c3b61347/docker-compose/runtime/docker-compose.yml

**Comment by bobvanluijt** [comment]
Check, thanks @etiennedi
