### ISSUE TITLE
Add explore "ranking" objects to GQL

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#906]
This is only about the structure defined in #881 without an actual implementation. This is so that @bobvanluijt can start building scripts and record videos using the API (which will then magically work once #881 is completed)

**Comment by bobvanluijt** [comment]
Awesome, thanks @etiennedi

**Comment by etiennedi** [comment]
Present in `Local { Get }` if you use the this docker-compose file: https://github.com/semi-technologies/weaviate/blob/5c0145c18af3f9712b46aaf17094c134120da04f/docker-compose/runtime/docker-compose.yml
