### ISSUE TITLE
Possible implications of "Vector over Graph" strategy

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#924]
List is WIP ... not complete yet

## Background
We see most opportunities around Weaviate's Vector/Fuzzy abilities and want to move further in that direction. To fully enable this, we want to replace some of the graph powered backends (namely janusgraph) with a purely vector based approach.

## Possible Implications 

| No. | Area | Capability | Previous Status | Technical Implication | UX / Possible Mitigation |
|--|--|--|--|--|--|
| 1 | `Local Get` | nested cross-refs in result set (not filter) | no depth limit | ⚠️ Each cross-ref is a new search query. Complexity moves from O(n) roughly to O(n^d) with d being the depth | Depth must be limited to a very low value (e.g. d=2) |
| 2 | `Local Get` | where filter on primitive props, no refs (including geo location) | no limits | ✅ no limits | |
| 3 | `Local Get` | where filter on nested refs, Example: `path: ["inCity", "City", "inCountry", "Country", "name"], valueString: "Amsterdam"` | no limits | ❌ not possible at all | query will error if user attempts something like this |
| 4 | `Local Get` | where filter on ref one level deep, Example: `path: ["inCity", "name"], valueString: "Amsterdam"` | no limits | ❓ unknown. If we store each cross-ref as a vector point, it might be possible to do a kNN search on the cross-ref prop instead of on the actual centroid. We have to try if this actually works | Needs experiment |

**Comment by bobvanluijt** [comment]
Note: We also need geo location filtering...

**Comment by etiennedi** [comment]
That's not an issue and should be included in no. 2. In fact, the way Janus is currently doing this is also with Elasticsearch :)

**Comment by bobvanluijt** [comment]
Wonderful

**Comment by bobvanluijt** [comment]
_First of all, I understand the challenge and that each nested request prompts a new request. I'm going to make a few assumptions based on how you are planning on storing the data so I might be wrong there._

Some thoughts per bullet.

1. Doesn't this depend on the number of queries? If I go 5 deep but set a limit of 10. This is a very reasonable request, isn't it?
3. This is the one I'm a bit worried about and I'm not sure I understand why this might be an issue (I think you mean `valueString=The Netherlands` btw). If I'm correct you are doing: request to get Cities, nested in this a request to get the related Country, you validate the name of the country, etcetera. I understand this is a compute-intensive task, but I don't understand why it is not possible.
4. That's an interesting point.

I think that if we let go a bit more of the traditional linking and focus more on the vector referencing we might actually get a lot of value. I need to think a bit more about this, though. I'll try to share my thoughts today.

**Comment by etiennedi** [comment]
I assume your bullet 2 references no 3 and 3 references 4. Under this assumption, some answers:

1. Your example leads to up to 10^5 =10,000 searches. That is very far from a reasonable request unfortunately. If a single user request can spawn this many db requests, we cannot build a stable system. As soon as there's a bit of load on weaviate the db load would be unimaginable. Additionally the UX would be very bad, as response times are enourmous. If we need to support such deep searches we need to either
  a. keep a graph backend
  b. build some sort of a reference index per concept at import time or asynchronously (this is essentially what janus does)
  c. limit the amount of references we consider. I.e. even if the user specifies n=10, we only follow the first cross-ref for each result. Then, we end up with 10 * 5 = 50 searches which is far more reasonable. However, if a concept has more than one cross-ref, we will be missing data.
2. n/a
3. What I mean is by impossible, is impossible to have the backend fullfill this request. Of course we can manually do a search for all matching countries first, then for all cities which reference the country (assuming bullet 4 works. If it doesn't, we can't even do that).  However, also then, the limitations from bullet 1 apply. More importantly however, then we cannot combine this with a vector search anymore. I.e. we end up with a list of e.g. 10,000 ids for potential Places which have the correct `inCity-City-inCountry-Contry` association, there is no way way to search for `concepts: ["food"]` on this list. So essentially, whenever a `cross-ref` filter is set, that's the only search we can apply.
4. Yeah, we just need to try this out. I'm hopeful that this will work.

**Comment by etiennedi** [comment]
Update: I have some other ideas. Essentially what we're both just trying to do is force a document db to behave like a graph db. It won't ever do that (well). However, if instead of trying to get something out of ES that it's not we adhere to how ES is structured, we can probably get a large percentage of the same functionality we had before. I have to gather my thoughts and I'll update you with what I mean in more detail later.

**Comment by etiennedi** [comment]
Closing as obsolete.
