### ISSUE TITLE
documentation cardinality example is missguiding

### ISSUE THREAD

**Issue by fefi42** [semi-technologies/weaviate#928]
The example following the explanation of the cardinality is not really supporting the just learned information. 
https://github.com/semi-technologies/weaviate/blob/master/docs/en/use/ontology-schema.md#cardinality

It seems like cardinality is connected to the number of classes that can be connected to the property, while it is actually connected to the number of things/actions(concepts). Further is it is not really helping because an animal rarely lives in both a cage and an aquarium.
Suggestion would be lives in: Country, Climate 
Since an animal can live in multiple countries and climates.

**Comment by bobvanluijt** [comment]
Check

**Comment by bobvanluijt** [comment]
Closing because moved it here.
