### ISSUE TITLE
Proposal for useful distinction between "Text" and "String"

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#930]
We've had the two datatypes `text` and `string` for quite a while but haven't really made a lot of use of it.

## Distinction in elasticsearch
Now that we ware using elasticsearch for answering more and more of our queries, this distinction becomes more necessary. Elasticsearch has two types:

**Keyword**: Example `john@doe.com` will match for `john@doe.com` but basically nothing else. I.e. this is for exact match for exact product names (model names), ids, emails, etc.

**Text**: Example `I've sent an email to john@doe.com`: Is tokenized at import time, will match for individual words, such as "email", "john", etc. Used for full-text search.

## Proposal

I'm proposing to align our datatypes to the ones above, so that

1. `string` behaves like ES `Keyword` (exact matches for IDs, Emails, etc)
2. `text` behaves like ES `Text` (fuzzy* matches, full-text search, etc.)

\* = Note that fuzzy does not mean vector in this case. The entire proposal is only about string/text matching behavior, vector matching is not affected.

cc @bobvanluijt @fefi42 @laura-ham

**Comment by fefi42** [comment]
I think this makes sense to stay close at the definitions of elastic. 

We have to be aware of some side effects of text though. I think during tokenization the `@` and `.` in `john@doe.com` are removed, however such symbols can bear meaning and create context. Especially in cases like `@` and `#`. Would the missing of such characters effect the vector creation?

**Comment by etiennedi** [comment]
@fefi42 

Thanks for your feedback. Some answers:

- Generally I think it's OK to have semantic meaning get lost through tokenization when the `text` property is used. If the user knows that their punctuation is semantically relevant, they should use a `string` field instead.
- Elasticsearch applies the same tokenization at search as at index time. So if a field is imported as `text` and therefore the email would be indexed as `john doe com`, the search query `john@doe.com` would also be transformed. Thus the user is able to find the email by both searching for `john@doe.com` and by searching for `john doe com`. If the type was `string` they'd have to match it exactly.
- In Vector creation we currently only support single words, so we need to strip all non-alphanumeric characters before creating a vector anyway. Not that as of now, `text` and `string` behave identically when talking about vectors. This issue is only about string/text matching.

**Comment by bobvanluijt** [comment]
What if we only would go for "Weaviate string == Elastic text"? That we only store text entities because we want to double down on the fuzzyness we don't need to move in the direction others already have solved...

**Comment by etiennedi** [comment]
I think not being able to filter by something exact like an email address or an ID would lead to a frustrating user experience.

**Comment by bobvanluijt** [comment]
> I think not being able to filter by something exact like an email address or an ID would lead to a frustrating user experience

That makes complete sense to me.

**Comment by etiennedi** [comment]
Note: This will become the default behavior in 0.20.x
