### ISSUE TITLE
Proposal: Add a new ~word~ concept to the Contextionary

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#946]
```sh
$ curl -X POST /v1/c11y/words -d '{
    word: "CTN"
    concepts: ["carton", "cardboard"]
}'
```

This will add the word to the c11y of the local Weaviate.

Thoughts; @fefi42, @etiennedi?

_Originally posted by @bobvanluijt in https://github.com/semi-technologies/internal-support-issuer-tracker/issues/4#issuecomment-519822969_

**Comment by etiennedi** [comment]
Some immediate thoughts:

1. Assuming you meant `/v1/c11y/words`, we can't use the path `POST /v1/c11y/words`, because `GET /v1/c11y/words` already describes a different resource, so either we need to move the get to a different resource or come up with a new resource description for this one (e.g. `POST /v1/c11y/synonyms). If you actually meant `/v1/words` without the `/c11y`, then I think we should change the other API, as it's very confusing to have `words` twice at slightly different paths.
1. All words in the c11y are currently lowercased, we should keep that convention here as well, so the request above would fail, unless the user specified `"word": "ctn"`. 
1. We could extend the `concepts` with weights, however that's also something we can do later (with minimal breaking changes)
1. From a tech perspective, we wouldn't actually add the words to the contextionary, instead we would add a lookup table in front of the contextionary. (Otherwise we'd open a huge can of worms of making the c11y itself stateful) To the user it would feel the same, however, this means, it'll only work efficiently if the amount of custom added words is releatively low compared to the common words. In other words this works to close a gap in the c11y, but it doesn't work to build up an entire industry-specific c11y. 
1. We could consider adding the limitation that the concepts referenced in `"concepts"` need to be words originally present in the c11y, not custom added words themselves. This would make rebuilding the synonym index (for example after a contextionary upgrade) much simpler.

**Comment by bobvanluijt** [comment]
1. Yes, it was `/v1/c11y/words`. Good point regarding the resources, it is indeed another one. I’m not sure about synonyms.
2. Agreed.
3. Ok
4. Ok
5. What numbers are we talking about? How big is “not too big”?

Also, we might want to be able to _extend_ a concept.

**Comment by etiennedi** [comment]
> What numbers are we talking about? How big is “not too big”?
We'd have to try it out. But considering that the "custom words list" is something that a human would have to create anyway, I don't think it'll ever get too big. Once we start using ML models to train the custom words list, we'd probably get into trouble and should start considering a custom c11y instead.

**Comment by bobvanluijt** [comment]
Makes sense, thanks.

**Comment by clunny-slb** [comment]
I have data with lots of acronyms, abbreviations and technical jargon that I think would benefit a lot from this feature.  I think it's a critical one for my application.  This feature has my vote.

**Comment by etiennedi** [comment]
@clunny-slb Always great to hear when our proposed features will directly benefit our users. This feature is currently high up on our prioritization list, but does not yet have an ETA. 

@bobvanluijt @fefi42 
We still need to decide on the endpoint, so far we have the following proposals:
- `/v1/c11y/words` -> ruled out as this is already taken and we don't want to introduce a beaking change
- `/v1/c11y/synonyms` -> so far @bobvanluijt commented "not sure about synonyms"
- Other suggestions?

**Comment by bobvanluijt** [comment]
@etiennedi thinking more about it I like synonyms and now I’m in dubio about `words` 😅

+1 on synonyms from me.

**Comment by bobvanluijt** [comment]
A remark, let's do this in combination with multiple words.

For example [Zip Groove](https://www.glossary.oilfield.slb.com/Terms/z/zip_groove.aspx).

So we would get:

```bash
$ curl -X POST /v1/c11y/words -d '{
    synonym: "zip groove" # or "zipGroove" ???
    concepts: ["reduced diameter section that has been machined..."] # etc.
}'
```

- @etiennedi maybe also have this go to a string as discussed?
- @clunny-slb FYI

**Comment by etiennedi** [comment]
@bobvanluijt

1. your snippet above has `words` in the url which I assume is a mistake, since the body then has synonym. 
2. I'm much in favor of `"zip groove"` (as opposed to `"zipGroove"`) as this is how it would occur both in descriptions written by humans. The fact that we have multiple words in a single request (with a single request) already makes clear that this is a concatenated word.
3. I'm in favor of a single string as opposed to an array

Based on the above my suggestion would be:

```
POST /v1/c11y/synonyms

{
  "synonym": "zip groove",
  "concept": "reduced diameter section that has been machined..." 
}
```

**Comment by bobvanluijt** [comment]
I think it would be good to allow the user to "replace" a concept or to "enhance" a concept.

For example, a user should be able to enhance the meaning of "mars", or to "replace" the meaning of "mars".

Not sure though if that should be done through the method, endpoint or body though.

PS:
@etiennedi I have some ideas regarding the calculation of an "enhanced" word. Let me know if you want to connect about this.
