### ISSUE TITLE
GET /c11/words does not reflect occurence

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#947]
Let's take the following end-point; `/c11y/words/movieActor`.

It seems like the concatenated centroid is using the "old" way of concatenating and not using the word occurrences like the algo that is used to calculate the centroid of a new thing or action.

**Comment by etiennedi** [comment]
The occurrence feature was added in contextionary version [enX.X.X-v0.3.2](https://github.com/semi-technologies/contextionary/releases/tag/en0.8.0-v0.3.2). Which version are you using, maybe you're just using an older one than that?

**Comment by bobvanluijt** [comment]
Aha, so just to make sure, the functionality used in [these endpoints](https://github.com/semi-technologies/weaviate/tree/master/client/contextionary_api) comes 100% from the [C11y-service](https://github.com/semi-technologies/contextionary). It couldn't be the case that we have some _old calculation legacy_?

**Comment by etiennedi** [comment]
Hm, good point. There might acutally be some leftovers in the handler itself, which means they might not make use of the new centroid building. 

When we build the centroids in `explore: { concepts: [ ] }` for example, I know for a fact that it's used.

I'll investigate about the endpoint.

**Comment by bobvanluijt** [comment]
> I'll investigate about the endpoint

I would appreciate that.

**Comment by etiennedi** [comment]
You are indeed correct, the c11y has some legacy code (there's even a big TODO at the top mentioning that this logic should be removed from the handler) and it does not do any occurence based weighing. I'm adding the bug label to this issue and renaming the title to fix it.

**Comment by bobvanluijt** [comment]
Aha, fantastic, good to know.

@fefi42 please note a dependency for your classification work on this one.

**Comment by etiennedi** [comment]
I'll prioritize this accordingly, but it'll probably be next week, before we have a fix on this.

**Comment by bobvanluijt** [comment]
Thanks 🙏
