### ISSUE TITLE
CORS issue for Firefox and Safari

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#958]
When loading Weaviate resources through Firefox or Safari. The error: `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8080/v1/schema. (Reason: missing token ‘content-type’ in CORS header ‘Access-Control-Allow-Headers’ from CORS preflight channel).` pops-up.

**Comment by etiennedi** [comment]
Interesting, am I correct to assume that this is not an issue with Chrome? (It seems we're all using Chrome, so this might have gone completely unnoticed so far)

How can I reproduce this? Access the playground in Firefox/Safari? Then do what?

**Comment by bobvanluijt** [comment]
Correct

Reproduce;
- run local Playground (Docker)
- use a browser which is not Chrome

**Comment by etiennedi** [comment]
## Problem analysis

We were sending `Access-Control-Allow-Headers: *` in the OPTIONS preflight. However, it seems the spec doesn't allow a `*` wildcard, but wants to list explicit headers. I guess Chrome isn't too strict here, but Firefox and Safari are.

I'm just setting the required headers explicitly and test it out locally with all three browsers. Expect a patch coming soon.

**Comment by etiennedi** [comment]
fixed in 0.19.4
