### ISSUE TITLE
Splitting for vector position calculation

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#959]
When creating the centroid for a concept class. Weaviate should not only split by string, but rather by non-alphabetical characters.

Examples:

- `foobar baz baq` => `[foobar, baz, baq]`
- `foo-bar baz baq` => `[foo, bar, baz, baq]`
- `foo-bar, baz, baq` => `[foo, bar, baz, baq]`
- `foo-bar, b&z, baq` => `[foo, bar, b, z, baq]`
- `foobar baz#(*@@baq` => `[foobar, baz, baq]`

Idea:
Maybe this can be combined with: https://github.com/semi-technologies/weaviate/issues/952

**Comment by etiennedi** [comment]
Moved to https://github.com/semi-technologies/contextionary/issues/7 as weaviate is agnostic of how words are split, all splitting is done in the contextionary svc.
