### ISSUE TITLE
Accepted UTF-8 characters

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#961]
Accepted characters should include:
- https://gist.github.com/bobvanluijt/8904e054c3e52d614624e54fd479691d
- `0123456789`

Classes and properties **can't** contain numbers.

Also note: https://github.com/semi-technologies/weaviate-vector-generator/issues/13

**Comment by etiennedi** [comment]
Could you specify where those characters should be accepted? In addition does that mean other characters should always not be accepted?

Off the top of my head I can see the following cases:

* Class Names
* Class Property Names
* Class Keywords
* Property Values of Type String
* Property Values of Type Text
* ... possibly more

**Comment by bobvanluijt** [comment]
- all characters that [match](https://gist.github.com/bobvanluijt/8904e054c3e52d614624e54fd479691d) should _always_ be accepted (regardless if they are a class, value, etc).
- CamelCase Weaviate-structure stays unchanged (**C**lass, **p**roperty and concatenate**W**ords).
- Numbers are only accepted in non-classes and non-properties.

**Comment by etiennedi** [comment]
What about characters not mentioned in the above lists in either `string` or `text` props? Should they stay accepted or be denied?

**Comment by bobvanluijt** [comment]
accepted but ignored. _Except_ for classes and properties.
