### ISSUE TITLE
Suggestion: filter for number of cross-refs

### ISSUE THREAD

**Issue by fefi42** [semi-technologies/weaviate#969]
Example:
Be **City**, **District** classes and **City 1-n District** possible references.
Then a filter for the number of cross references would show all cities with **less than x**, **more than x**, **exactly x** districts.

```
{
  Get {
    Things {
      City (where: {
        path: ["hasDistricts"]
        operator: CardinalityLessThan
        valueInt: 2
      }) {
        name
      }
    }
  }
}
```

**Comment by etiennedi** [comment]
Closed through #1101
