### ISSUE TITLE
Many to many limit and page support with > 0.20.X setup

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#970]
In the Janus setup, we had problems with a many-to-many relationship which might be resolvable with the ES setup.

For example: let say we have 20K restaurants and two types of reviews (positive and negative). And take the following GQL query:

```graphql
{
  Get{
    Things{
      Review{
        name
        hasRestaurants{
          ... on Resaurant{
            name
          }
        }
      }
    }
  }
}
```

We can currently limit the number of reviews but _not_ the restaurants.

## Suggestion

Include a limit and pagination for many to many relations.

For example:

```graphql
{
  Get{
    Things{
      Review{
        name
        hasRestaurants(
          limit: 250,
          page: 2
        ){
          ... on Resaurant{
            name
          }
        }
      }
    }
  }
}
```

PS:
Any thought from a UX perspective @laura-ham?

**Comment by laura-ham** [comment]
I'm in for implementing the `limit` argument here. 

So far we don't offer pagination in gql, but that was because Janusgraph didn't offer pagination (for free). (https://github.com/semi-technologies/weaviate/issues/745). I don't know how this would work now we switched to ES? If this is possible here, then I would implement a `page` argument next to every `limit` argument. If not, then we can also not offer is here.

**Comment by etiennedi** [comment]
Limit should be no problem at all, pagination should definitely be possible, but I need to look into how we'd want to do that. As of now cross-refs have no order, so right now we don't have any criterium to decide which results would go on which page. However, we could come up with something arbitrary like ordering beacons alphabetically.

**Comment by StudioSpindle** [comment]
@etiennedi  How about using an offset param? https://www.apollographql.com/docs/react/data/pagination/#offset-based

**Comment by StudioSpindle** [comment]
Not sure if this is related, but instead of pagination you could also use connection specification: https://facebook.github.io/relay/graphql/connections.htm#sec-Forward-pagination-arguments

Forward or backward.

**Comment by bobvanluijt** [comment]
Note, this is still relevant
