### ISSUE TITLE
Organise many to many with explore function > 0.20.X setup

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#971]
Related to: https://github.com/semi-technologies/weaviate/issues/970

If the above-mentioned issue is solvable. We might want to include sorting through exploring.

## Suggestion

_The graphql query will most probably be self explanitory_

```graphql
{
  Get{
    Things{
      Review{
        name
        hasRestaurants(
          limit: 250,
          explore: {
            concepts: ["pizza"]          
          }
        ){
          ... on Resaurant{
            name
          }
        }
      }
    }
  }
}
```

**Comment by etiennedi** [comment]
This should be possible (albeit non-trivial), but I'm not sure if this would actually achieve what you are intending. 

The above would:

1. List all Reviews (regardless of of their relation via `hasRestaurants`)
2. For each Review, out of all the `hasRestaurant` references it would rank them by the concept `pizza`. So if a `Review.hasRestaurants.Restaurant` has no relation to pizza, we'd still show all 250 Restaurants (ranked by "pizza")

This would only really make sense if you have a single (or very few) `Review` object. However that in turn leads to super-node behavior and is not ideal. 

Wouldn't it be much more powerful to have this as part of the where filter? E.g. Give me all the Reviews where the hasRestaurants->Restaurant relationship is close to "pizza"?
