### ISSUE TITLE
Classification: index every text prop separately

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#982]
... and then classify based on the specified prop.

**Comment by bobvanluijt** [comment]
@etiennedi is this still relevant?

**Comment by etiennedi** [comment]
It is a requirement for #1028 with the current setup. However, depending on the results of #1118 this architecture will probably change, so I'm fine with it staying closed for now and then we see what we need when we actually implement 1028.

**Comment by bobvanluijt** [comment]
Cool
