### ISSUE TITLE
Suggestion: ~auto~ contextual classification

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#987]
# Use Case

Let's say we have two things of the class `Country` and with the properties `name` and `hasCapital` and the `hasCapital`'s are unset.

```js
{
  "Country": {
    "name": "Germany",
    "hasCapital": null // in the schema connected to City
  }
}
```

```js
{
  "Country": {
    "name": "The Netherlands",
    "hasCapital": null // in the schema connected to City
  }
}
```

and we would have two cities:

```js
{
  "City": {
    "name": "Copenhagen"
  }
}
```

```js
{
  "City": {
    "name": "Berlin"
  }
}
```

We want to kick-off a classification that auto connects the cities to the hasCapitals.

The expected result here is to set Germany but to not set The Netherlands.

# Suggested API request

`POST /classifications`

object:

```js
{
  "class": "Country",
  "classifyProperties": [
    "hasCapital"
  ],
  "basedOnProperties": [
    "name"
  ],
  "type": "auto", // auto classification as a name ???
  "certainty": 0.8 // how certain should it be before connecting?
}
```

# Suggested approach

I would suggest, for MVP, to take the following steps:

1. We know with the above request that `hasCapital`_must_ match with `City`.
2. Loop over all `Countries`'s and check which is closest to the object as set in `basedOnProperties` _and_ the class itself (so in this case: "City + name + Copenhagen" and "City + name + Berlin")
3. If the highest value is `> certainty`, set it.

**Comment by bobvanluijt** [comment]
cc: @etiennedi & @fefi42

**Comment by bobvanluijt** [comment]
I'm for it, would be interested in @laura-ham's idea for a name for this classification.

**Comment by etiennedi** [comment]
@laura-ham Did you have a chance to look at this and form an opinion on a possible name?

**Comment by laura-ham** [comment]
I'm not sure about the name here, because I don't fully understand the difference between a `"type": "knn"` classification. Are they fully exclusive, i.e. is `contextual` not using any `knn` feature using at all?

**Comment by etiennedi** [comment]
@laura-ham 

In kNN we do the following:
- There are 5 source objects and 2 target objects
- Out of the 5 source objects there must be at least one which already has a reference to a target. We consider these training data or "classified objects", the remaining four are considered "unclassified objects"
- For each unclassified item, we do a kNN-search of classified objects **of the same class type**. Out of all the results (some point to target 1, some to target 2), we take the most common target and set this target for our unclassified item.

In summary: in kNN we search for the closest objects **of the same type** which have already been classified and adopt their reference. The more accurate traning data there is, the better the results become.

In the proposed auto/contextual classification we do the follwing:
- There are 5 source objects and 2 target objects
- Out of the 5 source objects not a single one already has a reference to one of the targets. Or if they do, they have no influence on the classification, they are simply ignored.
- For each unclassified object we compare which potential target (target 1, target 2, ...) has the lowest distance to the unclassified object itself. Whichever has the  lowest distance is set as the target for the unclassified object.

In summary: in contextual we search for the **target objects which are closest to the source** and set the winner. Other classified or unclassified objects of the same type have no influence on the classification, each classification is entirely independent of training data, it only compares the current source to a potential target.

Does this help clear things up?

**Comment by laura-ham** [comment]
@etiennedi Thanks so much, this explanation is very clear, and makes total sense! 

Then, I also agree that `auto` would not be the best name, because this could mean so many other things. I vote for `contextual` to keep in the flow of the word `contextionary` users should already be familiar with.

**Comment by etiennedi** [comment]
Closing as complete.
