### ISSUE TITLE
Results of GraphQL Explore function are not always sorted based on `certainty` when move parameters are set

### ISSUE THREAD

**Issue by laura-ham** [semi-technologies/weaviate#995]
The results of the GraphQL Explore function are not always sorted on the certaintly level, although they should be.

**Comment by bobvanluijt** [comment]
@etiennedi was this already resolved?

**Comment by bobvanluijt** [comment]
This seems more severe than initially thought. @laura-ham can give more context

**Comment by laura-ham** [comment]
The following Get(explore){} query results in a list of data objects that I assume are sorted based on their certainty level. The results make sense.

![image](https://user-images.githubusercontent.com/26965746/95325333-555f5500-08a1-11eb-88e1-72e2d5481eeb.png)

When `moveTo` and `moveAwayFrom` fields are added to the explore filter, I get very strange results. This only happens if the `force` is set high (like 0.9 here) to have an influence on the results.

![image](https://user-images.githubusercontent.com/26965746/95325292-44aedf00-08a1-11eb-9a22-71dddb878a54.png)

The first assumption was that there are no matching articles to this search query, but after investigating the `certainty` of individual results, it appears that there are results that are closer to the search query further down the result list. See in the following image:
- The color indicates the certainty of the data object matching the explore search query
- The plot is generated with t-sne
- The article that was listed first in the graphql result list does not have the highest certainty. It has a lower certainty, but still listed on top. See the certainty in the most right column of the dataframe. (the first row is the search query, where certainty is the average of all certainties of the results)

![image](https://user-images.githubusercontent.com/26965746/95325637-c868cb80-08a1-11eb-8a02-6df8968a52b8.png)

**Comment by etiennedi** [comment]
Closing in favor of #1267.

Our investigation has shown that the certainty calculation is correct. However, we now think that the way we do a `moveAwayFrom` is conceptually not idea.
